### ISSUE TITLE
Doc Rebuild Needed? Broken link, fixed in .Rmd but not html

### ISSUE THREAD

**Issue by katrinabrock** [stan-dev/cmdstanr#1004]
There is a broken link on this page: https://mc-stan.org/cmdstanr/articles/opencl.html

Seems to have been fixed by this commit: https://github.com/stan-dev/cmdstanr/commit/2aff80922a40008dbd164567476ce15f0fc48ad6

However, in corresponding HTML file still has the old/broken link.

https://github.com/stan-dev/cmdstanr/blob/284a10cda8f7db6eb8e77667d3cf7de569b06988/docs/articles/opencl.html#L185

**Comment by jgabry** [comment]
Thanks, yeah I think we need to regenerate the html for the whole website! Will do that ASAP. 

> Similarly...this commit [2709bb1](https://github.com/stan-dev/cmdstanr/commit/2709bb10fd23bbc44b45d39720b5f53ffbddaeeb) hasn't been deployed to the website so the current version's code doesn't work with recent versions.

Strange, for me this one does actually appear to be updated on the website. At https://mc-stan.org/cmdstanr/articles/articles-online-only/opencl.html#compiling-a-model-with-opencl I see the new array syntax: 

```
data {
  int<lower=1> k;
  int<lower=0> n;
  matrix[n, k] X;
  array[n] int y;
}
```

but regardless we definitely need to update the website. Thanks for pointing this out!

**Comment by jgabry** [comment]
Should be updated now. Thanks again for letting us know.

**Comment by katrinabrock** [comment]
@jgabry Thanks for looking into it!

The version I originally linked is different from the one you linked. The one I linked still exists and is out of date.

That HTML file seems like a relic from before this commit: https://github.com/stan-dev/cmdstanr/commit/0b9b040d887f99d60a03563382ef6d8a3f2e0b9a

You can see the outdated html file still exits here: https://github.com/stan-dev/cmdstanr/blob/master/docs/articles/opencl.html

And the updated one here: https://github.com/stan-dev/cmdstanr/blob/master/docs/articles/articles-online-only/opencl.html

Seems like the doc rebuild does not remove html files that were generated from Rmd which no longer exist. Maybe there is a setting to change that? Or just identify and manually delete the html files? (Or better replace them with a link to the new version in case anyone bookmarked it.)

I'm not sure how I stumbled upon the outdated vignette. Google perhaps? It doesn't seem to be linked from other parts of the site.

**Comment by jgabry** [comment]
Oh good point! I think a while back we changed the directory where the OpenCL vignette lives and forgot to remove the old version. So the doc rebuild does override the newer version of the OpenCL vignette (at https://github.com/stan-dev/cmdstanr/tree/master/docs/articles/articles-online-only) but there's still that older version in the other directory that we never got rid of. I will just delete it from the docs directory.
