### ISSUE TITLE
`$format(canonicalize = list("deprecations"))` fails for array syntax

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/cmdstanr#1007]
**Describe the bug**
Using the canonicalize option with deprecations results in a syntax error.

**To Reproduce**
The example code in the package documentation fails with a syntax error:

```
file <- write_stan_file("
parameters {
  real x[2];
}
model {
  x ~ std_normal();
}
")

# set compile=FALSE then call format to fix old syntax
mod <- cmdstan_model(file, compile = FALSE)
mod$format(canonicalize = list("deprecations"))
```
Yields:

```
    1:  
     2:  parameters {
     3:    real x[2];
                  ^
     4:  }
     5:  model {
   -------------------------------------------------

";" expected after variable declaration.
It looks like you are trying to use the old array syntax.
Please use the new syntax:
array[2] real x;
```

**Expected behavior**

I'd expect the new Stan program to have the following array syntax:

`array[2] real x;`

**Operating system**
Mac OS X 10.14.5

**CmdStanR version number**
Your CmdStanR version number (e.g. from `0.8.1`).

**Additional context**

**Comment by andrjohns** [comment]
This is CmdStan behaviour, not CmdStanR. The CmdStan canonicaliser does not support deprecated array syntax past v2.34. I'd recommend opening an issue upstream if you'd like this behaviour changed

**Comment by rtrangucci** [comment]
Thanks @andrjohns, that's helpful. It might be worth changing the example in the cmdstanr documentation then, it's confusing to see the example fail.

**Comment by andrjohns** [comment]
> Thanks @andrjohns, that's helpful. It might be worth changing the example in the cmdstanr documentation then, it's confusing to see the example fail.

Ah I missed that example in the doc! Thanks for pointing it out, will remove now
