### ISSUE TITLE
Import and use models made with brms or rstanarm

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#103]
I think this basically means support supplying the model as a string.

This one was suggested by @stevebronder, just putting it out there so it doesnt get missed.

**Comment by mitzimorris** [comment]
why does this require model as a string?  why not add a mechanism that lets the user create a named file somewhere and save the model?

**Comment by mitzimorris** [comment]
@jgabry opinions?
I know that we can add in features to allow this, but it's bad practice - the compiler works from *files*  - we should make it easy for the user to see and find these files.  not r-thonic?

**Comment by rok-cesnovar** [comment]
> why not add a mechanism that lets the user create a named file somewhere and save the model?

I am fine with that. Will wait for feedback before proceeding.

**Comment by jgabry** [comment]
That makes sense to me!

**Comment by mitzimorris** [comment]
CmdStanPy allows you to specify the compiled exe file without corresponding stan file - this would also be a way to run CmdStanR and BRMS models

**Comment by mitzimorris** [comment]
that is, when instantiating a CmdStanModel object, it can take either a stan_file or an exe_file arg - can also take both, and if exe file is newer than stan file, will skip compile step.

**Comment by jgabry** [comment]
that also sounds good!

**Comment by rok-cesnovar** [comment]
Also see https://github.com/paul-buerkner/brms/issues/891 
Will help Paul with this one.
