### ISSUE TITLE
Add method to return the CmdStan version used

### ISSUE THREAD

**Issue by mcol** [stan-dev/cmdstanr#107]
It would be nice to have a `$version()` method that reports the version of CmdStan used to compile/run a model. Perhaps this could also report the cmdstanr version. I don't have an opinion whether this should be part of the CmdStanModel or the CmdStanFit class (or both?).

This would be useful when helping users to debug problems, or to programmatically find the version numbers say in the context of reproducible research.

**Comment by rok-cesnovar** [comment]
You do have `cmdstan_version()`. The docs a grouped together with `set_cmdstan_path()`

**Comment by mcol** [comment]
Right, that's good enough for most uses. For me it says "2.21.0", although I'm using the current head of the CmdStan develop branch, but that's more of a CmdStan issue.

For the time being I'm going to send a tiny patch to mention that in the vignette.

**Comment by rok-cesnovar** [comment]
Yeah, we read https://github.com/stan-dev/cmdstan/blob/develop/makefile#L47 and return that. 

@mcol Thanks!

**Comment by rok-cesnovar** [comment]
The point about being checking whether you are on develop is a good one. I thought about that in the past, to allow some features if you are using a clone of cmdstan. But you then have a problem that someone is working on a branch that is behind the stan-dev develop and we would have to account for those. And that might be a hassle. But if someone would find knowing that info being useful, do open an issue and we can discuss further.
