### ISSUE TITLE
Simplify debugging for potential parser issue

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#115]
Cmdstan 2.22 uses the new parser (stanc3) and we should add a simple interface to switch to the older parser for debugging purposes.

That would simplify debugging issues like https://github.com/stan-dev/math/issues/1643 that turned out to not be related to the parser.

compile() should accept something like (use_stanc2 = TRUE), that would be turned off by default. This should only be allowed for 2.22 and up until he version where the existing compiler will be phased out.

**Comment by mitzimorris** [comment]
great idea - filed https://github.com/stan-dev/cmdstanpy/issues/202 - can argument be simply `stanc2` instead of `use_stanc2`?

**Comment by rok-cesnovar** [comment]
Yeah, definitely. Also think this should print a warning that the flag is on and should only be used to debug.

**Comment by mitzimorris** [comment]
this isn't feasible as a flag on the `compile` function given current CmdStan makefiles - right now CmdStan assumes that there is only one compiler - bin/stanc - and it builds it either from Stanc2 sources or uses the release or nightly build binary.
putting this flag on the `compile` function assumes that both compilers are available.  will file an issue on CmdStan to make this happen.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstan/issues/819

**Comment by rok-cesnovar** [comment]
I am going to close this one for two reasons: 
- we cant do this for 2.22 as that needs a make clean and build
- will be fixed by addressing #121
