### ISSUE TITLE
after fitting model, tell user to run `diagnose`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#118]
**Describe the issue**

RStan is able to diagnose divergences as part of the `stan` and `sampling` functions, but in CmdStanR breaks this into 2 steps in order to keep memory overhead low.  Because RStan users expect diagnostics as part of fitting, we need to make it clear that they need to do this for themselves.

**CmdStanR version number**
Your CmdStanR version number (e.g. from `packageVersion("cmdstanr")`).

**Comment by rok-cesnovar** [comment]
Thanks! 

This is already being addressed in #95. See https://github.com/stan-dev/cmdstanr/pull/95/files#diff-cbb7235afee10c3646161358a7655b0aR379 for some more details of what the users will see if there are divergences or max tree depth was hit.

**Comment by rok-cesnovar** [comment]
Closing, as after #95, cmdstanr does warn on divergences and max treedepth hits. https://github.com/stan-dev/cmdstanr/issues/125 will add the option for not doing that.
