### ISSUE TITLE
Enable running pre-built models

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#120]
This is a question to see how other see this feature. This is a use-case that would help maintaining some of the projects I am involved with, but I do not want to force it in cmdstanr if others dont see it as useful.

**Description:** 

Enable the users to run pre-build models using cmdstanr. This is useful for when you want to ship a pre-built Stan model as an executable to the end-user (for their OS) and enable them to easily use it via R. This is mainly so that they dont have to deal with any installation of compilers and toolchains if they are only interested in one specific model. Its probably not a really common use case.

Proposed use would be: 
`mod <- cmdstan_model(exe = "path/to/pre-built/exe/file)`
and the rest is then as usual.

**Comment by jgabry** [comment]
I agree it's not the most common use case but I'm ok with adding this functionality

**Comment by mitzimorris** [comment]
FWIW, you can do this in CmdStanPy
