### ISSUE TITLE
Error in gsub(addnlpat, "\\1\n", str) 

### ISSUE THREAD

**Issue by Inferrator** [stan-dev/cmdstanr#124]
**Describe the bug**
Upon calling `$sample`, I get the following error:
```
Error in gsub(addnlpat, "\\1\n", str) : 
  invalid regular expression '(.{1,276})(\s|$)', reason 'Invalid contents of {}'
```

**To Reproduce**
Using the example, i.e.
```
 file_test = file.path(paste0(getwd(),'/stan/ex.stan'))
    mod_test  = cmdstan_model(file_test,compile = FALSE)
    mod_test$compile(threads=FALSE)
    fitcs_test = mod_test$sample(data = data_list, num_chains = 1, num_cores = 1)
```
where `ex.stan` contains the example binomial model from the cmdstanr page
I does not always reproduce, and I am still trying  to find out what causes the issue.

**Operating system**
```
1 sysname        Linux                              
2 release        5.5.5-911.native                   
3 version        #1 SMP Wed Feb 19 15:03:47 PST 2020
4 machine        x86_64                             
5 login          user                               
6 user           user                               
7 effective_user user 
```
This is Clear Linux running R 3.6.2 and cmdstanr 0.0.0.9.
I have had this error once before, then it worked again, and now I am getting the error again. I have no idea what changed in between.

**CmdStanR version number**
```
‘0.0.0.9000
```

**Comment by rok-cesnovar** [comment]
Thanks for the report. 

Is there any additional info with the error message? There is no gsub(addnlpat, "\\1\n", str) in our codebase but could be an issue with interfacing some of the dependant packages.

**Comment by Inferrator** [comment]
I also loaded 'rstan' and 'tidyverse'.
I also have a few settings in the beginning of my script:
```
    cores=12
    options(mc.cores = cores)
    Sys.setenv(STAN_NUM_THREADS = cores)
    set_num_threads(cores)
```

**Comment by mcol** [comment]
Could you post the result of `traceback()` immediately after you get that error?

**Comment by rok-cesnovar** [comment]
Going to close this due to inactivity. Please reopen if still an issue.
