### ISSUE TITLE
bugs in new diagnostic warnings?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#127]
@rok-cesnovar @bbbales2 I should have noticed these earlier (sorry!) but I think the diagnostic warnings aren't quite right. 

* When running 4 chains I get warned that e.g. 100 of 1000 transitions ended in a divergence, but shouldn't this say 4000 instead of 1000? 

* When `thin` is specified the divergence warnings give different number of divergences than the `fit$cmdstan_diagnose()` method. I'm not sure what's going on here.

**Comment by jgabry** [comment]
Also, related to the issue with `thin`, is our code set up to handle cases when the number of iterations isn't divisible by `thin` (e.g. num_samples = 1000, thin = 3)? We probably need a floor or ceiling or something to avoid getting 333.33 draws.

**Comment by rok-cesnovar** [comment]
A refactor that will fix this issue is ready and is coming after we merge #126

**Comment by rok-cesnovar** [comment]
Will check the thin case, and add a test.

**Comment by jgabry** [comment]
Great thanks!
