### ISSUE TITLE
Initialization failure messages are suppressed

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#128]
**Describe the bug**

CmdStan's messages about initialization failure aren't being output by CmdStanR.

**To Reproduce**

This Stan program will give messages about failure to initialize if run in CmdStan but in CmdStanR we only get the message at the end about chains finishing unexpectedly but we don't get the messages about initialization failing. 

```stan
parameters {
  real mu;
}
model {
  target += negative_infinity();
}
```

**Comment by jgabry** [comment]
@mitzimorris had the insight that this is because these messages go to stdout instead of stderr

**Comment by rok-cesnovar** [comment]
Yeah, that makes sense. I will see if we can just regex it in. Otherwise we can do something along the lines of what cmdstanpy does and print stdout if chains fail.

**Comment by jgabry** [comment]
Sounds good, thanks!
