### ISSUE TITLE
check_sampling_csv_info_matches returns error when two csv's have different init files

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/cmdstanr#131]
**Describe the bug**
By not having `init` in `dont_match_list` it errors out when two samples are run using two different init files.

**To Reproduce**
Using the following sample files
[pk3cpt3.zip](https://github.com/stan-dev/cmdstanr/files/4268844/pk3cpt3.zip)

```r
> x <- read_sample_csv(c("pk3cpt3-202002271723-1.csv", "pk3cpt3-202002271723-2.csv"))
Error in read_sample_csv(c("pk3cpt3-202002271723-1.csv", "pk3cpt3-202002271723-2.csv")) : 
  Supplied CSV files do not match in all sampling settings!
```

**Expected behavior**
read w/o issue, like `rstan::read_stan_csv`

**Operating system**
mac os 10.14.6

**CmdStanR version number**
version 0.0.0.9000

**Comment by rok-cesnovar** [comment]
Thanks! Yeah line 16 here: https://github.com/stan-dev/cmdstanr/blob/master/R/read_csv.R#L16  should include the init file.

Or we change this to a match list. Now that I think of it, the things that must match are only the param names and number of samples. If we are saving warmup the number of warmup samples must also match so we can merge chains.
