### ISSUE TITLE
Consistent argument names - "num_cores" should be "cores"; "num_chains" should be "chains"

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#136]
**Is your feature request related to a problem? Please describe.**

The names "cores" and "chains" are used in both RStan and CmdStanPy.  "num_chains" might be more correct, but it's confusing to users coming from RStan.

**Describe the solution you'd like**
Please rename to just "chains" and "cores"

**Describe alternatives you've considered**
Was going to make CmdStanPy match this, but then it was pointed out that RStan and PyStan also use "chains" and "cores".

**Comment by jgabry** [comment]
I thought the point was to be consistent with CmdStan rather than RStan and PyStan? I know `num_chains` and `num_cores` don't exist for CmdStan but those names are consistent with CmdStan's `num_warmup` and `num_samples`.

**Comment by jgabry** [comment]
This is related to https://github.com/stan-dev/cmdstanpy/issues/221

**Comment by jgabry** [comment]
@mitzimorris @rok-cesnovar @bbbales2 I think if we use `num_warmup` and `num_samples` then we should use `num_chains` and `num_cores`. If we want to go with `cores` and `chains` I think we should rethink the rest of the names to make them consistent with those. 

I'm ok with @bob-carpenter's preference (in stan-dev/cmdstanpy#221) of picking names that we want to use for CmdStan3, but in that case we should go over _all_ the names again with that goal in mind. 

What do you all think?

**Comment by mitzimorris** [comment]
sounds good!
I would love to get traction on CmdStan3 - there's a proposal in the design-docs repo - discuss there?
https://github.com/stan-dev/design-docs/pull/15

**Comment by rok-cesnovar** [comment]
I honestly dont have a strong preference on names, other than things are consistent in at least the cmdstan* world. Redesigning names with cmdstan3 sounds like a good plan to me.

**Comment by mitzimorris** [comment]
spreadsheet comparing sampler controls available from RStan/PyStan and CmdStan -
https://docs.google.com/spreadsheets/d/1lU6vcY3GF_ftlFdCe2kDhr5FC4YJPWauC5bp2D9zz74/edit?usp=sharing

cells in yellow flag names that we'd like to change.
cells in green flag names we don't want to expose.

how does this work for CmdStanR?
alternative to names "num_samples", "num_warmup":  "iter_warmup", "iter_sampling" - more RStan-like?

**Comment by bob-carpenter** [comment]
This is really helpful.  

The seed isn't specified on a per-chain basis.  Instead, a seed is specified and a chain ID, then a single RNG is used and advanced a gazillion draws for each chain.  The id should not be ignored.

CmdStan3 is probably also going to want to specify output directory because we'll probably be outputting more than one file.

I'm agnostic on step_size vs. stepsize given that we have the latter now.

I want the adapt buffer and window controls.  For example, it's necessary to adapt step size without adapting the metric.  I'd love to see more descriptive names.  The init buffer is for finding the typical set, the term buffer is for final step size adaptation, and the window is the initial size for an exponentially growing number of draws used to estimate the metric.

I've never used the dual averaging adaptation parameters so am agnostic about exposing those.

**Comment by jgabry** [comment]
> sounds good!
> I would love to get traction on CmdStan3 - there's a proposal in the design-docs repo - discuss there?
> [stan-dev/design-docs#15](https://github.com/stan-dev/design-docs/pull/15)

Yeah I'll start commenting over at the design-docs repo. Thanks

**Comment by jgabry** [comment]
@rok-cesnovar @mitzimorris Working on this now

**Comment by jgabry** [comment]
@rok-cesnovar @mitzimorris Do you think it's worth deprecating the old argument names or just breaking backwards compatibility? We haven't been guaranteeing backwards compatibility since we haven't done a release yet, but I know people are using it already.

**Comment by mitzimorris** [comment]
how long do you think backwards compatibility should be supported?
in R, when you do a package update, is there any way to display a message - like "API changes docs <link>".

**Comment by rok-cesnovar** [comment]
> how long do you think backwards compatibility should be supported?

At most until we bump the major version, which will be 1.0.0

**Comment by mitzimorris** [comment]
supporting until 1.0.0 sounds reasonable.

**Comment by jgabry** [comment]
> in R, when you do a package update, is there any way to display a message - like "API changes docs see <link>".

Not during updating, but we can display messages when the package is loaded.

**Comment by mitzimorris** [comment]
most users will be new users, so this message wouldn't be useful - at worst, it will make a bad first impression.

**Comment by jgabry** [comment]
Yeah that's true
