### ISSUE TITLE
function "summary" requires rlang 0.4.5, not captured as a dependency?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#143]
I've authored a Google Colab notebook.  I appears that currently, the Colab R environment has `rlang` version 0.4.4, but CmdStanR requires 0.4.5.   I'm installing CmdStanR using the following command, in order to minimize install time:

```
devtools::install_github("stan-dev/cmdstanr", dependencies=c("Depends", "Imports"))
```

when I run the `summary` command, I get an error about Rlang version.
current notebook is here:

https://github.com/stan-dev/example-models/blob/case-study/stan-cloud/knitr/cloud-compute-2020/CmdStanR_Example_Notebook.ipynb

**Comment by rok-cesnovar** [comment]
Are you sure on this?

Ran
`install.packages("https://cran.r-project.org/src/contrib/Archive/rlang/rlang_0.4.4.tar.gz", repos=NULL, type="source")`

and the example model ran fin.

**Comment by jgabry** [comment]
Closing this, but we can reopen in the posterior package if still an issue.
