### ISSUE TITLE
[Travis CI] add github credentials to avoid Github API limits

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#150]
Travis CI tests were getting 403 errors when accessing the Github API for Cmdstan release info

See https://travis-ci.org/github/stan-dev/cmdstanr/jobs/666702075?utm_medium=notification&utm_source=github_status

For now Travis tests have a manually set tar URL to test with to avoid this issue: https://github.com/stan-dev/cmdstanr/blob/master/.travis.yml#L23

This might actually be just fine (we move to testing with the next version manually - more control but some manual work on releases). We can close this if this fine with you @jgabry.

The alternative is to add credentialed requests to the Github API if the credentials are available in environment variables for example.

This bug does not effect the end users.

**Comment by rok-cesnovar** [comment]
Same issue for Appveyor: 
```
In utils::download.file(url = download_url, destfile = destination_file,  :
  cannot open URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest': HTTP status was '403 rate limit exceeded'
```

**Comment by jgabry** [comment]
> This might actually be just fine (we move to testing with the next version manually - more control but some manual work on releases). We can close this if this fine with you @jgabry.

@rok-cesnovar I'm ok with that. 

> The alternative is to add credentialed requests to the Github API if the credentials are available in environment variables for example.

Do you know how to do that? I'm also ok with going this route but not exactly sure what that entails.

**Comment by rok-cesnovar** [comment]
> Do you know how to do that?

Yes, we put the Github credentials (secret tokens) as Appveyor/Travis environment variables. We could take the @stan-buildbot's credentials. Not a big deal but something to work on after we release beta.

**Comment by jgabry** [comment]
> We could take the @stan-buildbot's credentials. Not a big deal but something to work on after we release beta.

Ok cool

**Comment by rok-cesnovar** [comment]
Closing in favor of #176
