### ISSUE TITLE
Threading on by default

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#153]
Can we have threading on by default?

That way using `reduce_sum` doesn't require you to do:

```
model = cmdstan_model("model.stan", threads = TRUE)
```

And it'll just be on by default. @mitzimorris since I'd like this in cmdstanpy too. Otherwise I think people will be using reduce_sum and wondering why they aren't seeing speedup!

**Comment by mitzimorris** [comment]
you mean threading on by default always?
IIRC, there's a problem with model compilation - because we now compile model class seperately from cmdstan, there's linker errors if there's a mismatch between how they were compiled - @rok-cesnovar is this correct?

is there a downside to always having threading on?
ways to solve this problem would be by adding a `make/local` file as part of the cmdstan install process which specifies threading one way or another, and then adding more logic to the compile methods...  or

**Comment by bbbales2** [comment]
> you mean threading on by default always?

Yeah.

> is there a downside to always having threading on?

Not that I'm aware of. I think @wds15 said there might be like 2% overhead in the simplest models, but I don't think there's anything substantial we need to worry about.

**Comment by mitzimorris** [comment]
OK, then I think the solution is that install creates a `make/local` file which specifies threading on.  will try this out in CmdStanPy.

**Comment by wds15** [comment]
I am all for threading as a default being on!

**Comment by rok-cesnovar** [comment]
> there's linker errors if there's a mismatch between how they were compiled

Yes, main.o and friends need to be recompiled with `STAN_THREADS` on. But that is it. I will tackle this issue together with the generalization.

**Comment by mitzimorris** [comment]
whatever the default - on or off - unless the math lib makefiles use makefile variable `STAN_THREADS` - the CmdStan makefile needs to do the right thing by `model.o` and `main.o` - that needs to be solved for CmdStan.  for CmdStanX, the question is how to expose control over the `STAN_THREADS` makefile var.

**Comment by mitzimorris** [comment]
in CmdStan issues, there's this:  https://github.com/stan-dev/cmdstan/issues/757
and this:   https://github.com/stan-dev/cmdstan/issues/791

**Comment by rok-cesnovar** [comment]
This turned out to not be such a slam dunk for now, so I am going to close this and we can revisit it once we solve it in cmdstan.

The best idea I had so far is stanc3 somehow flagging the use of map_rect/reduce_sum which interfaces could then consume. The "somehow" is still up in the air.

**Comment by bbbales2** [comment]
`threads = TRUE` flag is okay if that's what we gotta do.
