### ISSUE TITLE
error "extract_variable_matrix" is not an exported object

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#155]
**Describe the bug**
sample method failed with error message:
`error "extract_variable_matrix" is not an exported object in namespace posterior`

**To Reproduce**
run sample method

**Expected behavior**
sample method should succeed given model and data.

**Operating system**
catalina

**CmdStanR version number**
0.090000

**Additional context**
Bob Carpenter was trying to fit some models for a case study.  he followed the instructions in the CmdStanR getting started vignette.  it appears that CmdStan did fit the model to the data - it took about 20 or 30 minutes - then crashed.  omitting the rest of the things that Bob said about CmdStanR.

**Comment by mitzimorris** [comment]
is it possible that Bob was using an old version of the posterior package?
if so, why wasn't this dependency picked up when installing cmdstanr?

**Comment by rok-cesnovar** [comment]
I am not sure if a version dependency check is performed for packages that are  not on CRAN. It might be possible but I have not found a solution.

I have pushed to master a fix that will write the following:
```
> library(cmdstanr)
This is cmdstanr version 0.0.0.9000
- Online documentation and vignettes at mc-stan.org/cmdstanr
- CmdStan path set to: /home/rok/.cmdstanr/cmdstan
- Use set_cmdstan_path() to change the path
Warning message:
In fun(libname, pkgname) :
  posterior is version 0.0.1, but should be >= 0.0.2. Please upgrade the posterior package using devtools::install_github("jgabry/posterior")
```

I would either recommend users to check their package version. Or to agree on upgrading the posterior package when they run install_github("stan-dev/cmdstanr").

I get something like:

> remotes::install_github("stan-dev/cmdstanr")
```
Downloading GitHub repo stan-dev/cmdstanr@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: backports (1.1.5 -> 1.1.6) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
```
If posterior is not the correct version it will be listed. Its just too easy to skip this.
