### ISSUE TITLE
Fix doc about default path

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#161]
Now that we use `.cmdstanr/cmdstan-[version]` instead of just `.cmdstanr/cmdstan` as the default path we need to update the doc in `help("cmdstan_path")` and in the vignette to match this.

**Comment by rok-cesnovar** [comment]
I fixed those on master just now, please take a look. I did not build the html files as I not exactly sure what is the right way.

`pkgdown::build_site()` seems to do too much.

**Comment by jgabry** [comment]
Thanks, looks good! I agree `build_site()` does too much. I just pushed a commit updating just the pages we want using: 

```r
withr::with_envvar(c("NOT_CRAN" = "true"), {
  pkgdown::build_reference(topics = "set_cmdstan_path")
  pkgdown::build_article(name = "cmdstanr") 
})
```

The `with_envvar` part just makes sure that the code in the vignette gets evaluated (we have a line at the top of the vignette that turns off evaluation on CRAN, which we don't need to do yet but will need when we submit it since we don't CRAN trying and failing to run CmdStan).
