### ISSUE TITLE
Interface for number of threads

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#163]
The current interface to setting the number of within chain threads is

```
set_num_threads(4)
```

Should we maybe move it to `$sample(chain_threads=4)`? Though the cores and threads together might be confusing?

**Comment by jgabry** [comment]
Yeah I like the idea of making it an argument to `$sample()`. I agree it could be confusing but we can document it clearly. I think it's even more confusing to do what we do now (treat the number of threads different from everything else).

**Comment by rok-cesnovar** [comment]
Ok, so we are then at argument names again :) 

`threads = x'?
`num_threads` is bad as num is redundant
`chain_threads = x`?

**Comment by jgabry** [comment]
Yeah I think either `threads` or `chain_threads`. @mitzimorris, what do you think? We should coordinate on this. 

Another question: if the user specifies this argument but didn't enable threading during compilation, should we throw an error? Ignore it with a warning?

**Comment by rok-cesnovar** [comment]
I say we throw an error.

**Comment by mitzimorris** [comment]
let's ask on the forums - we need inputs from users - certainly Sebastian, Charles, Ben B - curious who else might have an opinion.
