### ISSUE TITLE
Use aliases to make doc easier to navigate

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#186]
Since most things in CmdStanR are methods of R6 objects and not standalone functions, finding their doc is not the same as for typical R functions. We could use the `@aliases` tag in roxygen to make so that, e.g., `?draws` could be used instead of having to go `CmdStanMCMC` and click on the link to the draws method. Same for other methods. 

I can make a PR for this.

**Comment by bbbales2** [comment]
Yeah I like this. This might cause problems if multiple classes want to have the same aliases (sampling and vb both have draws functions), but it's better than nothing.

**Comment by jgabry** [comment]
Oops, closed this by accident. Meant to make a PR
