### ISSUE TITLE
Optional use of JSON for the middle layer IO

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#19]
As of Cmdstan 2.21 the input reading via JSON is going to be significantly faster than reading Rdump (see numbers below the chart https://github.com/stan-dev/cmdstan/pull/732#issuecomment-532822159). 

Is there any option of supporting JSON for the hidden layer between cmdstanr and cmdstan?  Not asking anyone to do it, I would try to help with this, just asking if this is an option at all. I understand that would probably mean a new dependecy library :/

I am really interested in using cmdstanr because I have all my performance measuring scripts for my Stan GPU research written in R with some custom wrappers to cmdstan. This would help really help cleanup and more easily maintain my code. Minimizing IO is kind of big deal for me as I am running models with large input sizes.

**Comment by jgabry** [comment]
Not yet, but I'd love to allow this! I'm really just getting started on this package and would love more people to help work on it, so if you'd like to help develop it that would be great!

**Comment by jgabry** [comment]
@rok-cesnovar In terms of adding a dependency, are you familiar with any of the R packages for reading and writing JSON? I don’t know too much on that topic so if you want to try implementing this feel free to go with whatever you think is the best option.

**Comment by rok-cesnovar** [comment]
I think jsonlite is considered to be the fastest one and also has the option of full_precision and an MIT license. There are some other performant libraries that get performance by sacrificing precision which is not desirable. I will do a microbenchmark for writeJSON or equivalent calls for the most popular packages once I start working on this (should be early next week). The R to JSON direction is the only one we care about here.

**Comment by jgabry** [comment]
#33 is now merged! So I think we can close
