### ISSUE TITLE
Refactor CmdstanProcs

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#197]
I started adding the generate_quantities method and this came up. Currently the CmdstanProcs is too sampling focused.

My current plan is to make a generic CmdstanProcs class with the common functionalities that are enough for VI/optimization/GQ and add a CmdstanMCMCProcs that inherits the generic one. But am open to other ideas.

This is currently blocking #7 We could fix it before this but it would just make this refactor more difficult.

**Comment by jgabry** [comment]
Yeah that sounds good to me. Maybe we can talk about this on the call today If you're able to join (if not no worries).

**Comment by rok-cesnovar** [comment]
Still not sure if I make. Will try. Sorry for being so bad with this meeting.

**Comment by jgabry** [comment]
If you can't make it don't worry about it!

**Comment by jgabry** [comment]
By the way, it's fine by me for you to do this even though we didn't talk during the meeting today.

**Comment by rok-cesnovar** [comment]
I am slowly refactoring this. One question before I go too deep.

I think stuff in procs should be referred to as procs not runs.

This would be the reasoning:
run = something that produces a result (for example a fit), regardless of how many chains were started etc.
procs = 1 to 1 mapping to an actual process started

So the `num_runs` here:https://github.com/stan-dev/cmdstanr/blob/master/R/run.R#L318 would become `num_procs` and so on whatever has to be changed accordingly.

**Comment by jgabry** [comment]
Yeah you're right, changing to `num_procs` makes sense.
