### ISSUE TITLE
Create read_stan_csv

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#199]
We currently have `read_sample_csv`, `read_optim_csv`, etc. Make a `read_X_csv` function that would be method-agnostic and would use the already implemented functions in the backend.

`cmdstanr::read_stan_csv` is a good name, though it shadows the rstan's name so that might be a problem. `cmdstanr::read_csv` is maybe too generic and probably shadows many other CSV reading packages. 

Any ideas?

**Comment by jgabry** [comment]
Good idea. How about `read_cmdstan_csv`?

**Comment by rok-cesnovar** [comment]
Also fix the cmdstanr internals vignette.
