### ISSUE TITLE
Easy access to inverse_metric after fitting

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#202]
Right now `read_sample_csv()` provides access to the estimated inverse metric but it's not accessible via the fitted model object. Should we add a method `fit$inverse_metric()`? If so, then: 

(a) Thoughts on name `fit$inverse_metric()`? 

(b) Sometimes it will be a vector (diagonal) and other times a matrix (if dense). Should we allow it to have different return types or should we always return a matrix that is usually but not always a diagonal matrix? Using the same return type is nice but for large matrices it would wasteful to always return the whole matrix unless we use one of R's sparse matrix types (but that requires adding another R package dependency)

**Comment by rok-cesnovar** [comment]
What if it was `fit$inverse_metric(as_matrix = FALSE)` and by default it returned different types, but could return a matrix if requested. Or is that too confusing?

**Comment by jgabry** [comment]
Good idea with the `as_matrix` argument. My inclination would be to have `as_matrix=TRUE` by default so that by default the return types are always the same and the the user can set to `FALSE` to say memory if desired. What do you think?

@bbbales2 @mitzimorris Any thoughts on this?

**Comment by jgabry** [comment]
In PR #204 I propose to go with`fit$inv_metric(matrix=TRUE)`
