### ISSUE TITLE
read_sample_csv doesn't respect order of variables argument

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#211]
**Describe the bug**

This is just a minor bug in that the CSV is read correctly, but the order specified in the `variables` argument isn't respected. That is, `variables = c("a", "b")` returns the draws in the same order as `variables = c("b", "a")`. 

This isn't a big deal but it's inconvenient because, for example, these two lines create the same plot but the second should really have the x and y axes flipped:

```r
bayesplot::mcmc_scatter(fit$draws("alpha", "beta[1]"))
bayesplot::mcmc_scatter(fit$draws("beta[1]", "alpha"))
```

I think the issue seems to be that the `matching_variables()` helper function that is called by `read_sample_csv()` always returns the same order: 

```r
> matching_variables(variable_filters = c("a", "b"),  variables = letters)
$matching
[1] "a" "b"

$not_found
NULL


> matching_variables(variable_filters = c("b", "a"),  variables = letters)
$matching
[1] "a" "b"

$not_found
NULL
```

**To Reproduce**

```r
fit <- cmdstanr_example("logistic")

# these return the draws in the same order
identical(
 fit$draws(c("alpha", "beta[1]")),
 fit$draws(c("beta[1]", "alpha")) 
)
```

**Expected behavior**

`fit$draws(c("beta[1]", "alpha")) ` should return the draws with `beta[1]` before `alpha`.

**CmdStanR version number**
`0.0.0.9006`

**Comment by jgabry** [comment]
I think I have a fix for this. Will make a PR shortly.

**Comment by rok-cesnovar** [comment]
Good catch!
