### ISSUE TITLE
Fitting 35000 parameters causes cmdstan to fail

### ISSUE THREAD

**Issue by karldw** [stan-dev/cmdstanr#213]
#### Summary:
I noticed that when I run a large imputation program in cmdstan, the program fails. There seem to be problems for both ADVI and MCMC.

#### Description:
When running [imputation within brms](https://paul-buerkner.github.io/brms/articles/brms_missings.html) each missing data point is a parameter, so it's easy to get quite high parameter counts. When I run one of these models with ADVI or MCMC I get errors, though at different points.

The output of both is below. ADVI seems to be failing with status -9 somewhere in the compiled stan program. MCMC seems to get all the way through sampling, then aborts with a core dump. 

I think this is a problem with cmdstan, rather than cmdstanr or brms, but let me know if I should file this issue somewhere else. 

#### Reproducible Steps:

```r
library(brms)
options(mc.cores=4) # edit
set.seed(1)
N <- 40000
frac_miss <- 0.9
df <- data.frame(
  y = ifelse(rbinom(N, prob=frac_miss, size=1), NA_real_, rnorm(N)),
  x = rnorm(N)
)
# Both of these fail:
fit1 <- brm(bf(y | mi() ~ x), data=df, algorithm="fullrank", backend="cmdstan")
fit2 <- brm(bf(y | mi() ~ x), data=df, algorithm="sampling", backend="cmdstan")

```
Edit: fixed typo in example.

#### Current Output:
<details>

<summary>
ADVI (algorithm fullrank) output
</summary>

```
Start sampling
method = variational
  variational
    algorithm = fullrank
      fullrank
    iter = 2000
    grad_samples = 1 (Default)
    elbo_samples = 100 (Default)
    eta = 1 (Default)
    adapt
      engaged = 1 (Default)
      iter = 50 (Default)
    tol_rel_obj = 0.01 (Default)
    eval_elbo = 100 (Default)
    output_samples = 1000 (Default)
id = 1
data
  file = /tmp/Rtmp7WnXCF/standata-44a17a27862e.json
init = 2 (Default)
random
  seed = 203757686
output
  file = /tmp/Rtmp7WnXCF/file44a11d525f03-202006131129-1-c273b6.csv
  diagnostic_file =  (Default)
  refresh = 100 (Default)

------------------------------------------------------------
EXPERIMENTAL ALGORITHM:
  This procedure has not been thoroughly tested and may be unstable
  or buggy. The interface is subject to change.
------------------------------------------------------------

Gradient evaluation took 0.005164 seconds
1000 transitions using 10 leapfrog steps per transition would take 51.64 seconds.
Adjust your expectations accordingly!

Begin eta adaptation.
Error in processx::run(command = self$command(), args = self$command_args()[[1]],  : 
  System command 'file44a11d525f03' failed, exit status: -9, stdout & stderr were printed

```

</details>

<details>

<summary>
MCMC output
</summary>

```
Start sampling
Running MCMC with 4 chain(s) on 4 core(s)...

Running ./file4605202e5693 'id=1' random 'seed=557537745' data \
  'file=/tmp/RtmphAM1Xz/standata-46054d575fd.json' output \
  'file=/tmp/RtmphAM1Xz/file4605202e5693-202006131144-1-64e0f9.csv' \
  'method=sample' 'num_samples=1000' 'num_warmup=1000' 'save_warmup=0' \
  'thin=1' 'algorithm=hmc' 'engine=nuts' adapt 'engaged=1'
Running ./file4605202e5693 'id=2' random 'seed=238490394' data \
  'file=/tmp/RtmphAM1Xz/standata-46054d575fd.json' output \
  'file=/tmp/RtmphAM1Xz/file4605202e5693-202006131144-2-64e0f9.csv' \
  'method=sample' 'num_samples=1000' 'num_warmup=1000' 'save_warmup=0' \
  'thin=1' 'algorithm=hmc' 'engine=nuts' adapt 'engaged=1'
Running ./file4605202e5693 'id=3' random 'seed=1485495582' data \
  'file=/tmp/RtmphAM1Xz/standata-46054d575fd.json' output \
  'file=/tmp/RtmphAM1Xz/file4605202e5693-202006131144-3-64e0f9.csv' \
  'method=sample' 'num_samples=1000' 'num_warmup=1000' 'save_warmup=0' \
  'thin=1' 'algorithm=hmc' 'engine=nuts' adapt 'engaged=1'
Running ./file4605202e5693 'id=4' random 'seed=1895355607' data \
  'file=/tmp/RtmphAM1Xz/standata-46054d575fd.json' output \
  'file=/tmp/RtmphAM1Xz/file4605202e5693-202006131144-4-64e0f9.csv' \
  'method=sample' 'num_samples=1000' 'num_warmup=1000' 'save_warmup=0' \
  'thin=1' 'algorithm=hmc' 'engine=nuts' adapt 'engaged=1'

... (sampling progress)

Chain 4 finished in 1878.6 seconds.

All 4 chains finished successfully.
Mean chain execution time: 1828.2 seconds.
Total execution time: 1878.7 seconds.
terminate called recursively
terminate called after throwing an instance of 'std::bad_alloc'
terminate called recursively
Aborted (core dumped)

```

</details>

#### Expected Output:
I expected the models to run.

#### Additional information

- MCMC runs without error (but with divergent transitions) if I set `iter=10`.
- The ADVI example also fails with `backend="rstan"`; I haven't tested the MCMC example with `backend="rstan"`
- The stan csvs are created (316 MB per chain) and I'm able to read all of them back in with `rstan::read_stan_csv`
- 35000 isn't a magic number. I haven't experimented with different parameter counts.

#### Current Version:
cmdstan v2.23.0, brms v2.13.3 (54cba34)

**Comment by rok-cesnovar** [comment]
This is a cmdstanr issue (actually the package we use to read csv files needs a few more hints with so many parameters). Will address shortly.

**Comment by jgabry** [comment]
@karldw  Now that #214 is merged, if you install the latest cmdstanr from github does it resolve the issue? If not we can reopen this.

**Comment by karldw** [comment]
This works well, thanks everyone!

**Comment by jgabry** [comment]
Ok great, thanks for checking!

**Comment by karldw** [comment]
Ah, it looks like my confusion in the `algorithm="fullrank"` case is already covered by this issue from six years ago: https://github.com/stan-dev/cmdstan/issues/514
