### ISSUE TITLE
Drop rstan from Suggests? 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#215]
Currently we have a soft dependency on rstan because for CmdStan < 2.22, we use `rstan::stan_rdump()` to write the data file (I believe this is because of a problem with JSON pre 2.22): 

https://github.com/stan-dev/cmdstanr/blob/373a891ef02eff9e8809bde1cb2f10a7c936e191/R/model.R#L868-L871

I think it would be preferable to get rid of all dependence on rstan, so I propose that instead of calling rstan inside CmdStanR we instead throw an error and tell the user to call `rstan::stan_rdump()` themselves. This would affect a very small number of users (only those who insist on using an old CmdStan) and allow us to remove rstan entirely while still supporting R dump files. 

Thoughts? I have a branch that does this so I can make PR if no objection.

**Comment by rok-cesnovar** [comment]
I support this. It's really such a non-standard case its not worth even a soft dependency. We can do what you propose or check if there is a dimension with zero elements and stop only in that case. I am fine either way.

The problematic case is <2.22 and a dimension with zero elements.
