### ISSUE TITLE
Suppress printed CmdStan commands? 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#219]
Currently the model fitting methods print the CmdStan command, e.g.: 

```
Running ./logistic 'id=4' random 'seed=412468223' data \
  'file=/Users/jgabry/Documents/Stan/cmdstanr/inst/logistic.data.json' output \
  'file=/var/folders/h6/14xy_35x4wd2tz542dn0qhtc0000gn/T/Rtmpnqymdw/logistic-202006241344-4-c46894.csv' \
  'method=sample' 'save_warmup=0' 'algorithm=hmc' 'engine=nuts' adapt 'engaged=1'
```

but this isn't really providing the user with information they don't already know (they know which arguments they specified and where their Stan program is, and they probably don't care about the temporary file path for the output.) 

I suggest that we suppress this. Any objections? If not I'll open a PR.

**Comment by rok-cesnovar** [comment]
I am in favor of this. These provide no additional information so they are just be ignored.
