### ISSUE TITLE
Message to user to expect slow compilation the first time?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#230]
@rok-cesnovar The first time the user compiles a model after installing CmdStan they should expect it to take a lot longer than usual (presumably to build the precompiled header, etc.), right? If so, maybe we should print a message the first time they try to compile something to warn them to expect a long compilation time. I can imagine that once we release CmdStanR we could get lots of questions on the forums about that if we don't warn them to expect it. What do you think?

**Comment by rok-cesnovar** [comment]
Great idea!
