### ISSUE TITLE
Allow passing inits as a list of R objects or function like RStan

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#231]
For inits, right now CmdStanR requires specifying initialization files, but we could allow passing in a list of initial values like RStan does. This came up in a brms issue: https://github.com/paul-buerkner/brms/issues/940

**Comment by rok-cesnovar** [comment]
Just to clarify 2 things:
- inits should be handled the same as lists for data?
- in case of multiple chains its a vector of lists?

**Comment by jgabry** [comment]
> * inits should be handled the same as lists for data?

I think so, yeah. We can just write it to JSON.

> * in case of multiple chains its a vector of lists?

Yeah, a list of lists. For example, for 2 chains and parameters block

```stan
parameters {
  real alpha;
  vector[2] beta;
}
```

it could be

```r
initial_values <- list(
  list(
    alpha = 0.3,
    beta = c(1.5, 3.7)
  ),
  list(
    alpha = 0.7,
    beta = c(-1, 8.2)
  )
)

mod$sample(..., init = initial_values)
```

I think like rstan we should also allow a _function_ that generates inits, e.g.: 

```r
init_fun <- function(chain_id) {
  # optionally use chain_id inside the function, but not required
  list(
    alpha = rnorm(1, mean = 0, sd = 2),
    beta = rnorm(2, mean = c(-1, 1), sd = 1)
  )
}

mod$sample(..., init = init_fun)
```

**Comment by jgabry** [comment]
I might have a little bit of time this afternoon to try to implement this.
