### ISSUE TITLE
Output directory for $compile

### ISSUE THREAD

**Issue by jstagge** [stan-dev/cmdstanr#237]
I would like to be able to compile a stan model to a specific directory. 

This would help with model storage and when compiling a model within an R package (my current use case).

This function may be available within the cpp_options using the -o flag, but I cannot figure it out. And I suspect when you go to sample from the model, it might not retain the connection.

**Comment by rok-cesnovar** [comment]
Hi,

thanks for the feature request!

So if I understand correctly, you wish to place the built model (the executable) to some specific location?
Currently, we place the executable to the same location as the model. We could add something like

```R
mod <- cmdstan_model("bernoulli.stan", output_dir = "~/someOtherLocation/")
```

So the executable would be placed in `~/someOtherLocation/bernoulli` or `~/someOtherLocation/bernoulli.exe` on Windows.

I think this sounds useful. @jgabry any thoughts?

**Comment by jstagge** [comment]
That is exactly what I was hoping for - similar to how it handles output of model runs.

**Comment by jgabry** [comment]
Sure, sounds good to me!

**Comment by jgabry** [comment]
And adding a reminder here for whichever one of us ends up adding this: remember to update these lines in the vignette

https://github.com/stan-dev/cmdstanr/blob/31016816cf346e602a8458cb15cc31f43ef16931/vignettes/cmdstanr-internals.Rmd#L104-L105

**Comment by jgabry** [comment]
@jstagge Thanks again for the feature request. This should be working on the master branch now that #238 is merged. If you reinstall with `devtools::install_github("stan-dev/cmdstanr")` does the new `dir` argument work properly for you?
