### ISSUE TITLE
specify target-directory for executable in cmdstan_model

### ISSUE THREAD

**Issue by gbiele** [stan-dev/cmdstanr#242]
**Is your feature request related to a problem? Please describe.**
When working on (Windows) machines with very limited user-rights it is not generally possible to use cmdstanr-generated *.exe files if they are not located at specific location.

**Describe the solution you'd like**
Add an option `model.dir` (I don't care much about the name) to `cmdstan_model` which takes as argument the path to a directory in which the executable is saved.

**Describe alternatives you've considered**
Currently I am just copying the Stan-file to the desired directory (where I can execute executables) and then point `cmdstan_model` to this copy.

**Additional context**
I am not sure if it is worth implementing this. That depends probably on how many people work on systems where they cannot use executables stored anywhere. On the other hand, there are alternative use cases. If for instance if the Stan file is stored somewhere `cmdstan_model` cannot save the executable (e.g. some github-repo on the internet) the current `cmdstan_model` cannot generate the executable. (though looks as if rstan also can't do the latter.)

**Comment by rok-cesnovar** [comment]
Hi @gbiele, thanks for the request. You are in luck . This was added to cmdstanr just recently https://github.com/stan-dev/cmdstanr/pull/238

Could you install the Github version and try out the dir argument to the cmdstan_model function. Also see the updated vignette: https://github.com/stan-dev/cmdstanr/pull/238

**Comment by rok-cesnovar** [comment]
Bumping this.

**Comment by rok-cesnovar** [comment]
I am going to close this issue.

@gbiele if you would want some additional features to dir argument of the cmdstan_model function, feel free to reopen.
