### ISSUE TITLE
Update doc for install_cmdstan()?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#248]
@rok-cesnovar It seems like our recommendation to check appendix B of the CmdStan guide

https://github.com/stan-dev/cmdstanr/blob/d5d5246563390fcc994af23832455c4b9f0766f8/R/install.R#L7-L8

is out of date. (Also there doesn't seem to be an appendix B anymore in the online CmdStan doc.) We should point to the latest instructions for getting the required tool chain.

**Comment by rok-cesnovar** [comment]
Good call. Lets just point to https://mc-stan.org/docs/2_24/cmdstan-guide/cmdstan-installation.html

**Comment by jgabry** [comment]
Yeah that makes sense.

**Comment by jgabry** [comment]
Actually just from reading Chapter 1 at that link it will seem to the reader that they need to do a whole bunch of extra stuff that `cmdstanr::install_cmdstan()` will do automatically for them. So we really just need them to see a subset of the info from Chapter 1 or we could confuse people.

**Comment by jgabry** [comment]
Also is there stuff in @maxmantei's blog post (https://www.maxmantei.com/blog/2020-05-16-installing-cmdstanr-on-windows/cmdstanr-windows/) that is relevant for Windows users that isn't mentioned in the latest CmdStan guide? If so should we point there from the doc too or copy that info over? (Sorry I'm so ignorant about Windows!)

**Comment by rok-cesnovar** [comment]
Yes, if using Rtools 4.0 you need to install mingw32-make:
```
You actually have to install mingw32-make manually via RTools Bash. To open RTools Bash, which comes with RTools 4.0, just hit Windows Key, type rtools bash and hit Enter. A new console window will pop up. Now, just type

pacman -Sy mingw-w64-x86_64-make
```
This is missing from the docs. 

We really need a dedicated install page for all interfaces! I started work on that a while ago, really shoud finish it.

For mac and linux its just checking you have a toolchain.

**Comment by mitzimorris** [comment]
@rok-cesnovar - do I need to update the CmdStan guide or it it correct?

**Comment by rok-cesnovar** [comment]
The Windows instruction are missing the info above:

On Windows we require `mingw32-make` for building models. `mingw32-make` does not come with RTools 4.0 but can be installed easily via RTools Bash. To open RTools Bash, which comes with RTools 4.0, just hit Windows Key, type rtools bash and hit Enter. A new console window will pop up. Now, just type

`pacman -Sy mingw-w64-x86_64-make`

Then restart the terminal and check that `mingw32-make --version` works.

**Comment by tjmahr** [comment]
> 
> 
> The Windows instruction are missing the info above:
> 
> On Windows we require `mingw32-make` for building models. `mingw32-make` does not come with RTools 4.0 but can be installed easily via RTools Bash. To open RTools Bash, which comes with RTools 4.0, just hit Windows Key, type rtools bash and hit Enter. A new console window will pop up. Now, just type
> 
> `pacman -Sy mingw-w64-x86_64-make`
> 
> Then restart the terminal and check that `mingw32-make --version` works.

Can `make_cmd()` check for this program and offer this advice in a message? (If not call pacman and do the installation?) I followed the CmdStan installation instructions exactly and ran into this problem.

Should this issue be open until stan-dev/cmdstan#909 is closed?

**Comment by rok-cesnovar** [comment]
> Can make_cmd() check for this program and offer this advice in a message?

Yes! It was my intent to add this together with #259 

The plan is to:
- try if mingw32-make —version works
- if not look at specific places where it might be 
- if not found, suggest to the user the pacman install command

I dont think the pacman install can be automated

I need to revisit the cmdstan instruction once more as it seems yes. Thanks for the report.
