### ISSUE TITLE
Fall back to read.csv in case of a vroom error

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#249]
Suggested by @maedoc

The idea in pseudocde is: 
```
try {
//read with vroom
} catch {
warning("There was an issue with reading the CSV file with vroom. Using the utils::read_csv")
// read entire file with read_csv
}
```

@jgabry something like this would do? Any suggestions on the message?

**Comment by jgabry** [comment]
Yeah I think something like that would work. For the message, maybe something like this? 

```
Fast CSV reading with vroom::vroom() failed. Using utils::read_csv() instead. 
```

Also, in the message should we ask people to report it to us? That could help us figure out which exact combination of R and package versions causes this. I'm also ok with not asking them to report this, but if we do want to do that the message could be: 

```
Fast CSV reading with vroom::vroom() failed. Using utils::read_csv() instead. 
To help avoid this in the future, please report this issue at github.com/stan-dev/cmdstanr/issues 
and include the output from sessionInfo(). 
```

**Comment by rok-cesnovar** [comment]
I think I am in favor of reporting.

**Comment by saudiwin** [comment]
I doubt this would help a lot, but I've found read_csv in readr package to be very stable and faster than read.csv.

**Comment by rok-cesnovar** [comment]
The readr's read_csv function is great, but we had issues with the specifics of cmdstan's CSV. It mostly works fine, but broke in some specific cases. We will use read.csv as a last resort and hoping users never need it once we fix this vroom issue.
