### ISSUE TITLE
Write functions to read CmdStan csv output into R

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#25]
The csv output is different depending on whether the CmdStan `method` is sample, optimize or variational. Right now `rstan::read_stan_csv()` is used for `method=sample`, but it doesn't work for the csv output for optimization or variational inference. We also don't want to depend on RStan (#2), so we should eventually not rely on it for `method=sample` either.

**Comment by jgabry** [comment]
I have basic implementations called `read_optim_csv` and `read_vb_csv` in `R/utils.R` that are working but still pretty primitive.

**Comment by rok-cesnovar** [comment]
How does this differ from #2 ? I might just be missing something.

**Comment by jgabry** [comment]
#2 was specific to not relying on rstan functions. read_stan_csv doesn't work for optimization and vb so I opened this separate issue for more generally tracking the progress on reading output from cmdstan.

**Comment by jgabry** [comment]
We can close this now though since I think we just need to read the csv for sampling now and that is covered by #2
