### ISSUE TITLE
Beta release schedule

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#253]
@rok-cesnovar The only open issue in the beta release milestone is now #200 (Vignettes)! I think we probably have enough in the vignettes for the beta release (is there anything we obvious need that we don't have?), although I do think we should add those additional vignettes for the 1.0 release. What do you think? Should we move forward with the beta release? Especially given all the problems with RStan recently, unless we're waiting on something crucial, maybe we should go ahead?

@mitzimorris I think CmdStanPy technically is already in beta, right? If not in beta, how close are you to ready? If already in beta, then when we do CmdStanR's beta release I guess we can announce both?

**Comment by rok-cesnovar** [comment]
I agree that we are ready for beta. We can add vignettes as we find out what the users struggle with the most.

**Comment by jgabry** [comment]
What version number do you want to use for beta? Does `0.1.0` make sense?

**Comment by rok-cesnovar** [comment]
I think it does make sense yes.

**Comment by jgabry** [comment]
Ok great. I'll make a branch for the beta release that 

* changes the version number
* updates any mentions of "pre-beta" to beta
* updates the website

If there's anything else you think of that needs to be done let me know (I have some time today)

**Comment by mitzimorris** [comment]
CmdStanPy started in Beta, so calling this a Beta release is fine.

**Comment by jgabry** [comment]
Ok great, we'll go ahead and call this a "beta" release for CmdStanR. And yeah for 1.0 I agree with all those bullet points.
