### ISSUE TITLE
Enable faster compilation on Windows with RTools 4.x with cmdstan 2.24+

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#257]
Cmdstan 2.24 brought 40% faster compilation for Mac and Linux. Windows users with RTools 4.0 installed toolchain can also get faster compile times if they set a makefile flag. 

This makefile flag set on windows with RTools 3.5 causes the compilation to fail, which is why the flag is not on for Windows by default like it is for Mac & Linux.

Example on Windows with Rtools 4.0: 

```r
test_file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(test_file, compile = FALSE)

non_precompiled <- c()
for (i in 1:5){
  start <- Sys.time()
  mod$compile(force_recompile = TRUE)
  stop <- Sys.time()
  non_precompiled <- c(non_precompiled, (stop - start))
}

> non_precompiled
[1] 24.64085 24.86109 24.70086 24.44173 25.25062
```
But if I run: 
```r
cmdstan_make_local(cpp_options = list(PRECOMPILED_HEADERS=TRUE))
rebuild_cmdstan()
```
or just install a fresh cmdstan with the flag already set
`install_cmdstan(cores= 4, cpp_options = list(PRECOMPILED_HEADERS=TRUE), overwrite = TRUE)`

```r
precompiled <- c()
for (i in 1:5){
  start <- Sys.time()
  mod$compile(force_recompile = TRUE)
  stop <- Sys.time()
  precompiled <- c(precompiled, (stop - start))
}

> precompiled
[1] 14.90948 14.93675 14.96293 15.09841 14.96765
```
So a 40% decrease of compile time.

There are a few options we can do: 
- automatically set flag if R version is 4.x (can we assume people using RTools 4.0 with R 4.0? I guess we could. )
- automatically set flag if g++ version is 8.1.0 (check for version on install)
- mention that this is recommended to the users in install docs

Any thoughts?

**Comment by jgabry** [comment]
Wow 40% is a lot! I think we should do this automatically for the user instead of just recommending it in the docs (although it's probably worth also mentioning it in the docs). 

> * automatically set flag if R version is 4.x (can we assume people using RTools 4.0 with R 4.0? I guess we could. )

Yeah I think RTools 40 is required if using R >= 4.0, so just checking that `R.version$major` is at least "4" is probably sufficient. In that case, do we _also_ need to check the g++ version?

**Comment by rok-cesnovar** [comment]
> Wow 40% is a lot!

Indeed. On Linux with g++ it's actually close to 50%. So we should recommend users to switch to 2.24.

> do we _also_ need to check the g++ version

No. Its maybe a problem if the users have both 4.0 and 3.5 installed for some reason and a mess in PATH env. variables. But in that case, its going to be a problem anyway.
