### ISSUE TITLE
Replace vroom with fread

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#262]
**Describe the issue**

~We should move `vroom` from `Imports` to `Suggests` in the `DESCRIPTION` file. This was suggested by [Michael Peck on Discourse](https://discourse.mc-stan.org/t/lightweight-interfaces-keeping-it-light/16932/11?u=jonah). It has a lot of dependencies, so it's best to use it if present but not force people to install it.~

edit by Rok: 

We can replace vroom with data.table's fread function which makes making vroom optional redundant.

**CmdStanR version number**

0.1.0

**Comment by rok-cesnovar** [comment]
Just a heads up that I started working on plugging in `fread` and it seems like it should be an easy replacement. I am not sure if some recent updates of data.table made it play nicer with Stan CSV or I did something wrong in my previous tests.

So I dont think its worth it to make vroom optional beforehand. I am going to edit the title and top-level post to reflect that.

**Comment by jgabry** [comment]
Thanks @rok-cesnovar. Should we also close https://github.com/stan-dev/cmdstanr/pull/263?

**Comment by rok-cesnovar** [comment]
Yeah, went ahead and closed it.

**Comment by jgabry** [comment]
Thanks!
