### ISSUE TITLE
Let users know if a new CmdStan is available 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#265]
@mitzimorris and I were talking about this. At load time we could compare the latest installed cmdstan to the latest available cmdstan and let the user know if a newer release is available. (If we do this we should make sure to skip this check or wrap it in `try()` if there's no internet connection.)

**Comment by rok-cesnovar** [comment]
Yeah, no internet connection is one possible problem here, the other is Github API limit rate. I do agree that this feature makes sense yes.
