### ISSUE TITLE
Expose `chain_id` argument?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#266]
CmdStanPy exposes CmdStan's `chain_id` argument but we currently aren't exposing it in CmdStanR (we just always use 1:num_chains). 

@rok-cesnovar Do you think we need to expose `chain_id` for if people want to run the same call to `$sample()` on different machines and then combine the results? (If so, we'd also want a way to combine multiple CmdStanMCMC objects into a single one).

If we do implement this we should make sure to consider the issue in  https://github.com/stan-dev/cmdstanpy/pull/266.

**Comment by rok-cesnovar** [comment]
If I understand this correctly, the user would be able to supply 1,2,3,4 to first sample call and 5,6,7,8 for the second sample call?

That does seem useful for this use-case you mention.

**Comment by jgabry** [comment]
> If I understand this correctly, the user would be able to supply 1,2,3,4 to first sample call and 5,6,7,8 for the second sample call?

Yeah exactly.
