### ISSUE TITLE
Prints in the transform data are not printed

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#269]
As reported in https://github.com/stan-dev/stanc3/issues/652, 
print() in transform data does not get printed.

The reason for this is that in order to not print the initial Cmdstan metadata dump for all chains, we start printing stdout to the user only after either an error occurs, an init warning is read or the start of warmup/sampling is printed. So not ideal.

For the time being, we might get away with printing everything after the line
```
refresh = x
```
which I think is guaranteed to always be the last metadata printed (do have to check though). But that means that we will always print the gradient times for all chains. Hopefully, we can parse that away.

The ideal solution for this would be the "wrapper-friendly" mode for Cmdstan. But that won't be available at least until next release if we get others on board with that idea.

**Comment by jgabry** [comment]
> The ideal solution for this would be the "wrapper-friendly" mode for Cmdstan. But that won't be available at least until next release if we get others on board with that idea.

I'd really like this. Is this being discussed somewhere? If so let me know if I should chime in with my support.

**Comment by rok-cesnovar** [comment]
This has not been discussed much. I plan on making a proper proposal on how to do this, just need to send the latest version of my thesis to the committee. Should have more time to clear up to backlog on my TODO then.

The ideas so far are:
- more friendly stdout which makes it easier to skip the initial metadata dump (basically easier to show progress, warnings, etc.)
- write two or three separate CSV files: metadata with the step size and inv_metric as actual CSV data (not comments), samples CSV, warmup CSV (optional)
- a separate file for only reporting divergence/max treedepth hits that can be reported in real time (possibly enable a feature to stop sampling when divergences occur/max treedepth is hit)

**Comment by jgabry** [comment]
Sounds great! Would be nice to also write initial values to one of the files or a separate file.

**Comment by jgabry** [comment]
Related problem: `sig_figs` and the `generate_quantities` method: 

```
> fit_gq <- mod_gq$generate_quantities(fit_mcmc, data = data, seed = 123)
Running standalone generated quantities after 4 MCMC chains, 1 chain at a time ...

Chain 1   sig_figs = -1 (Default) 
Chain 1 finished in 0.0 seconds.
Chain 2   sig_figs = -1 (Default) 
Chain 2 finished in 0.0 seconds.
Chain 3   sig_figs = -1 (Default) 
Chain 3 finished in 0.0 seconds.
Chain 4   sig_figs = -1 (Default) 
Chain 4 finished in 0.0 seconds.

All 4 chains finished successfully.
Mean chain execution time: 0.0 seconds.
Total execution time: 0.6 seconds.
```
