### ISSUE TITLE
Decide what print should do for fitted model objects

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#27]
What should the `$print()` methods show for the different fitted model objects? Is it different than `$summary()` These include CmdStanMCMC, CmdStanMLE, and CmdStanVB objects, and eventually also CmdStanGQ objects once implemented.

**Comment by bbbales2** [comment]
I liked how it printed out the different methods I might call on the object. A cleaner version of that might be nice (so I can easily tell what my options are). I guess that's significantly different behavior than the interfaces now though.

On a related note, how do I get the docs for fit$function()? Normally I'd do ?function but it's not clear how to get the docs in Rstudio.

**Comment by rok-cesnovar** [comment]
> On a related note, how do I get the docs for fit$function()? Normally I'd do ?function but it's not clear how to get the docs in Rstudio.

For the model you get those by running ?CmdStanModel, ?CmdStanMCMC is the object returned by sample. CmdStanMLE is for optimize(), etc.

**Comment by jgabry** [comment]
> I liked how it printed out the different methods I might call on the object. A cleaner version of that might be nice (so I can easily tell what my options are). I guess that's significantly different behavior than the interfaces now though.

@bbbales2 I like this too despite it being atypical of the interfaces. Right now it’s using the default print method for R6 objects but I could modify that a bit to group the methods together by functionality and provide some more info.
