### ISSUE TITLE
Unable to Call External Functions/Stan Files with cmdstan_model

### ISSUE THREAD

**Issue by medewitt** [stan-dev/cmdstanr#271]
**Describe the bug**
I believe this relates to this issue that was resolved in StanJulia <https://github.com/StanJulia/CmdStan.jl/issues/55#issue-475560856>

This issue is when I try to include separate Stan functions in the function block using the usual syntax, `cmdstan_model` cannot find said functions

**To Reproduce**

File 1 calls "my_functions.stan"
```stan
functions {
#include my_functions.stan
}

data {
  int<lower=1> N;
  int<lower=0,upper=1> y[N];
}
parameters {
  real<lower=0,upper=1> theta;
}
model {
  my_function();
  theta ~ beta(1,1);
  y ~ bernoulli(theta);
}

```
my_functions.stan
```stan
my_function(){
    print("I'm working");
}

```

In R when I try to compile this program:

```r
library(cmdstanr)

mod <- cmdstan_model("bernoulli.stan")
```
I've tried various levels of specification of where the program is located with no difference. Each time I get the following error:

```
Could not find include file my_functions.stan in specified include paths.
```

**Expected behavior**
Stan program should compile with the functions that are called within the function block.

**Operating system**
Replicated on Windows 10 and OSX

**CmdStanR version number**
CmdStanR version number ‘0.1.0’
R 3.6.1 (on Windows), R 3.6.3 on Mac,

**Additional context**
I imagine the issue is that the program is compiled to a temp directory so the relative path to the other functions gets lost. I tried to get around that by putting the fully specified path in the functions block, but I still got an error (e.g. C:/..../my_functions.stan.

**Comment by jgabry** [comment]
I might be wrong but I think you're just missing the `include_paths` arguments which tells it where to look for included files. That's an argument to the `$compile()` method but can be passed to `cmdstan_model()` via `...`. http://mc-stan.org/cmdstanr/reference/model-method-compile.html

Can you try that and let us know if it works? If it doesn't then there may indeed be a bug.

**Comment by medewitt** [comment]
@jgabry while running through multiple scenarios, I realised I need a void type declaration on my dummy function. That with the include_paths, if worked. Thanks! Closing!

**Comment by jgabry** [comment]
Ok great glad that works!
