### ISSUE TITLE
Issue with installing cmdstan

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstanr#278]
**Describe the bug**

I did redefine the variable MAKE=„make -j6“ and this lead to a failure during building cmdstan...maybe this issue needs to be moved to cmdstan.

So the build did abort in this case. Redefining make in this way is a common thing to do for parallel builds I thought.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A description of what you expected to happen.

**Operating system**
Your operating system (e.g. mac os x 10.15, windows 10, etc.)

macOS x catalina

**CmdStanR version number**
0.1.1

**Additional context**

**Comment by rok-cesnovar** [comment]
Thanks for the report. 

You have this defined in the cmdstan make/local or a global make setting? 
Just to clarify, install_cmdstan() failed or did building a model fail?

I typically just define -jN every time, but I can see why someone would do that. 

I am almost certain this is a cmdstanr thing as the `processx::run` expects the first argument to be just the command without spaces.

**Comment by jgabry** [comment]
Is it a problem that we have a `cores` argument that Is _always_ passed to `build_cmdstan()`? 

https://github.com/stan-dev/cmdstanr/blob/497a0c8f08ed234f5df7819dd0a279017982f5ba/R/install.R#L292

**Comment by wds15** [comment]
I did define in my R sessions

`Sys.setenv(MAKE="make -j6")`

just before calling the `install_cmdstan()` and then it failed.

**Comment by jgabry** [comment]
Oh ok. I just tried that and it also errors for me. Until this is fixed if you want to use 6 cores during the build stage of installation you can just use `install_cmdstan(cores=6)`. 

As for the error, it does seem to start building but then it fails for me with: 

```
/bin/sh: -c: line 0: conditional binary operator expected
/bin/sh: -c: line 0: syntax error near `-j6'
/bin/sh: -c: line 0: `if [[ Darwin == Windows_NT ]]; then 	if ! [[ make -j6 =~ mingw32 ]]; then 		echo "ERROR: Please use mingw32-make on Windows to build the Intel TBB library."; 		echo "This is packaged with RTools, for example."; 		exit 1; 	fi fi'
make: *** [stan/lib/stan_math/lib/tbb/tbb-make-check] Error 2
make: *** Waiting for unfinished jobs....
```

@rok-cesnovar Is the problem that the `-j6` is getting copied into this if statement?

```
if ! [[ make -j6 =~ mingw32 ]];
```

**Comment by rok-cesnovar** [comment]
Yes, that is correct. Same thing on Linux. 

So this is an issue in Math actually. I updated the issue in https://github.com/stan-dev/math/issues/2012 that is tackling a similar problem (when there is a path in space to mingw32-make). I have a PR open, will try to find a fix for this issue as well.

I think just using cores is more than enough for the vast majority of users, but still won't hurt to fix.
