### ISSUE TITLE
Implement finalize() methods for the R6 classes?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#28]
Do we need this? It can be used to delete the potentially large temp files created by cmdstanr when a user deletes an object with rm() and when R exits. I guess this does come with a small risk that users could lose files by accident, so implementing this should come with adding an argument to the fitting methods (e.g. sample) so the user can specify that files should be saved at that time, without having to wait to call the `save_output_files()` method after fitting the model.

**Comment by jgabry** [comment]
@rok-cesnovar What do you think about this? If a user removes a fitted model object, e.g.,  

```r
fit <- mod$sample(...)
rm(fit)
```

should we remove the temporary CSV files? Obviously we wouldn't remove them if `output_dir` was specified, but in the case that they are temporary files do you think removing the object should result in immediate deletion of the temp files?

**Comment by rok-cesnovar** [comment]
I think they should get removed yeah. Maybe add a short example on what output_dir does in one of the vignettes.

**Comment by jgabry** [comment]
Ok so I implemented a finalizer in the branch `R6-finalizers` and it works, but not exactly how I was initially expecting. It seems that the finalizer is only called when R does garbage collection, which doesn't necessarily happen immediately after `rm(fit)` is run. 

```r
fit <- cmdstanr_example()
files <- fit$output_files()
rm(fit) # doesn't necessarily finalize
all(file.exists(files)) # TRUE
gc()    # force garbage collection forces finalize
any(file.exists(files)) # FALSE
```

The doc for R6 mentions this (https://r6.r-lib.org/articles/Introduction.html#finalizers-1) so I should have expected it. 

So it will definitely finalize when the R session ends (but the temp files would get removed then anyway without a finalizer) and it will finalize when garbage collection happens during an R session (even if not forced it happens from time to time), but not necessarily immediately after the object is removed. I guess that's better than not having it, so I'll make a PR.
