### ISSUE TITLE
Request: extract draws from models with different variables 

### ISSUE THREAD

**Issue by karldw** [stan-dev/cmdstanr#280]
**Is your feature request related to a problem? Please describe.**

I'm writing a model where some parameters are fitted values, but the length of the fitted value vector is random. I'm not interested in the fitted value. When I try to read the *other* model parameters back, I get an error.

**Describe the solution you'd like**

Either of the following:
- A way to extract draws from a fitted model, even when the variables differ across chains. 
- Some way to tell cmdstan not to write out specific variables (that is, the first request of #173)

**Describe alternatives you've considered**

The random number of parameters comes up because I'm bootstrapping within Stan. I could avoid this by drawing the bootstrap sample outside Stan, but it seemed like more hassle to get the random number generation correct, and chains are a nice unit of parallelism.

**Additional context**

Here's a demonstration of an odd measurement error model, borrowing bootstrap code from the [users guide](https://mc-stan.org/docs/2_24/stan-users-guide/coding-the-bootstrap-in-stan.html):

Stan model saved as `shuffle_example.stan`

```stan
functions {
  // Which elements of x are != 0?
  // Side note: is there a better way to express this? I just want R's which().
  int[] which (int[] x) {
    int N = size(x);
    int is_nonzero[N];
    for (i in 1:N) {
      is_nonzero[i] = x[i] != 0;
    }
    int result[sum(is_nonzero)];
    int j = 0;
    for (i in 1:N) {
      if (is_nonzero[i]) {
        j += 1;
        result[j] = i;
      }
    }
    return result;
  }
}
data {
  int<lower=0> N; 
  vector[N] x;
  vector[N] x_se;
}
transformed data {
  int<lower=1, upper=N> boot_idx[N];
  simplex[N] uniform = rep_vector(1.0 / N, N);
  for (i in 1:N) {
    boot_idx[i] = categorical_rng(uniform);
  }
  // construct shuffled versions of x and x_se
  vector[N] x_reindex = x[boot_idx];
  vector[N] x_se_reindex = x_se[boot_idx];

  // make an indicator for whether the shuffled x is 0
  int obs_dummy[N];
  for (i in 1:N) {
    obs_dummy[i] = x_reindex[i] != 0;
  }
  int N_obs = sum(obs_dummy); // number of observed x, after reindex

  // Extract the non-zero x_reindex
  int<lower=1> obs_idx[N_obs] = which(obs_dummy); // index of observed
  vector[N_obs] x_obs = x_reindex[obs_idx];
  vector[N_obs] x_se_obs = x_se_reindex[obs_idx];

}
parameters {
  vector[N_obs] latent_x;  // latent variable
  real intercept;
  real<lower=0> sigma;
}
model {
  x_obs ~ normal(latent_x, x_se_obs); // Measurement error
  latent_x ~ normal(intercept, sigma); // model latent value
}


```

R code to call the above
```r
x <- c(0, 1, 0, 0, 3, 5, 2)
x_se <- c(Inf, 0.1, Inf, Inf, 0.2, 0.6, 0.4)
sdata <- list(x = x, x_se = x_se, N = length(x))


mod <- cmdstanr::cmdstan_model("shuffle_example.stan")
fit <- mod$sample(sdata, seed = 1, validate_csv = FALSE)
fit$draws("intercept")
#> Error: Supplied CSV files have samples for different variables!

# Diagnose also fails
fit$cmdstan_diagnose()
# Running bin/diagnose \
#   /tmp/RtmptgmtVX/shuffle_example-202008162044-1-198ad9.csv \
#   /tmp/RtmptgmtVX/shuffle_example-202008162044-2-198ad9.csv \
#   /tmp/RtmptgmtVX/shuffle_example-202008162044-3-198ad9.csv \
#   /tmp/RtmptgmtVX/shuffle_example-202008162044-4-198ad9.csv
# terminate called after throwing an instance of 'std::invalid_argument'
#   what():  add(stan_csv): number of columns in sample does not match chains
# Error in processx::run(command = target_exe, args = c(self$output_files(include_failed = FALSE),  : 
#   System command 'diagnose' failed, exit status: -6, stdout & stderr were printed
```

cmdstan: v 2.24.1
cmdstanr: 0.0.0.9008
posterior: 0.1.0 (stan-dev/posterior@d7c0a69)

**Comment by rok-cesnovar** [comment]
Thanks for the report. 

We do have the variables argument for draws(see https://mc-stan.org/cmdstanr/reference/fit-method-draws.html), though that might not help you here as the read csv function will fail because it validates the listed param names even when not reading them.

For now, you can read them in separately with reas_cmdstan_csv(fit$output_files()[1]).

**Comment by karldw** [comment]
Thank you! I think I'm using the `variables` argument for the `draws` method when I call `fit$draws("intercept")`, right? As you predicted, it still raises an error.

Your workaround is much easier than the other options I was considering -- thanks!

**Comment by rok-cesnovar** [comment]
> I think I'm using the `variables` argument for the `draws` method when I call `fit$draws("intercept")`

Yes, that is correct.

@jgabry what do you think of removing the restriction that models need to match on parameter names? I think if the models match on other details like the name and such, we probably don't need this. Most users will not use read_cmstan_csv directly anyways. 

I am only not sure how/if draws_array works if some parameters only have 1 chain while others have 2 for example.

**Comment by jgabry** [comment]
Yeah I'm ok with that in theory but I think the problem, as you anticipated, is with the `draws_array` format. I'm pretty sure `draws_array` assumes a non-ragged array, so I don't think it will work properly if the number of chains isn't the same (and because of that the number of draws isn't the same either). So we would need a new type of draws object that doesn't assume the same number of draws per parameter.

**Comment by rok-cesnovar** [comment]
I an going to close this one as I think will not be feasible. 

You can now also use as_cmdstan_fit() on the different csv files.
