### ISSUE TITLE
Output directory errors with trailing slash on Windows

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#281]
Someone told me that they were having troubles specifying the `output_dir` argument with a trailing slash. I checked in Linux and it works so maybe this is a Windows thing?

Close if it's not possible to reproduce.

Here's a model:
```
parameters {
  real a;
}

model {
  a ~ normal(0, 1);
}
```

Here's R to get an error:
```
library(cmdstanr)
model = cmdstan_model("test.stan")
dir.create("whatever")
fit = model$sample(output_dir = "./whatever/")
```

**Comment by jgabry** [comment]
> I checked in Linux and it works so maybe this is a Windows thing?

Works fine on my mac too. So yeah maybe a Windows thing?

**Comment by jgabry** [comment]
Not urgent at all, but @rok-cesnovar when you have a chance can you check if you can reproduce this on Windows?

**Comment by rok-cesnovar** [comment]
Ah, forgot to post earlier today that yes, I can reproduce on Windows. 

While Unix systems dont mind folder//filename, Windows does not like this. Will hopefully finish a PR tomorrow together with some other Windows related fixes and improvements.

**Comment by jgabry** [comment]
Ok thanks!
