### ISSUE TITLE
expose argument `save_iterations` on `optimize` method; return all iterations

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#282]
see https://github.com/stan-dev/cmdstanpy/issues/281

**Additional context**
Advanced developer feature - useful for testing/diagnosing algorithms.

**Comment by jgabry** [comment]
We haven't had any requests for this in the 4ish years since this issue, so I'm going to close this in favor of prioritizing other features. But we can definitely add this people start requesting it.
