### ISSUE TITLE
Off by one index error in read_cmdstan_csv()

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#292]
As reported by @johnlees in #291, when using `read_cmdstan_csv()` with CmdStan CSV files (_not_ created via CmdStanR), there is an error due to `id` starting at 0 instead of 1.

**Comment by jgabry** [comment]
@johnlees Thanks again for reporting this. I think your follow up comment in your PR is correct. This isn't an issue if the CSV files were generated by CmdStanR, which is why the PR causes those tests to fail. I agree this is worth looking at though because it would be preferable if `read_cmdstan_csv()` worked even if CmdStanR wasn't used to run the model. 

Adding an `index_adjust` argument to `read_cmdstan_csv()` like you suggested is an option, but maybe we can just check if `id` starts at 0 and adjust automatically without the user needing to specify any extra arguments.

@rok-cesnovar What do you think?

**Comment by rok-cesnovar** [comment]
Yeah, cmdstanr uses `seq_len(num of chains)` to generate the chain IDs and the cmdstan manual example starts with zeros.

**Comment by rok-cesnovar** [comment]
This should be done automatically I think.

**Comment by jgabry** [comment]
> and the cmdstan manual example starts with zeros

Yeah, so I think @johnlees you can probably avoid the error for now by running CmdStan with id=1 instead of starting with 0. 

In terms of fixing this, it's also related to https://github.com/stan-dev/cmdstanr/issues/266 because something similar could happen if we allow users to choose the chain_id values in R instead of automatically starting them from 1 and using sequential ids. So my previous suggestion of just detecting if it starts from 0 and adjusting automatically would only be a temporary solution. If we allow the user to pick arbitrary chain ids then we need a more general way of dealing with it since we're using `id` to index lists and vectors: 

https://github.com/stan-dev/cmdstanr/blob/509101797b9e0355cb8cf31fb2add0d2d3d07894/R/read_csv.R#L130

We probably need both a sequential id and a user-specified label, right?

**Comment by rok-cesnovar** [comment]
How about just going with 

inv_metric[[as.character(metadata$id)]] <- metadata$inv_metric

That way we can access by actual ID (which is unlikely anyone will require) and also support id=0.

```r
> a$inv_metric
$`0`
[1] 0.620954

$`1`
[1] 0.487018

$`2`
[1] 0.494204

$`3`
[1] 0.549404

> a$inv_metric[[1]]
[1] 0.620954
> a$inv_metric[["0"]]
[1] 0.620954
```

**Comment by jgabry** [comment]
@rok-cesnovar Yeah treating the id as a name instead of a position when indexing is a good idea. 

@johnlees We can implement this fix but if you want to contribute and modify your PR to do this that would be great too (we like getting new contributors!). Either way is fine, just let us know.

**Comment by johnlees** [comment]
Looks like a very neat solution, thanks! I'm happy to add it to that PR and see if I can get the tests working
