### ISSUE TITLE
`write_stan_json()` doesn't preserve dimension of matrices in data

### ISSUE THREAD

**Issue by bschneidr** [stan-dev/cmdstanr#296]
**Describe the bug**
My model (a multivariate Fay-Herriot model) requires a list of 2x2 covariance matrices as inputs. However, `cmdstanr` seems to mangle the covariance matrices when it writes them to JSON. In the example below, you can see that a two-element list of 2x2 covariance matrices becomes a 2x4 array.

**To Reproduce**
``` r
# Generate fake data consisting of point estimates and accompany vcov matrices
point_estimates <- list(
  c(20,30),
  c(40, 50)
)

cov_matrices <- list(
  matrix(c(20, 30, 20, 30), nrow = 2),
  matrix(c(21, 30, 20, 31), nrow = 2)
)

full_data <- list(
  'point_estimates' = point_estimates,
  'cov_matrices' = cov_matrices
)

# Write the data to JSON
cmdstanr:::write_stan_json(data = full_data,
                           file = "output-json-file.json")

# Read in the results for inspection
json_output <- readLines("output-json-file.json")
cat(json_output, sep = "\n")
#> {
#>   "point_estimates": [
#>     [20, 30],
#>     [40, 50]
#>   ],
#>   "cov_matrices": [
#>     [20, 30, 20, 30],
#>     [21, 30, 20, 31]
#>   ]
#> }
```

<sup>Created on 2020-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Expected behavior**
I would expect the `cov_matrices` section of the JSON file to respect the fact that the elements should be 2x2 matrices, not rows of a four-column matrix, with the JSON for the matrices looking like the following:

```json
"cov_matrices": [
 [[20,30], [20,30]],
 [[21,30], [20,31]]
]
```

**Operating system**
Windows 10

**CmdStanR version number**
0.1.3

**Additional context**
The reason I care about this is that it eventually produces the following error when I try to sample for the model:
`Chain 1 Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=cov_matrices; dims declared=(50,2,2); dims found=(50,4)`, when the model expects a 50-element list, where each element is a 2x2 covariance matrix.

**Comment by jgabry** [comment]
Thanks for reporting this. Definitely looks like a bug. In your Stan program do you have `matrix[2,2] cov_matrices[50]`?

**Comment by bschneidr** [comment]
Hi Jonah, you're right about what the JSON corresponding to that R code is. Please excuse the fact that I mistakenly forgot to specify `byrow = TRUE`, which is necessary for that data (`c(20,30,20,30)`) to be a valid, symmetric 2x2 covariance matrix. Would it be helpful for me to update the reprex accordingly?

To answer your other question: in the data block of the Stan code for the model, I have `cov_matrix[2] cov_matrices[50];`

**Comment by jgabry** [comment]
No worries and no need to update the example, I just wanted to make sure we were on the same page about the correct output. Now that we agree on the output I can proceed with debugging more confidently! 

> To answer your other question: in the data block of the Stan code for the model, I have `cov_matrix[2] cov_matrices[50];`

Oh ok, that makes sense.

**Comment by jgabry** [comment]
Ok I may have sorted this out. Can you try installing CmdStanR from a branch I just created and checking if it works for you? 

```r
devtools::install_github("stan-dev/cmdstanr", ref = "fix-list-of-matrices")
```

**Comment by jgabry** [comment]
@bschneidr Just following up to see if you were able to check if that branch solves the data problem you were running into. No worries if you haven't had time.

**Comment by bschneidr** [comment]
@jgabry Hi Jonah. Thanks for addressing this so quickly! I'm sorry I haven't been able to check whether this solves the problem quite yet. I should be able to check tomorrow afternoon (Thursday 9/17) when I'm able to access the data involved again. But if you're in a rush to implement this change, please don't feel delayed on my account.

**Comment by jgabry** [comment]
No problem, whenever you end up having time I'd love to hear if it works for you but I definitely won't let it hold this up if I'm certain it's fixed. Thanks!

**Comment by bschneidr** [comment]
@jgabry, this completely fixed the problem I was running into. Thanks again for implementing this!

**Comment by jgabry** [comment]
Oops, just realized I forgot to respond. Thanks for checking, glad this fixed it!
