### ISSUE TITLE
Deprecate `output_dir` in favor of `dir`

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#297]
Per the discussion over at https://github.com/stan-dev/cmdstanpy/issues/289, for consistency we should change the `output_dir` argument of the model fitting methods to `dir` to match the argument name used in `install_cmdstan()` and the `compile()` method.

**Comment by rok-cesnovar** [comment]
Closing due to reasons outlined here: https://github.com/stan-dev/cmdstanr/pull/312
