### ISSUE TITLE
cmdstan_model constructor arg `include_paths` redundant given `stanc_options`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#298]
Comparing CmdStanR interface to CmdStanPy - separate arg `include_paths` not in CmdStanPy, which uses `stanc_options` instead.

For CmdStanPy, would strongly prefer to keep just `stanc_options` - assuming proper documentation and good error messaging.

Is it OK for interfaces to diverge on this point?

**Comment by jgabry** [comment]
This is a good point. Using includes is common enough that it seemed natural to have an easy to use separate argument for it, but I agree it’s redundant and that’s definitely suboptimal from a design perspective. @rok-cesnovar Any preference either way?

**Comment by rok-cesnovar** [comment]
Sorry, I missed this one. I have no preference in this case. Unifying seems fine to me.

**Comment by jgabry** [comment]
After thinking about this more, I'm convinced that we should keep the `include_paths` argument for the same reason I mentioned in #358 for why we should add a `pedantic` argument. Basically, I don't think it's reasonable to ask the user to specify compiler flags unless they want to use a super advanced feature. Something like `include_paths` should not be considered an advanced feature (in fact people should probably use it more than they currently do to avoid code duplication issues), so I don't think a compiler flag is appropriate (many users probably don't even know what compiler flags are).

**Comment by rok-cesnovar** [comment]
@jgabry I am guessing we can close this as well given what we decided with `pedantic`?

**Comment by jgabry** [comment]
Yeah I'll close it now.
