### ISSUE TITLE
read_cmdstan_csv efficiency issue for large number of parameters

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/cmdstanr#299]
**Describe the bug**
CSV read speed drastically degrades when the number of params is large(>10^5) .

**To Reproduce**
@billgillespie and I ran into a model with 10^6 params and `read_cmdstan_csv` becomes stalled . I was able to reproduce it with the following dummy model
```stan
parameters {
  real k;
}

transformed parameters {
  real x[100000] = rep_array(k, 100000);
}

model {
  k ~ normal(0, 1);
}
```
The output file contains only one sample:
```bash
./dummy sample algorithm=fixed_param num_warmup=0 num_samples=1 output file=dummy.csv
```

`rstan::read_stan_csv` vs `cmdstanr::read_cmdstan_csv`:
```r
> system.time(fit <- cmdstanr::read_cmdstan_csv("dummy.csv"))
   user  system elapsed 
 55.873  26.429  67.056 
> system.time(fit <- rstan::read_stan_csv("dummy.csv"))
   user  system elapsed 
  5.449   0.341   5.847 
```

**Expected behavior**
More realistic reading speed in this scenario.

**Operating system**
macos mojave 
```r
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2    tcltk_3.6.2   
```

**CmdStanR version number**
```r
> library("cmdstanr")
This is cmdstanr version 0.1.3
- Online documentation and vignettes at mc-stan.org/cmdstanr
- Use set_cmdstan_path() to set the path to CmdStan
- Use install_cmdstan() to install CmdStan
```

**Comment by mike-lawrence** [comment]
You're not seeing a message that says "Fast CSV reading with vroom::vroom() failed." are you?

If not, then reading the csv's already employ's the current fastest csv-reading method, [vroom](https://cran.r-project.org/web/packages/vroom/vignettes/benchmarks.html). Someday `cmdstan` will move to a proper binary output format and be ridiculously faster, but for now we're stuck with the current speeds.

**Comment by mike-lawrence** [comment]
Ah, slight correction: I guess `data.table::fread()` is slightly faster than `vroom::vroom()`, and while it's possible that `cmdstanr` might move to the former for it's lighter dependency requirements, that probably won't yield noticeable speed improvements.

**Comment by rok-cesnovar** [comment]
Thanks for the report @yizhang-yiz and sorry for the issues. Will take a look this weekend.

**Comment by yizhang-yiz** [comment]
> You're not seeing a message that says "Fast CSV reading with vroom::vroom() failed." are you?

No.

> I guess data.table::fread() is slightly faster than vroom::vroom()

@billgillespie just tested it and fread is much faster.

**Comment by mike-lawrence** [comment]
> @billgillespie just tested it and fread is much faster.

Cool! Did you guys do this test in a fork of cmdstanr? If so, feel free to do a pull request!

**Comment by dpastoor** [comment]
FYI, from vroom itself:

https://vroom.r-lib.org/articles/benchmarks.html#all-numeric-data

> All numeric data is really a worst case scenario for vroom. The index takes about as much memory as the parsed data. Also because parsing doubles can be done quickly in parallel and text representations of doubles are only ~25 characters at most there isn’t a great deal of savings for delayed parsing.

> For these reasons (and because the data.table implementation is very fast) vroom is a bit slower than fread for pure numeric data.

![image](https://user-images.githubusercontent.com/3196313/93712099-6e39dd80-fb21-11ea-9ef5-6632593687c6.png)

**Comment by rok-cesnovar** [comment]
Sorry for the radio silence on this issue. After debugging this issue for some time I took another look at fread and some preliminary tests show that we can just replace vroom with data.table  and its fread function. Either data.table was updated recently to play nicer with Stan CSV or I was sloppy in my initial testing of fread. 

this will get sorted by replacing vroom with fread which will also close https://github.com/stan-dev/cmdstanr/issues/262 and https://github.com/stan-dev/cmdstanr/issues/198

**Comment by rok-cesnovar** [comment]
Can someone on a mac try the following: 

```r
library(cmdstanr)
library(data.table)

model_code <- "
parameters {
  real k;
}

transformed parameters {
  real x[100000] = rep_array(k, 100000);
}

model {
  k ~ normal(0, 1);
}
"
model_file <- write_stan_file(model_code)
mod <- cmdstan_model(model_file)
fit <- mod$sample(iter_sampling = 1, iter_warmup = 200, validate_csv = FALSE, chains = 4)

a <- Sys.time()
t1 <- rstan::read_stan_csv(fit$output_files())
print(Sys.time()-a)

a <- Sys.time()
t2 <- list()
for (f in fit$output_files()) {
  t2[[f]] <- fread(cmd= paste0("grep -v '^#' ", f))
}
print(Sys.time()-a)
```
The grep thing is ugly but necessary as `fread` does not support comment.char. There is an equivalent Windows approach to this. On Linux this is really fast.

**Comment by yizhang-yiz** [comment]
```r
Running MCMC with 4 sequential chains...

Chain 1 Iteration:   1 / 201 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 201 [ 49%]  (Warmup) 
Chain 1 Iteration: 200 / 201 [ 99%]  (Warmup) 
Chain 1 Iteration: 201 / 201 [100%]  (Sampling) 
Chain 1 finished in 0.2 seconds.
Chain 2 Iteration:   1 / 201 [  0%]  (Warmup) 
Chain 2 Iteration: 100 / 201 [ 49%]  (Warmup) 
Chain 2 Iteration: 200 / 201 [ 99%]  (Warmup) 
Chain 2 Iteration: 201 / 201 [100%]  (Sampling) 
Chain 2 finished in 0.2 seconds.
Chain 3 Iteration:   1 / 201 [  0%]  (Warmup) 
Chain 3 Iteration: 100 / 201 [ 49%]  (Warmup) 
Chain 3 Iteration: 200 / 201 [ 99%]  (Warmup) 
Chain 3 Iteration: 201 / 201 [100%]  (Sampling) 
Chain 3 finished in 0.2 seconds.
Chain 4 Iteration:   1 / 201 [  0%]  (Warmup) 
Chain 4 Iteration: 100 / 201 [ 49%]  (Warmup) 
Chain 4 Iteration: 200 / 201 [ 99%]  (Warmup) 
Chain 4 Iteration: 201 / 201 [100%]  (Sampling) 
Chain 4 finished in 0.2 seconds.

All 4 chains finished successfully.
Mean chain execution time: 0.2 seconds.
Total execution time: 0.9 seconds.
> Time difference of 8.561616 secs
> + + > Time difference of 1.311881 secs
> 
```

**Comment by rok-cesnovar** [comment]
Cool, thanks. 

At least for unix systems then this looks promising. For windows we can use findstr.
Hopefully that will work.

No comment.char in fread is a longstanding issue (https://github.com/Rdatatable/data.table/issues/856#issue-comment-box) and there does not seem to be much traction there, so this grep/findstr thing will have to do.

**Comment by spinkney** [comment]
fwiw, it was taking a super long time on a recent model for fit$summary() that I just stopped it. Running the above from Rok on my model yields
```
> a <- Sys.time()
> t1 <- rstan::read_stan_csv(fit_vi$output_files())
Warning messages:
1: In parse_stancsv_comments(comments) :
  line with "Elapsed Time" not found
2: In validityMethod(object) :
  The following variables have undefined values:  log_p__. Many subsequent functions will not work correctly.
> print(Sys.time()-a)
Time difference of 3.083478 mins
> 
> a <- Sys.time()
> t2 <- list()
> for (f in fit_vi$output_files()) {
+   t2[[f]] <- fread(cmd= paste0("grep -v '^#' ", f))
+ }
> print(Sys.time()-a)
Time difference of 20.21756 secs
```
9x faster!

**Comment by bbbales2** [comment]
I was having some issues with slow reads lately and running the code above and comparing against develop cmdstanr I'm getting

rstan 8.5s
fread 1.6s
cmdstanr 13s

Did something need changed that means the fread solution doesn't work or does it seem like I'm doing something wrong?

Test code was that above plus:
```
a <- Sys.time()
tmp <- cmdstanr::read_cmdstan_csv(fit$output_files())
print(Sys.time()-a)
```

**Comment by rok-cesnovar** [comment]
For fastest reading use draws_format = “draws_list”

see https://github.com/stan-dev/cmdstanr/pull/482

**Comment by bbbales2** [comment]
Uh oh, still seems like something is going wrong. I'm installing my cmdstanr from Github.

I ended up needing to make the vector 10x smaller than it is in the example. The output is now:

```
> a <- Sys.time()
> t1 <- rstan::read_stan_csv(fit$output_files())
> print(Sys.time()-a)
Time difference of 0.7841558 secs
> 
> a <- Sys.time()
> t2 <- list()
> for (f in fit$output_files()) {
+   t2[[f]] <- fread(cmd= paste0("grep -v '^#' ", f))
+ }
> print(Sys.time()-a)
Time difference of 0.207078 secs
> 
> a <- Sys.time()
> tmp <- fit$draws(format = "draws_list")
> print(Sys.time()-a)
Time difference of 17.68409 secs
```

This is on Ubuntu and I also got it on a Mac. I'm getting cmdstanr with `remotes::install_github("stan-dev/cmdstanr")`.

**Comment by bbbales2** [comment]
Anyway can follow up in the week. Gonna go mess around with some other stuff for now.

**Comment by jgabry** [comment]
Thanks @bbbales2. @rok-cesnovar Ssould we reopen this?

**Comment by rok-cesnovar** [comment]
Sure thing. I cant replicate locally so will need to wait for Ben to give more info

**Comment by jgabry** [comment]
Reopening so we don't forget to follow up with @bbbales2 about this when he has time

**Comment by jgabry** [comment]
And there was just another report of a (potentially different) problem with the efficiency on discourse: 

https://discourse.mc-stan.org/t/cmdstanr-fails-to-read-its-own-csv-files-for-large-number-of-parameters/22450

**Comment by jgabry** [comment]
> > a <- Sys.time()
> > tmp <- fit$draws(format = "draws_list")
> > print(Sys.time()-a)
> Time difference of 17.68409 secs

@bbbales2 I think the issue here is that you're using the `draws()` method which calls `posterior::subset_draws()`. We just fixed a major efficiency problem with `posterior::subset_draws()` so I'm hoping that fixes your issue. If you update posterior and cmdstanr again from GitHub and try again do you still see the really bad timing for draws()?

**Comment by bbbales2** [comment]
Looks like this worked wonders. Performance is:

```
> a <- Sys.time()
> t1 <- rstan::read_stan_csv(fit$output_files())
> print(Sys.time()-a)
Time difference of 8.895082 secs
> 
> a <- Sys.time()
> t2 <- list()
> for (f in fit$output_files()) {
+   t2[[f]] <- fread(cmd= paste0("grep -v '^#' ", f))
+ }
> print(Sys.time()-a)
Time difference of 2.123384 secs
> 
> a <- Sys.time()
> tmp <- cmdstanr::read_cmdstan_csv(fit$output_files())
> print(Sys.time()-a)
Time difference of 12.8633 secs
> 
> a <- Sys.time()
> tmp <- fit$draws()
> print(Sys.time()-a)
Time difference of 9.908498 secs
> 
> a <- Sys.time()
> tmp <- fit$draws(format = "draws_list")
> print(Sys.time()-a)
Time difference of 8.237552 secs
```

I'm still kinda :eyes: at the fread performance but this'll work!

**Comment by rok-cesnovar** [comment]
The rest of it comes down to parsing the rest of the CSV (metadata). We could maybe add an option to not return that?

**Comment by jgabry** [comment]
> The rest of it comes down to parsing the rest of the CSV (metadata). We could maybe add an option to not return that?

Yeah maybe that's worth it

**Comment by bbbales2** [comment]
Hmm, that sounds like one of those edge features I'll forget to use even if it's there (so might not be worth the maintenance cost). I'll letcha know if things get prohibitively slow, but this is probably good.

**Comment by jgabry** [comment]
> Reopening so we don't forget to follow up with @bbbales2 about this when he has time

Will close this again since I think it's resolved now by the fix in the posterior package

**Comment by mike-lawrence** [comment]
> Sorry for jumping on an old issue but has there been any further updates with regards to switching to a binary format. The [linked thread](https://discourse.mc-stan.org/t/status-of-the-io-re-factor/17176) further up in this chat appears to have gone cold. 

The latest design proposal is [here](https://github.com/stan-dev/design-docs/blob/master/designs/0032-stan-output-formats.md)


> Having done a few projects recently where I used parquet/arrow to read multiple GB of data in seconds I can't help but feel that adopting a binary format would provide some major benefits.

Feel like you have enough skill with those formats to contribute? I think bandwidth of the devs is the major limitation on this. 


> In particular on a recent project using cmdstanr I was struck by the slow read times for models with lots of generated quantities (despite the improvements that have been made and documented here).  It would be good if this could be reduced further by a more performant format. 

Some workarounds in the meantime:
- Sample with a model that omits the GQs, generating them (only after models sample and pass diagnostics) either with the generate_quantities method or (possibly faster since it doesn't involve writing to disk) the newer expose_methods() tools to run the compiled C code from R. n.b. I haven't done the latter yet myself but it is on my to-try)
- if we're talking models that take a long time to sample, take inspiration from the currently-broken [aria](https://github.com/mike-lawrence/aria) package and move the data to a more performant binary during sampling. (aria uses netcdf, but it has a huge bottleneck even initializing models with large numbers of variables, so I've been planning on switching to zarr but haven't gotten around to it)

**Comment by mike-lawrence** [comment]
> I hadn't realised that you could make separate calls to generated quantities, I think this could potentially improve the design of our current code so thank you for pointing it out.

(back at my laptop, so can make a more detailed response) The way to do this is to make two copies of your model, one with no GQ section and one with it. Sample with the no-gq model and then do:
```r
gq_mod$generate_quantities(
	data = original_data
	, fitted_params = no_gq_mod_post$draws()
)
```
But again, that approach involves a bunch of IO that can be skipped. For that approach, for each quantity in GQ, you'd extract it's compute steps and turn them into a function. So, this
```stan
generate quantities{
  vector[n] x = ... ; // some compute involving parameters a & b
}
```
becomes
```stan
functions{
    vector get_x( ... ){
     ...
    }
```
and then in R you'd use `expose_functions()` to gain access to `get_x()`, then loop over your draws running `this_draw$x = get_x(this_draw$a, this_draw$b)`.
