### ISSUE TITLE
Not working with _relative_ paths to Stan programs outside cmdstan dir 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#30]
If the user supplies a _relative_ path to a Stan program that’s outside the cmdstan directory I think we need to convert it to a full path before calling the executable. Unfortunately `tools::file_path_as_absolute` and other standard mechanisms sometimes still return relative paths. @rok-cesnovar any ideas?

**Comment by rok-cesnovar** [comment]
So my understanding is that the user specifies the relative path relative to their working directory right? Wouldnt just concatenating `getwd()` and whatever they specified work here? I may be missing something obvious, idk.

From the docs: `getwd returns an absolute filepath representing the current working directory of the R process`

Or was the intention of having relative path relative to the cmdstan folder. I think R users are more acustomed to the former. But not really sure.

**Comment by jgabry** [comment]
Thanks, I was overthinking it. You’re right that it will  be relative to the working directory, so I  think you’re right that concatenating with getwd() should be fine. I’ll try that.

**Comment by jgabry** [comment]
It’s working but I’m reopening this until I add some tests for this.
