### ISSUE TITLE
nice if there was a way to exclude parameters from fit object

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/cmdstanr#305]
**Is your feature request related to a problem? Please describe.**
I have a model with about 10-15 interesting parameters and more than 1000 nuisance parameters. `rstan` offers a feature where you can include/exclude parameters to reduce the amount of data that needs to be moved around.

**Describe the solution you'd like**
I'm not sure. The best solution would be if `cmdstan` could be told not to record a subset of parameters in the output CSVs.

Failing that, it would be helpful if I could drop a subset of parameters from a fit object and then save it much more compactly on disk. So I might tell `cmdstan` to output to /tmp (a local solid state disk), filter the parameters, and re-write the output in compact form to a network disk.

**Describe alternatives you've considered**
Is this functionality already available in `cmdstanr`? How do you think it should be supported?

**Comment by rok-cesnovar** [comment]
Hi, thanks for the request.

There is currently a way to save RAM by not reading in all the parameters from the resulting CSV to the fit object. You can do that by specifying the `variables` argument to fit$draws() at which point CmdStanR will only read in the requested variables (unless they have already been read in).

But based on your post you are more interested in a feature where we would only write selected parameters to the CSV. That needs to first be done in cmdstan. There is a longstanding issue for that https://github.com/stan-dev/cmdstan/issues/553
Once that is implemented cmdstanr can support that easily.

**Comment by jpritikin** [comment]
Ah, nice to know about that argument to `fit$draws()`. Maybe that will be sufficient for the task at hand.
