### ISSUE TITLE
Add output sig_figs

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#313]
Cmdstan 2.25 will have the output sig_figs argument, see https://github.com/stan-dev/cmdstan/issues/922

cmdstan call will be:

`./model sample data file=data.json output sig_figs=12`

We should support that.

**Comment by jgabry** [comment]
Can we just always use max sig_figs and avoid adding a new argument? Or is it preferable not to default to max and make the user request it?

**Comment by rok-cesnovar** [comment]
In the CSV format more precision means larger files. Typically more than 6 sig figs do not really have a huge effect, but it sometimes does, like the case where this came up or this old issue in cmdstan: https://github.com/stan-dev/cmdstan/issues/521.

We could go with something larger than 6 for default, but 18 is probably too much.

**Comment by jgabry** [comment]
Oh ok, good point. I think it's fine to add this argument then.

**Comment by rok-cesnovar** [comment]
You would probably have a better feeling how common these cases are and what would be a good default.

**Comment by jgabry** [comment]
Hmm, yeah I'm not sure but I'll think about it. I'm actually a bit surprised that issues like the one about outputting covariance matrices don't come up more often.
