### ISSUE TITLE
investigate "summary" for "optimize" fit object

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#315]
**Describe the issue**
User reports that calling `summary` method is slow for optimize output
https://discourse.mc-stan.org/t/summary-method-slow-for-large-models/18147/10

**Comment by rok-cesnovar** [comment]
This is the same issue as https://github.com/stan-dev/cmdstanr/issues/299 and will be fixed by closing https://github.com/stan-dev/cmdstanr/issues/262

I think we can close this one.
