### ISSUE TITLE
Any reason to use devtools::install_github over remotes::install_github

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstanr#317]
The devtools folks created the [remotes](https://github.com/r-lib/remotes) package as a lighter-weight successor for simply doing installs like `install_github()`. Is there any reason for continued use of `devtools` in the `cmdstanr` guides? (ditto for the rest of the Stan-iverse?)

**Comment by rok-cesnovar** [comment]
> Is there any reason for continued use of `devtools` in the `cmdstanr` guides

I don't think so. Probably more of a habit.

**Comment by jgabry** [comment]
Yeah no reason at all other than habit. If you or anyone else wants to change them to remotes::install_github() that would be great! Otherwise I can add it to my mile long to-do list ;)
