### ISSUE TITLE
error: PCH file uses an older PCH format that is no longer supported

### ISSUE THREAD

**Issue by beyondpie** [stan-dev/cmdstanr#321]
**Describe the bug**
Using cmdstanr::cmdstan_model  compile model  faces the error: 
PCH file uses an older PCH format that is no longer supported

**Operating system**
Mac OS 10.15.7

**CmdStanR version number**
0.1.3

**Comment by beyondpie** [comment]
This program is workable on Linux Ubuntu use the same function.

**Comment by beyondpie** [comment]
https://github.com/stan-dev/cmdstanpy/issues/108 
I notice that a related issues in cmdstanpy. But I didn't get any hints there.

**Comment by jgabry** [comment]
Hmm, can you try running rebuild_cmdstan() and then see if the error persists?

**Comment by beyondpie** [comment]
@jgabry 
Interesting! It now works! Thank you!

**Comment by rok-cesnovar** [comment]
This is an issue that pops up on macOS sometimes when xcode upgrades. I think it happens often enough that we should try to catch this error message and signal to the user that rebuild_cmdstan() is the solution.

Weirdly this does not pop up on Linux if I upgrade the clang compiler.

I am going to reopen this and we can close this once we have a way to suggest to the user to rebuild cmdstan.

**Comment by mitzimorris** [comment]
I've hit this a couple of times and added a mention specifically of PCH files in the CmdStan doc.  as the docs are not a very good solution, I like Rok's suggestion of trying to catch the error message and do the right thing.

**Comment by jgabry** [comment]
@beyondpie glad it's working now. @rok-cesnovar @mitzimorris Yeah it would be great to catch this error.

**Comment by beyondpie** [comment]
One strange thing is: 
- I use cmdstanr install the newest cmdstan (2.25.0)
- then I compile the model, it's OK.
- and I modified the model. cmdstan report bugs in the model.
- I correct it. Then compile the model. It says PCH file uses an older PCH format. 
- I have to use `rebuild_cmdstan()`, then it works.

But during this process, I didn't update my Xcode or Mac system...

**Comment by rok-cesnovar** [comment]
So this happens every time? Or just once and now it will work?

Do you use any compile flags like stan_threads?

**Comment by beyondpie** [comment]
@rok-cesnovar 
- I don't use any compile flags (though in the future, I plan to use GPU support...)
- I modified the stan script, it happens again.
- BTW, I use `cmdstanr::cmdstan_model( my_stan_file,   compile = T  )` to compile the model. I notice there is a arg `force_recompile = FALSE`.  I try to set it as T, but it's not useful.

One more details:
- when I have a successful compiled stan model 
- then I update the stan script, and try to compile again (before compiling, I remove the old compiled one)
- `error: PCH file uses a newer PCH format that cannot be read`

**Comment by beyondpie** [comment]
I don't know the details. But seems there is some cache during compiling ? And only when I `rebuild_stan`, the cache is cleared?

**Comment by mitzimorris** [comment]
>then I update the stan script, and try to compile again 

by script you mean the `model.stan` file?
every time you update a Stan program and recompile, you get this error?

**Comment by beyondpie** [comment]
@mitzimorris 

- Yes. `model.stan` file. 
- Not every time. I face this problem in the morning. And then seems OK ...

**Comment by rok-cesnovar** [comment]
Thanks for all the info. 

If you can help us investigate this a bit more: Can you `cmdstan_model(..., quiet = FALSE)` and tell me if its compiled with g++ or clang?

Googling this a bit it seems this is Xcode related.

**Comment by beyondpie** [comment]
@rok-cesnovar 
Yesterday, everything seems OK after I recompile cmdstan. But today I delete one comment line in the STAN script, then it failed again ... 
![image](https://user-images.githubusercontent.com/6449478/97579091-043a1100-19c8-11eb-9dd5-ae95004f09a0.png)

**Comment by beyondpie** [comment]
I `rebuild_cmdstan()`, then it's OK.
![image](https://user-images.githubusercontent.com/6449478/97579693-c093d700-19c8-11eb-9268-2a1b75dd991b.png)

**Comment by beyondpie** [comment]
@rok-cesnovar 
Seems that, after `rebuild_cmdstan()`, the first step in make is different.  Maybe some file exists, and makefile jumps to the next command before I `rebuild_cmdstan()` ?

**Comment by rok-cesnovar** [comment]
Can you post the output of `cmdstan_make_local()`

**Comment by rok-cesnovar** [comment]
99% is that it will return nothing, but just to double check.

**Comment by beyondpie** [comment]
> Can you post the output of `cmdstan_make_local()`

It returns `character(0)`

**Comment by beyondpie** [comment]
@rok-cesnovar 
I compile the model in a R console repeatedly, not in the terminal.  Hope this is fine.

**Comment by rok-cesnovar** [comment]
Yeah, that should definitely not be a problem. 

I keep seeing suggestions to set GCC_PRECOMPILE_PREFIX_HEADER=NO in Xcode, though I honestly have zero ideas on how to do that. I, unfortunately, have no experience with macOS.

Maybe: 

```r
cmdstan_make_local(cpp_options = "GCC_PRECOMPILE_PREFIX_HEADER=NO", append = TRUE)
rebuild_cmdstan()
```

which writes this in the makefile. But I doubt that.

What does 

```r
p <- processx::run("clang++", args = "--version")
cat(p$stdout)
```

return?

**Comment by beyondpie** [comment]
> ```r
> p <- processx::run("clang++", args = "--version")
> cat(p$stdout)
> ```

It returns: 
```Apple clang version 12.0.0 (clang-1200.0.31.1)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by beyondpie** [comment]
> Maybe:
> 
> ```r
> cmdstan_make_local(cpp_options = "GCC_PRECOMPILE_PREFIX_HEADER=NO", append = TRUE)
> rebuild_cmdstan()
> ```
> 
> which writes this in the makefile. But I doubt that.

Thanks. I will give it a try tomorrow morning because I notice that I face this compile issue every morning. Then it works in the day....

**Comment by rok-cesnovar** [comment]
> It returns:

are you sure there is not one more line before the Target line? That should have the clang version.

> I will give it a try tomorrow morning because I notice that I face this compile issue every morning. 

Thanks! Do this at the end of today and then if this repeats tomorrow morning we can dig further. Sorry for the troubles.

**Comment by beyondpie** [comment]
> are you sure there is not one more line before the Target line? That should have the clang version.

Sorry for this. I correct the information.

> Thanks! Do this at the end of today and then if this repeats tomorrow morning we can dig further. Sorry for the troubles.

Sure. Thank you very much! At least, I know `rebuild_cmdstan()` works when I face this issue.

**Comment by rok-cesnovar** [comment]
One thing that comes to mind. Is this actually clang 12? Is that what install with Xcode on macOS? I think clang 11 is the last release and 12 is "develop".

**Comment by jgabry** [comment]
Hmm, interesting. It definitely says clang 12 on my mac too:

```jgabry@Jonahs-MacBook-Pro ~ % clang --version
Apple clang version 12.0.0 (clang-1200.0.32.21)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by beyondpie** [comment]
@rok-cesnovar 

I follow this yesterday, but today I can still get the error.
```
cmdstan_make_local(cpp_options = "GCC_PRECOMPILE_PREFIX_HEADER=NO", append = TRUE)
rebuild_cmdstan()
```
![image](https://user-images.githubusercontent.com/6449478/97722671-45522400-1aa1-11eb-9494-9bfe5b91e17e.png)

**Comment by rok-cesnovar** [comment]
Thanks!

Looking at your output I am not sure why there is a `-I/usr/local/opt/llvm/include`. I don't see that in my clang compile output.

**Comment by beyondpie** [comment]
> Thanks!
> 
> Looking at your output I am not sure why there is a `-I/usr/local/opt/llvm/include`. I don't see that in my clang compile output.

Yes. I notice that in my bash env, I add 
```
export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib  -L/usr/local/opt/openblas/lib"$
export CPPFLAGS="-I/usr/local/opt/llvm/include -I/usr/local/opt/openblas/include"$
```
I use this for other projects. Will this influence the compelling results ?

**Comment by rok-cesnovar** [comment]
Ah okay, it probably should not, but clang is a part of llvm so that got me thinking in this direction and I have never seen that before.
