### ISSUE TITLE
$optimize() prints output for every iteration when refresh = 0 and algorithm = newton

### ISSUE THREAD

**Issue by tcuongd** [stan-dev/cmdstanr#323]
Hello! I'm currently running `cmdstanr` within RStudio.

**Describe the bug**

When setting `refresh = 0` and `algorithm = "newton"` for the `$optimize()` method, the output for every iteration gets printed to the console (the format of the message is `Iteration []. Log join probability = []. Improved by [].`, and there is one message per line). This issue does not occur for `algorithm = "lbfgs" | "bfgs"`.

**To Reproduce**
```
file <- file.path(cmdstan_path(), "examples/bernoulli/bernoulli.stan")
mod <- cmdstan_model(file)
stan_data <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
mod$optimize(
  data = stan_data,
  seed = 123,
  algorithm = "newton",
  refresh = 0
)
```

**Expected behavior**
No console output.

**Operating system**
```
Running under: macOS Catalina 10.15.6
Platform: x86_64-apple-darwin19.4.0 (64-bit)
```

**CmdStanR version number**
```
cmdstanr_0.1.3
.cmdstanr/cmdstan-2.24.1
```

**Comment by rok-cesnovar** [comment]
I am guessing this is with `algorithm = "newton"`. Can you confirm?

**Comment by tcuongd** [comment]
> I am guessing this is with `algorithm = "newton"`. Can you confirm?

Yes that's right! I haven't actually tried it for the other algorithms, will confirm that and update the opening post.

**Comment by tcuongd** [comment]
> I am guessing this is with `algorithm = "newton"`. Can you confirm?

Yep so this isn't an issue for `lbfgs` and `bfgs`. Have updated the opening post with more details and a full example. Thank you!

**Comment by rok-cesnovar** [comment]
There is a PR open for this, you can try it out with 

`remotes::install_github("stan-dev/cmdstanr@zero_refresh_fix")`
