### ISSUE TITLE
seed = 0 is invalid here (while it is valid in rstan)

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/cmdstanr#325]
**Describe the issue**
Just wanted to point out that while rstan accepts a seed of `0`, cmdstanr allows only values over 1. Is this on purpose? It's just mildly annoying when I want to use rstan functions with cmdstanr

**CmdStanR version number**
0.1.3

**Comment by rok-cesnovar** [comment]
This is a limit that cmdstan enforces. I am not completely sure why its > 0 not >= 0. 

Opened an issue: https://github.com/stan-dev/cmdstan/issues/941

**Comment by rok-cesnovar** [comment]
This was fixed in cmdstan and the next release will allow seed = 0. Will open a separate issue to track progress on supporting new 2.26 features that require changes in cmdstanr. Thanks!
