### ISSUE TITLE
model_name consistency: stan file or exe?

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstanr#337]
I notice that there's a few places in model.R where `model_name` is computed differently. Sometimes it's taken from the name of the stan file, sometimes from the name of the exe and these can be different (i.e. the exe can get a suffix with some combination of `_threads`, `_mpi` and `_opencl`; there's also a [PR](https://github.com/stan-dev/cmdstanr/pull/306) that will mean that the exe will *always* have a suffix containing the hash of the auto-formatted stan code).

Is there any use for having the `model_name` variable/attribute match the exe? Or should we simplify and default to using the stan file?

**Comment by rok-cesnovar** [comment]
> (i.e. the exe can get a suffix with some combination of _threads, _mpi and _opencl;

That was used to simplify switching threads/mpi/opencl on and off for 2.23 and earlier, but can be removed now. Will clean that up in a few hours.

**Comment by rok-cesnovar** [comment]
Otherwise, this should be consistent I agree. Thanks for bringing that up!

**Comment by mike-lawrence** [comment]
So `  model_name <- sub(" ", "_", paste0(strip_ext(basename(self$stan_file())), "_model"))` throughout, yes?

**Comment by rok-cesnovar** [comment]
I think the _model is unnecessary yes.

**Comment by jgabry** [comment]
I agree, thanks!
