### ISSUE TITLE
More informative error messages for stanc options

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#339]
Was working with @hyunjimoon on a project and we were trying to use the `stanc_options` argument to do `allow-undefined`.

Eventually we iterated to the right solution (which is documented via example), but before we got there we tried two things that can probably be detected return more informative errors.

First was:

```
> cmdstan_model("stan/sir.stan", stanc_options = list("--allow-undefined"))
Compiling Stan program...
bin/stanc: unknown option '--=--allow-undefined'.
Usage: stanc [option] ... <model_file.stan>
  --debug-lex                      For debugging purposes: print the lexer actions
  --debug-parse                    For debugging purposes: print the parser actions
...
```

This could print something like:

```
No leading hyphens in arguments. For example `stanc_options = list("pedantic-mode" = TRUE)`
```

The second was:
```
> cmdstan_model("stan/sir.stan", stanc_options = list("allow-undefined"))
Compiling Stan program...
bin/stanc: unknown option '--=allow-undefined'.
Usage: stanc [option] ... <model_file.stan>
  --debug-lex                      For debugging purposes: print the lexer actions
```

Which I guess overloads with the first, but the error here is that the options list requires a key and a value. I'm assuming there's a way to detect that in R and say that?

```
Compiler options should have a key and value, like `stanc_options = list("pedantic-mode" = TRUE)`
```

(or whatever R calls the list keys/values)

**Comment by rok-cesnovar** [comment]
> No leading hyphens in arguments. For example `stanc_options = list("pedantic-mode" = TRUE)`

Good call.

> Which I guess overloads with the first, but the error here is that the options list requires a key and a value. I'm assuming there's a way to detect that in R and say that?

How about if we just fix this so that `list("pedantic-mode")`  so that its the same as `list("pedantic-mode" = TRUE)`. We can do that easily.

**Comment by bbbales2** [comment]
> How about if we just fix this so that list("pedantic-mode") so that its the same as list("pedantic-mode" = TRUE). We can do that easily.

That seems good too!

**Comment by rok-cesnovar** [comment]
Thanks for the feedback. We could also probably trim the leading "--" silently so that both "--pedantic-mode" and "pedantic-mode" would work. Or is that confusing?

**Comment by bbbales2** [comment]
Just as long as it doesn't get hard to maintain or misleading, I think. If they're both valid, then we'll end up with code that uses both.

**Comment by rok-cesnovar** [comment]
Yeah, makes sense. Lets go without the leading “—“

**Comment by rok-cesnovar** [comment]
Fixed in https://github.com/stan-dev/cmdstanr/pull/343
