### ISSUE TITLE
`quiet` option for cmdstan_diagnose()

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstanr#341]
Any objections to adding a quiet option to cmdstan_diagnose() for use in automated model fitting/checking workflows? If not, I'll do a PR.

**Comment by jgabry** [comment]
Fine by me!

**Comment by beyondpie** [comment]
@mike-lawrence 

how you implement the "quiet" option ? 
I also want to "silent" the  log information during fitting, and only leave my "message()" information for extra things.

**Comment by mike-lawrence** [comment]
@beyondpie Presumably you're referring to the messages that are printed when you run either `mod$sample()`, `mod$optimize()` or `mod$variational()` in which case you should be able to supply the argument `refresh=0` to prevent them.

**Comment by beyondpie** [comment]
@mike-lawrence thanks!  I miss-understand `refresh`, I set it to maximum iteration number. 
Good to know this, thanks again.

**Comment by beyondpie** [comment]
@mike-lawrence 
Still has the log like `Initial log joint probability = ...,  Optimization terminated normally, ...`. Do you have any idea to not output them too?

**Comment by jgabry** [comment]
Can you try installing cmdstanr again using `install_github("stan-dev/cmdstanr")`? We somewhat recently reduced the output for optimization if refresh=0. When I try it with refresh=0 the only output I see is it saying "Finished" and the amount of time it took:

```
> fit <- mod$optimize(data = stan_data, refresh = 0)
Finished in  0.1 seconds.
```

**Comment by beyondpie** [comment]
@jgabry 
Sure.  BTW, do you know how to stop the output like `Finished in 0.1 seconds`? I mean, completely make cmdstanr silent.

**Comment by mike-lawrence** [comment]
If you're using linux or mac, you can do: 
```R
sink('/dev/null') #turns off all output
out = mod$optimize(...)
sink(NULL) #turns output back on
```

**Comment by jgabry** [comment]
Yeah `sink` should work or another option would be to wrap the call inside of `capture.output`:

```r
output <- capture.output(fit <- mod$optimize(data = stan_data))
```

Now `fit` is the fitted model object as usual and `output` contains the console output in case you want to check it (but it shouldn't actually print anything).

**Comment by beyondpie** [comment]
@mike-lawrence @jgabry 
thanks! nice to know the two ways. I will try them.

**Comment by rok-cesnovar** [comment]
I am guessing this can be closed after #357?

**Comment by beyondpie** [comment]
@rok-cesnovar 
For me, I use `capture.output` is enough. Thanks! BTW, do you have time plan for the v1.0.0 release?

**Comment by rok-cesnovar** [comment]
Thanks! I am going to close this issue then.

We have not set up a time plan yet. There are a few more issues to close before we can start thinking about that.
