### ISSUE TITLE
$generate_quantities() can produce fewer samples than in original fit object

### ISSUE THREAD

**Issue by nerutenbeck** [stan-dev/cmdstanr#342]
The Discourse topic inspiring this feature request is documented here:
https://discourse.mc-stan.org/t/fewer-generated-quantities-than-parameter-samples/19070

__The problem:__
Say I have a model with several hundred parameters, some specifying individual-level effects. I also have a separate `generated quantities` program to produce posterior predictions for each individual (say 500 individuals). I may want or need to run the initial model for a certain number of iterations to achieve convergence (say the default 1000 iterations X 4 chains). The issue is I might not actually need or want 4000 posterior predictions per indvidual - 100 might be plenty, and in fact in larger `n` cases with possibly several generated quantities, the posterior predictive samples become unnecessarily memory intensive.

__A proposed solution:__
The feature request would just be to be able to pass an additional argument `iter_sampling` or some such to the `generate_quantities` method specifying the number of iterations to run in the generated quantities program. Alternately, providing a method to downsample the draws array to a smaller dimension e.g. via `posterior::subset_draws()` and pass it directly to the `generated_quantities` call rather than passing the `fit` object itself.

__Current workarounds:__
Currently to work around this, if I want to limit the number of posterior observations, I need to build generated quantities "by hand" from downsampled posterior distribution in R. This is not so bad, but somewhat annoying since in my current workflow it involves munging big dataframes of parameters via `posterior` and `tidybayes`, or some similar solution involving storing the posterior distribution and generating predictions JIT.

Thanks as always! Love the package.

**Comment by mitzimorris** [comment]
you must use all of the draws in the sample in order to get new quantities of interest that match the posterior distribution - you can't throw away draws because that will change the density.

**Comment by nerutenbeck** [comment]
Yeah this is a very basic misunderstanding on my part. Of course sampling is happening after convergence. Apologies. I think changing `iter_sampling` will do just what I want.
