### ISSUE TITLE
compilation in tempdir and other compilation issues

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#352]
@mitzimorris Can you share the concerns you mentioned to me about how CmdStanR is doing compilation? I want to make sure we're all on the same page about how to do compilation and you know far more about that topic than I do! If we should make changes I'd like to do that now before we go too far with PR #306 and other compilation stuff.

**Comment by rok-cesnovar** [comment]
So the only difference right now (on master) is that we always compile in the temp folder as opposed to only when the path is weird (has spaces, etc). 

I think there are many more Windows users among the R Stan community than there are in the Python Stan community (this is 100% a guess, but that is my gut feeling, just based on how many support questions for Windows there are for cmdstanr as opposed to cmdstanpy).

So I would keep the approach we have, using temp only sometimes only complicates the codebase in my opinion, and keeps us from any additional model path issues. We only had one issue that was related to the temp folder as of now.

**Comment by rok-cesnovar** [comment]
If you agree @jgabry just close the issue.
