### ISSUE TITLE
PATH issue for Github Actions

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#354]
We still use `echo "::add-path::.."` in our CI. This is now officially disabled and we need to replace it: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by jgabry** [comment]
Thanks. I was about to look into why things were failing but this is probably the reason.

**Comment by rok-cesnovar** [comment]
It is yes, but I wont be able to fix this today. Will do tomorrow.
