### ISSUE TITLE
Making it easier to use pedantic mode

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#358]
Should we add an argument to `$check_syntax()` (or even to `$compile()`) for turning on pedantic mode? I know we already can specify it in `stanc_options` but I think most users will stay away from the `stanc_options` argument. But we could add an argument like this 

```r
mod$check_syntax(pedantic=TRUE) # should probably be FALSE by default
```

which would make it much more likely for users to try it out and hopefully that would both benefit users and help get @rybern and others more feedback on the feature. 

Thoughts? 

This is also related to #298 where @mitzimorris rightfully pointed out that the `include_paths` argument is redundant given that it is part of `stanc_options`. I think users will be more likely to take advantage of certain features if we give them ON/OFF switches rather than making them specify compiler flags. But I also understand @mitzimorris's concern about redundancy and not offering too many ways to do the same thing if not necessary.

**Comment by rok-cesnovar** [comment]
>  I think users will be more likely to take advantage of certain features if we give them ON/OFF switches rather than making them specify compiler flags. 

+1

This is a question of maintenance vs user-friendly. I personally don't think these arguments represent a huge maintenance burden and I would agree with Jonah here.

**Comment by jgabry** [comment]
Ok cool glad you agree. I just don't think it's fair to expect users to specify compile flags unless it's for pretty advanced options. Using file includes and pedantic mode are not advanced features (they should be used regularly) so I think it makes sense to add explicit arguments for those. Will open a PR shortly.

**Comment by jgabry** [comment]
Tagging @mitzimorris in case this is something to also implement in CmdStanPy
