### ISSUE TITLE
Add loo method

### ISSUE THREAD

**Issue by avehtari** [stan-dev/cmdstanr#366]
Implement loo so that the following works for cmdstanr fit object similarly as for rstan object
```
loo(fit)
```

https://discourse.mc-stan.org/t/using-loo-with-cmdstanr/17230/2 suggest to use
```
loo(fit$draws("log_lik"))
```
but this misses `r_eff` and should be
```
loo(fit$draws("log_lik"), r_eff=relative_eff(fit$draws("log_lik")))
```
which is much more difficult to remember than `loo(fit)`

Seems like an easy feature to add?

**Comment by jgabry** [comment]
Sounds good to me. It would definitely be nice to be able to do loo(fit).

**Comment by jgabry** [comment]
@avehtari @rok-cesnovar and anyone else, how do you think people should call this method? Which option do you prefer? 
(a) `loo(fit)`, to be consistent in our other packages that don't use R6 classes
(b) `fit$loo()`, to be consistent with CmdStanR's other methods for fitted model objects 
(c) Allow both if possible

**Comment by jgabry** [comment]
I think I prefer (b) and we could always do (c) later if we decide we want to also add the other one. But I'm not attached to that.

**Comment by avehtari** [comment]
(c) or if (b) at least give a helpful message if someone tries (a), but start with something

**Comment by rok-cesnovar** [comment]
Lets start with b). 

If we expose loo(fit) to give a message to try fit$loo() I think we should just make loo(fit) call fit$loo(). It is another API endpoint but if users are so accustomed to loo(fit) then I think we have no option.

**Comment by jgabry** [comment]
I have a preliminary version of (b) now on the `loo-method` branch. Will open a PR and make some comments on a few things that still need to be decided.
