### ISSUE TITLE
Handle TBB lib on Windows

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#37]
Cmdstan 2.21 now includes the Intel TBB library. This changes nothing for non-Windows users in terms of how they build models.

Windows users of cmdstan have the option of adding the path to the build library (<cmdstan-path>/stan/lib/stan_math/lib/tbb) to their user of system PATH variable. If they dont do that, the tbb.dll is copied to the executable folder for each model. 

So techincally they also dont have to do anything, but to avoid copying of dlls or requiring the users to set the path variable cmdstanpy and cmdstanr could provide convenience features that Windows users dont have to add that. 

The easiest solution would be to add the above path to the PATH variable for the session or simply for every run.

I added a windows label, hope that is ok with you @jgabry.

**Comment by jgabry** [comment]
Seems like a good idea to me!

**Comment by jgabry** [comment]
and yeah feel free to create labels and milestones and anything like that. I’m planning on creating milestones for a beta release and an eventual CRAN release, so we can organize issues better for those. I don’t really have target dates for those yet. it would be good to do a beta release soon but a lot of the open issues should probably be addressed before then (unless we want to call it an alpha release maybe)

**Comment by rok-cesnovar** [comment]
Great, thanks! Yeah, at least the rstan dependency would be nice to remove for beta.

**Comment by jgabry** [comment]
Yes! We just need to write something to read the csv output so we can also drop read_stan_csv.
