### ISSUE TITLE
update_cmdstan function

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#38]
From @rok-cesnovar in #35: 

> This also raises the issue of having a upgrade_cmstan that deletes the existing cmdstan and installs the new version?

 Yeah that’s a good idea.

**Comment by rok-cesnovar** [comment]
This should also have an arugment like update_cmdstan(develop=TRUE) that would install the latest develop version of cmdstan.

**Comment by jgabry** [comment]
Yeah good idea

**Comment by jgabry** [comment]
by default I think it should just delete the old one because that’s the best option for most users, but it should probably also at least have an option to not delete the existing installation and I guess in that case we can just rename the existing installation?

**Comment by jgabry** [comment]
An alternative to having a separate `update_cmdstan()` function could be to just implement these features (being able to install from develop, option to remove old installation) as part of the `install_cmdstan()` function. I don't have a strong preference, so either approach (new function or modify existing function) is fine by me.

**Comment by rok-cesnovar** [comment]
You wont believe this but I was also thinking about something likat that.

Something like 

```R
install_cmdstan(remove_old_version=True, develop = False)
```
I am more for this now. Will make a PR over the weekend.
