### ISSUE TITLE
Add a manually triggerable Github Actions job for Cmdstan RC and release testing

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#380]
Add a [manual](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#manual-events) job that someone with write permissions can start.

Argument: tarball URL

Runs all unit tests with the R release version (no need for R-devel/oldrel) on all OS.

Would serve as a test if cmdstanr works with RCs and as a check for Cmdstan release tarballs - https://github.com/stan-dev/cmdstan/issues/810

**Comment by jgabry** [comment]
Good idea
