### ISSUE TITLE
Allow $generate_quantities() to directly use draws_array objects

### ISSUE THREAD

**Issue by wlandau** [stan-dev/cmdstanr#387]
Mentioned by @rok-cesnovar at https://discourse.mc-stan.org/t/should-generate-quantities-accept-cmdstanvb-objects/19628. This would allow us, for example, to use variational Bayes draws to run generated quantities.

**Comment by jgabry** [comment]
I think we would also need to allow `draws_matrix` in addition to `draws_array` in order to support VB (there's no concept of chains in VB so it's just a draws x variables matrix instead of an array), but that will be trivial if we get it working with arrays.

**Comment by jgabry** [comment]
@wlandau This should now be working on the master branch if you want to try it out. You can now use CmdStanMCMC, CmdStanVB, draws_array (from MCMC), or draws_matrix (from VB) as the `fitted_params` argument.

**Comment by wlandau** [comment]
Awesome, thanks! All 4 kinds of input worked when I tried them.

**Comment by jgabry** [comment]
Ok great, thanks for trying them out.
