### ISSUE TITLE
Allow specification of cmdstan diagonostic_file and parse the outputs

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#39]
This file has the unconstrained parameters, momentums, and gradients

**Comment by jgabry** [comment]
There's now a `diagnostic_file` argument (path to .csv like CmdStan), but haven't yet implemented reading it back in

**Comment by jgabry** [comment]
@bbbales2 What would you like to see in terms of parsing the output? There’s a bunch of stuff included so I could imagine either returning the same matrix that cmdstan spits out or providing separate access to the different stuff included.

**Comment by bbbales2** [comment]
I guess fit$draws(unconstrained = TRUE) is what I'd like.

Or maybe a sample(keep_diagnostics = TRUE)

I can get that with:

```
read_csv("diagnostic_file.csv", comment = "#") %>%
  select(-lp__, -accept_stat__, -stepsize__, -treedepth__, -n_leapfrog__, -divergent__, -energy__) %>%
  select(-starts_with("p_"), -starts_with("g_"))
```

I guess really I'd like all the ```-lp__, -accept_stat__, -stepsize__, -treedepth__, -n_leapfrog__, -divergent__, -energy__``` to go into a matrix/dataframe/tibble somewhere where I could access them for diagnostics.

The momentum and gradient information I don't personally have a use for, but I guess the goal is to wrap cmdstan not give me something I find useful. So maybe they could appear as momentum_draws() or gradient_draws()? It'd probably be better to select those out with column indexes rather than starts_with things to avoid naming confusion.

Also the way diagnostic_file is implemented now won't work in general. It needs to be handled like the output files I think. Every chain tries to write diagnostic_file and only one remains after all the chains finish.

**Comment by bbbales2** [comment]
Yeah maybe fit$unconstrained_draws() is better than fit$draws(unconstrained = TRUE)?

Presumably if sampling is done without the extra diagnostics then fit$unconstrained_draws()/fit$momentum_draws()/fit$gradient_draws() could throw an error and print a message to say re-run? 

And all of this stuff ```-lp__, -accept_stat__, -stepsize__, -treedepth__, -n_leapfrog__, -divergent__, -energy__``` is available through the original output, right?

Frankly I'm happy if this comes in as fit$diagnostic_files() or something. I can pull these files in a parse them myself. I've got a fringe use case and I don't think this is high priority for other folks.

**Comment by jgabry** [comment]
Thanks for the feedback!

Ok, for now I think what I'll do is make `diagnostic_file` a `TRUE/FALSE` argument (instead of a file path) and then have `fit$diagnostic_files()` give you the paths and `fit$save_diagnostic_files()` allow you to move them from temporary files to wherever you want. That's consistent with `fit$save_output_files()`. Once we have that then we can think about adding an `unconstrained_draws()` method like you suggested.

**Comment by bbbales2** [comment]
I'm happy to leave it at that. Who knows how long this option lives on in Cmdstan anyway.

**Comment by jgabry** [comment]
@bbbales2 No rush, but whenever you have a chance can you try out the branch called `save-diagnostics` that I just pushed and let me know what you think?  It actually replaces the `diagnostic_file` argument with a T/F argument `save_diagnostics` (figured that makes more sense as an argument name). If TRUE it will automatically create the diagnostic files in the temp directory. The fit object now has methods `$diagnostic_files()` and `$save_diagnostic_files()` for getting the tempfile paths and saving the files, respectively.
