### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#391]
I think it would make sense to have something like a verbose mode that could be used for troubleshooting, debugging, and developing with cmdstanr. I think an option would be just fine. This is not something a regular user would need.
Like 
```R
options("cmdstanr_verbose"= TRUE)
```
would print all commands and all output from processx. This came up when debugging a problem with @yizhang-yiz [here](https://github.com/stan-dev/cmdstanr/pull/350#issuecomment-740786862)

**Comment by jgabry** [comment]
That seems like a good idea
