### ISSUE TITLE
sample should explicitly print warning messages when models have divergences or hit max_treedepth

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#41]
Right now it doesn't.

**Comment by jgabry** [comment]
What do you think about it automatically running CmdStan's `bin/diagnose` after sampling?

**Comment by rok-cesnovar** [comment]
I would go with the 

> implement something on the R side to check these and throw warnings

I can tackle this one @jgabry. I will have some time today and Friday to tackle some of these issues.

The plan on the Cmdstan is to refactor the Cmdstan I/O that would make this easier to capture for the cmdstanLang interfaces. Hopefully that happens for the next release. I will certainly be pushing for that.

**Comment by rok-cesnovar** [comment]
This issue,  #18 and #3 all need some kind of processing of the standard output and standard error  from the various commands. @jgabry would you mind if I take on that larger task and squash these 3 issues?

With that and replacing the rstan csv read we are then probably ready for at least the alpha release? I think.

**Comment by bbbales2** [comment]
> What do you think about it automatically running CmdStan's bin/diagnose after sampling?

I think all the output needs to be pulled into R in some form or fashion. Having the ability to plot divergences is pretty important I think. As a quick fix it'd be okay to just run bin/diagnose.

**Comment by rok-cesnovar** [comment]
@bbbales2 do you maybe know of any simple-ish example models that have divergences or hit max_treedepth that I can use to test?

**Comment by bbbales2** [comment]
Eight schools!

```
data {
  int<lower=0> J;
  real y[J];
  real<lower=0> sigma[J];
}

parameters {
  real mu;
  real<lower=0> tau;
  real theta_tilde[J];
}

transformed parameters {
  real theta[J];
  for (j in 1:J)
    theta[j] = mu + tau * theta_tilde[j];
}

model {
  mu ~ normal(0, 5);
  tau ~ cauchy(0, 5);
  theta_tilde ~ normal(0, 1);
  y ~ normal(theta, sigma);
}
```

Use this data for divergences:
```
J <- 8
y <- c(28,  8, -3,  7, -1,  1, 18, 12)
sigma <- c(15, 10, 16, 11,  9, 11, 10, 18)
```

Use this data for treedepth errors:
```
J <- 8
y <- c(28,  8, -3,  7, -1,  1, 18, 12)
sigma <- c(0.15, 0.10, 0.16, 0.11,  0.09, 0.11, 0.10, 0.18)
```

Or you can also set max_treedepth to like 4 or something super low and you'll hit max treedepth.

**Comment by rok-cesnovar** [comment]
Ah 8 schools off course. Fantastic.

**Comment by jgabry** [comment]
> Or you can also set max_treedepth to like 4 or something super low and you'll hit max treedepth.

Just one comment on this: Currently CmdStan itself uses `max_depth` instead of `max_treedepth` as the argument name. So I went with `max_depth` in CmdStanR too for consistency even though I actually prefer `max_treedepth`. I'm open to changing it (although preferably it would be changed in CmdStan too).

**Comment by jgabry** [comment]
> This issue, #18 and #3 all need some kind of processing of the standard output and standard error from the various commands. @jgabry would you mind if I take on that larger task and squash these 3 issues?

@rok-cesnovar That would be great! I've had a few more thoughts on those other issues you referenced but I'll comment over on those issues.

**Comment by bbbales2** [comment]
> Ah 8 schools off course. Fantastic.

Oops. I was closing open tabs on my computer and realized I gave you the non-centered 8-schools. That model won't have divergences. Non-centered will give you treedepth errors if you make the sigma really small.

Use the centered parameterization to get the divergences. My bad:

```
data {
  int<lower=0> J;
  real y[J];
  real<lower=0> sigma[J];
}

parameters {
  real mu;
  real<lower=0> tau;
  real theta[J];
}

model {
  mu ~ normal(0, 5);
  tau ~ cauchy(0, 5);
  theta_tilde ~ normal(mu, tau);
  y ~ normal(theta, sigma);
}
```
