### ISSUE TITLE
Create CmdStanMCMC R6 object from CSV

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/cmdstanr#411]
**Is your feature request related to a problem? Please describe.**
Currently no sane way to create `CmdStanMCMC` object as returned by `$sample` command by reading from CSV. 

**Describe the solution you'd like**
Something like
```r
fit <- to.cmdstan.mcmc(read_cmdstan_csv(c(file1, file2, file3, file4)))
```
so that later `fit` can be used for various actions such as
```r
draws <- fit$draws()
```

**Describe alternatives you've considered**
None so far.

**Additional context**
One motivation is to help user share/debug outputs, as indicated [here](https://discourse.mc-stan.org/t/draws-method-in-cmdstanr-is-still-slow/19490/5?u=yizhang). Another one is to port past cmdstan output to be postprocessed.

**Comment by jgabry** [comment]
I thought at first that we would need to create the CmdStanRun object that CmdStanMCMC takes as input, but that would be a huge hassle. However, I think I figured out a much easier way to do this and I'll have something to share soon.

**Comment by jgabry** [comment]
@yizhang-yiz With the branch in the linked PR this should now be possible: 

```r
csv_contents <- read_cmdstan_csv(files)
fit <- as_cmdstan_mcmc(csv_contents)
```

**Comment by yizhang-yiz** [comment]
@jgabry Thanks a lot. Will test it asap.

**Comment by rok-cesnovar** [comment]
Nice. What if the API would be `read_cmdstan_csv(files, as_cmdstan_fit = TRUE)` or something the like? That way you can also access file paths.

**Comment by jgabry** [comment]
I like having access to the file paths but I don't love the idea of the same function returning drastically different output (list vs CmdStanMCMC object) depending on an argument (I'm not totally opposed but would be nice to avoid). What about if `as_cmdstan_mcmc()` just takes the files as input and calls `read_cmdstan_csv()` internally? That would give us the same thing but without the same function returning different types: 

```r
# same as we already have, returns list
read_cmdstan_csv(files, variables = NULL, sampler_diagnostics = NULL)

# calls read_cmdstan_csv internally returns CmdStanMCMC
as_cmdstan_mcmc(files)
```

**Comment by yizhang-yiz** [comment]
BTW what's the intended use of the list returned by `read_cmdstan_csv`?

**Comment by jgabry** [comment]
Mainly it's just for internal use (we use it to create the fitted model objects). We exposed it to give people direct access to the csv contents if they prefer that. I think it can also be used to inspect the output from failed chains.

**Comment by jgabry** [comment]
It also gives people using CmdStan directly (not via CmdStanR) a way to read their output into R. It's more efficient than `rstan::read_stan_csv()`, which used to serve that purpose (I guess it still does because we haven't removed it from rstan).

**Comment by jgabry** [comment]
I just switched what's on the branch to use the idea from above https://github.com/stan-dev/cmdstanr/issues/411#issuecomment-748332237

**Comment by rok-cesnovar** [comment]
I agree with the separate function.
