### ISSUE TITLE
don't use symlinks on windows? 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#42]
Currently `install_cmdstan` installs the latest CmdStan and creates a symlink for it so it can just be referred to by `cmdstan` instead of the including the particular version number. This is convenient, but I've heard symlinks could be problematic on Windows. @rok-cesnovar do you know anything about this?

**Comment by rok-cesnovar** [comment]
Havent tried installing cmdstan via install_cmdstan() on Windows yet, but in general these simple symlinks should work. 

The symlinks that dont usually work is when you are tryign to dynamically link a .dll file via symlink. Will investigate. Assigning myself.

**Comment by jgabry** [comment]
Thanks!

**Comment by rok-cesnovar** [comment]
ln -s ${CS} essentially does a copy on Windows which I guess is fine. I will open a PR to cleanup some of the minor Windows issues. I am also wondering why is there a need for the symlink at all.

**Comment by jgabry** [comment]
Thanks, and yeah i think you’re probably right to question using symlinks at all. if you want and have time feel free to remove the symlink usage in the package entirely.

**Comment by rok-cesnovar** [comment]
We can close this one as we no longer use symlinks.
