### ISSUE TITLE
Suppress the remaining messages in cmdstan_model() if quiet is TRUE?

### ISSUE THREAD

**Issue by wlandau** [stan-dev/cmdstanr#429]
I think it would be convenient if "Compiling Stan program..." and "Model executable is up to date!" were suppressed when `quiet` is `TRUE`.

``` r
library(cmdstanr)
#> This is cmdstanr version 0.2.2
#> - Online documentation and vignettes at mc-stan.org/cmdstanr
#> - CmdStan path set to: /Users/<CENSORED>/.cmdstanr/cmdstan-2.25.0
#> - Use set_cmdstan_path() to change the path
stan_program <- "
data {
  int<lower=0> N;
  int<lower=0,upper=1> y[N];
}
parameters {
  real<lower=0,upper=1> theta;
}
model {
  y ~ bernoulli(theta);
}
"
file <- write_stan_file(stan_program)

model <- cmdstan_model(file, quiet = TRUE)
#> Compiling Stan program...

model <- cmdstan_model(file, quiet = TRUE)
#> Model executable is up to date!
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rok-cesnovar** [comment]
Thanks!

I think we want to have 3 levels of output: 

- no output (what you propose)
- print informational messages (what we currently print with quiet = TRUE)
- print all compile messages (what we currently print with quiet = FALSE)

I am not sure what would be the best way of adding the "no output" option. A new argument or some third value to quiet, like quiet = "really quiet" :)

**Comment by wlandau** [comment]
After more thought...what about a custom path to a log file? `log = R.utils::nullfile()` could be equivalent to totally quiet, and a text log would be super convenient for models that take days to run. I currently do this in `stantargets`: https://wlandau.github.io/stantargets/reference/tar_stan_mcmc.html#arguments.

**Comment by wlandau** [comment]
I know `R CMD BATCH` has a log of its own, but sometimes stdout does not come through, e.g. in HPC settings where it can be difficult or annoying to relay the output.

**Comment by mike-lawrence** [comment]
@wlandau See [this feature discussion](https://github.com/stan-dev/cmdstanr/issues/424), the proposed implementation of which would involve stdout/stderr files, which should address the persistent verbosity of cmdstan.

**Comment by dpsimpson** [comment]
A different solution that might be useful regardless of the new features would be to only print out those messages when `interactive() == TRUE`. This would fix the problem for RMarkdown docs.

**Comment by rok-cesnovar** [comment]
Oh, good point.

Will make a PR for that prior to what we agree on for the features. Rmd displaying messages from cmdstanr has annoyed me to no end. Didnt think of interactive...

**Comment by wlandau** [comment]
Noticed it has been a while. I can write the PR if you would like. May I?

**Comment by rok-cesnovar** [comment]
Of course! Sorry, it was a bit busy the last month. Thank you!

**Comment by wlandau** [comment]
Thanks!

I forgot I need to go through a couple pre-approvals at my work before I start submitting PRs to `cmdstanr`. Hopefully that will go through this week.
