### ISSUE TITLE
add file naming arguments to sample()

### ISSUE THREAD

**Issue by wpetry** [stan-dev/cmdstanr#438]
`save_output_files()` has several useful file naming arguments that are great for helping the user craft meaningful file names. However, only one of these arguments (`output_dir`) can be specified when saving sampling output directly from `sample()`. The remaining arguments use the function defaults.

I'd like to see arguments added to `sample()` that allowing the user to specify the `basename`, `timestamp`, and `random` arguments. I think this would make the output CSVs much more human-readable. To me, the current solution to use `output_dir` if you want the default naming, but needing a separate function call to change one argument seems inconsistent.

I think it would be most intuitive to pass `sample()` a list of arguments that are used to save the output CSVs. However, the current convention seems to avoid this type of grouping (compare with `rstan::sampling()`'s `control`). Directly adding the arguments may be the least intrusive solution.

Kudos for developing such a great package for interfacing Stan!

**Comment by seth127** [comment]
I'm considering using `cmdstanr` under-the-hood in [the `bbr` package](https://github.com/metrumresearchgroup/bbr) I'm working on. This feature would be nice to have.

**Comment by rok-cesnovar** [comment]
@jgabry what do you think? I think the use-case is real and we should think about supporting it.

I think the easiest way of supporting this is allowing the user to supply `output_files = c("file1.csv", "file2.csv", "file3.csv")` which has to have unique values and match the number of chains?

Does that work for you @wpetry @seth127 ?

**Comment by wpetry** [comment]
@rok-cesnovar I think that would work well for my use case. It ought to be easy enough to generate the necessary filenames.

**Comment by rok-cesnovar** [comment]
You can just copy what we do in generate_file_names https://github.com/stan-dev/cmdstanr/blob/master/R/utils.R#L170

**Comment by seth127** [comment]
I like the idea of exposing those arguments to generate_file_names(), as opposed to asking the user to pass in a vector of custom names. Or even if it's just one of those args like id or basename (whichever feels most appropriate). 

I didn't look at that code too closely but I envision passing something like "my_dir/my_run_id" and having it save files as "my_dir/my_run_id_1.csv", "my_dir/my_run_id_2.csv", ... or whatever, for all of the chains.

**Comment by rok-cesnovar** [comment]
Thanks. 

Exposing `output_basename` in addition to `output_dir` would work for me if would for everyone else.

**Comment by jgabry** [comment]
> Exposing `output_basename` in addition to `output_dir` would work for me if would for everyone else.

Sorry I missed this issue earlier, but this option is fine by me too!
