### ISSUE TITLE
knitr called in .onLoad() but is not listed in Imports, causes installation error if not installed prior to installing cmdstanr

### ISSUE THREAD

**Issue by tcuongd** [stan-dev/cmdstanr#440]
**Describe the bug**

Hello! When installing from source, there is a step that checks whether the package can be loaded from a temporary location. I believe `cmdstanr` does the following calls in `.onLoad()` (https://github.com/stan-dev/cmdstanr/blob/ff832c844389a25427d3642c873af2cee3719811/R/zzz.R#L75):

```
.onLoad <- function(...) {
  cmdstanr_knitr_env(knitr::knit_global())
  cmdstanr_initialize()
}
```

Since `knitr` is only in Suggests and not Imports, an error will occur if the user doesn't have `knitr` installed before installing `cmdstanr`:

```
** testing if installed package can be loaded from temporary location Error: package or namespace load failed for ‘cmdstanr’:  .onLoad failed in loadNamespace() for 'cmdstanr', details:   call: loadNamespace(name)   error: there is no package called ‘knitr’ Error: loading failed Execution halted
```

I'm guessing this error would also occur if we install from binary and call `library(cmdstanr)`? 

**To Reproduce**

1. Ensure `knitr` is not installed.
2. Install `cmdstanr` from source.

**Expected behavior**

I'm not sure what the purpose of `cmdstanr_knitr_env(knitr::knit_global())` is, but my first thought would be to remove it from `.onLoad()` if `knitr` is really only a suggested package. Or, we could check the namespace for `knitr` before trying to run ` cmdstanr_knitr_env(knitr::knit_global())`.

Otherwise, we should move `knitr` to Imports.

**Operating system**
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin19.6.0 (64-bit)
Running under: macOS Catalina 10.15.7
```

**CmdStanR version number**

After installing `knitr` and having a successful install:

```
> packageVersion("cmdstanr")
[1] ‘0.3.0.9000’
```

**Comment by rok-cesnovar** [comment]
> Or, we could check the namespace for knitr before trying to run cmdstanr_knitr_env(knitr::knit_global()).

I think this is the way to go, but will defer this one to @jgabry.

**Comment by tcuongd** [comment]
> > Or, we could check the namespace for knitr before trying to run cmdstanr_knitr_env(knitr::knit_global()).
> 
> I think this is the way to go, but will defer this one to @jgabry.

Ah yeah I think that makes sense, that's how it is for the other places which call `knitr` anyways. I've raised a quick fix ^.
