### ISSUE TITLE
False "The CmdStan toolchain is setup properly!" message

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#444]
I cleaned out my ~/.cmdstanr and went to reinstall it and I got this message:

```
> install_cmdstan()
The CmdStan toolchain is setup properly!
* Latest CmdStan release is v2.26.0
* Installing CmdStan v2.26.0 in /home/bbales2/.cmdstanr/cmdstan-2.26.0
* Downloading cmdstan-2.26.0.tar.gz from GitHub...
```

I'm pretty sure it isn't setup properly if then it goes to install and download. Something must be weird with that print logic.

**Comment by rok-cesnovar** [comment]
This means that the toolchain for CmdStan is setup properly, as in g++/clang++ and make/mingw32-make and anything else we need. Maybe we need to reword the text?

**Comment by bbbales2** [comment]
Oooh, I guess just say C++ toolchain.
