### ISSUE TITLE
Should cmdstan_model default to automatically compiling? 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#45]
There doesn't really seem to be a use case for a CmdStanModel object before compilation, so maybe it should just happen by default? E.g. `cmdstan_model()` could have a `compile` argument defaulting to `TRUE`.  

We can decide this in conjunction with @mitzimorris and other CmdStanPy devs. Corresponding isssue is https://github.com/stan-dev/cmdstanpy/issues/153

**Comment by jgabry** [comment]
And thanks @bbbales2 for suggesting this the other day

**Comment by jgabry** [comment]
I was already playing around with this earlier so I can make a PR for this soon.

**Comment by mitzimorris** [comment]
does this work for models which require include paths?

**Comment by jgabry** [comment]
@mitzimorris I hadn't thought of that. Will check, thanks! Do you have a simple example? If not I'll put one together when I have a chance and test it.

**Comment by mitzimorris** [comment]
yes, there's an example in the cmdstanpy test data directory:

https://github.com/stan-dev/cmdstanpy/blob/master/test/data/bernoulli_include.stan
https://github.com/stan-dev/cmdstanpy/blob/master/test/data/divide_real_by_two.stan

**Comment by jgabry** [comment]
Thanks! will try it out.

**Comment by jgabry** [comment]
Bummer it errors. But I think at least for CmdStanR this is a problem in general and not just because of compiling automatically now. It will error even if it's manually compiled. I'll open a new issue for this.

**Comment by jgabry** [comment]
#59
