### ISSUE TITLE
initial values ignored

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/cmdstanr#451]
**Describe the bug**
Can't set initial values

**To Reproduce**
Run [bug.tar.gz](https://github.com/stan-dev/cmdstanr/files/5989070/bug.tar.gz)

**Expected behavior**
`rawTwin[1]` etc should be set to 0.5

**Operating system**
Linux Ubuntu 20.10

**CmdStanR version number**
0.1.3, using cmdstan-2.26.0

**Additional context**
Maybe a cmdstan bug?

**Comment by jpritikin** [comment]
Oops, you can comment `tall[['ord']] <- ordinalize(tall[['value']], 12)` and `source("util.R")` to get the script to run.

**Comment by mike-lawrence** [comment]
Check that you're structuring the inits properly. [See this issue](https://github.com/stan-dev/cmdstan/issues/966) that boiled down to failure to do so.

**Comment by jpritikin** [comment]
Here's what I found in the init file:

````
{
  "predVar": 1,
  "eVar": 2,
  "rawFamily[1]": 0.5,
  "rawFamily[2]": 0.5,
  "rawFamily[3]": 0.5,
  "rawFamily[4]": 0.5,
  "rawFamily[5]": 0.5,
  "rawFamily[6]": 0.5,
  "rawFamily[7]": 0.5,
  "rawFamily[8]": 0.5,
  "rawTwin[1]": 0.5,
  "rawTwin[2]": 0.5,
  "rawTwin[3]": 0.5,
  "rawTwin[4]": 0.5,
  "rawTwin[5]": 0.5,
  "rawTwin[6]": 0.5,
  "rawTwin[7]": 0.5,
  "rawTwin[8]": 0.5
}
````

> Check that you're structuring the inits properly

What can I do? It's cmdstanr that structures the output.

**Comment by jpritikin** [comment]
Oh, so I needed to do:

````
    initVal <- list(predVar=1, eVar=2)
    initVal[['rawFamily']] <- rep(.5, dl$numFamily)
    initVal[['rawTwin']] <- rep(.5, dl$numTwin)
````

Why doesn't cmdstanr prohibit square brackets in variable names?

**Comment by mike-lawrence** [comment]
> Why doesn't cmdstanr prohibit square brackets in variable names?

Yup, that's what *should* happen. If you scroll to the bottom of the issue I linked, that's the solution that has been seemingly agreed-to as the solution to this.

**Comment by rok-cesnovar** [comment]
In all honest I forgot about that. Lets keep this issue here so we dont forget.
