### ISSUE TITLE
print reminder to update make/local after install_cmdstan()

### ISSUE THREAD

**Issue by jsocolar** [stan-dev/cmdstanr#455]
I just updated to cmdstan 2.26.1 and very nearly forgot to update make/local. It would be great if users could get reminded about this.  I think the ideal behavior for `install_cmdstan` might be to look for the most recent version of cmdstan (if it exists) in the same directory where the new cmdstan was installed. If there is a previous installation of cmdstan in the same directory, and if make/local exists and contains any non-whitespace characters, print to the console something like:

```
Your previous cmdstan installation ([most recent version number]) may contain persistent compiler flags at [filepath to old make/local]. To continue using these, add them at [filepath to new make/local]. Contents of make/local from version [most recent version number]:
[print(readLines(filepath to old make/local))]
See ?cmdstan_make_local for further information.
```

Users who aren't using make/local don't see any message. Users who do use make/local see a message with instructions for what to do, but still (desirably IMO) have to engage a little bit with what their compiler flags are (rather than just automatically porting across the old make/local, which I think would be potentially undesirable).

**Comment by rok-cesnovar** [comment]
Great idea!
