### ISSUE TITLE
When there is a folder with the cmdstan model name cmdstanr produces strange errors

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#456]
This is from @merlinheidemanns

Make a model called 'test4.stan' in your working directory.

Something like this is fine:
```stan
parameters {
  real x;
}

model {
  x ~ normal(0, 1);
}
```

Now create a directory 'test4'. `cmdstan_model` will think the model is built and up to date and produce an error when running.

```
> dir.create('test4')
> mod = cmdstan_model('test4.stan')
Model executable is up to date!
> mod$sample()
Running MCMC with 4 sequential chains...

 Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  cannot start processx process './test4' (system error 13, Permission denied) @unix/processx.c:592 (processx_exec)
Type .Last.error.trace to see where the error occured 
```

If you update the model, it builds and then gets put in that folder:

```
> mod = cmdstan_model('test4.stan')
Compiling Stan program...
 
> mod$sample()
Running MCMC with 4 sequential chains...

 Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  cannot start processx process './test4' (system error 13, Permission denied) @unix/processx.c:592 (processx_exec)
Type .Last.error.trace to see where the error occured 
> list.files("test4/")
[1] "model-13792589c4fe"
```

**Comment by rok-cesnovar** [comment]
Nice find. And once for a change this is unlikely to cause problem for windows. I think the best fix here is to check if a file is a directory and if so just stop and throw an error to the user to rename either the stan model name or the folder.

**Comment by bbbales2** [comment]
> I think the best fix here is to check if a file is a directory

That makes sense to me.
