### ISSUE TITLE
cmdstan_diagnose: Return diagnostics as numerics

### ISSUE THREAD

**Issue by nicokist** [stan-dev/cmdstanr#459]
**Is your feature request related to a problem? Please describe.**
I don't think cmdstanr currently allows you to easily pull out the number of divergent transitions except using cmdstan_diagnose, which returns a string that would then need to be parsed.

**Describe the solution you'd like**
Would there be any objection if I modified cmdstan_diagnose to include in its output list the number of divergent transitions? Other diagnostics such as exceeding max_treedepth and E-BFMI could receive similar treatment. This would allow logic to easily interact with the diagnostics, perhaps as follows:

```r
diag <- model$stanfit_diagnose()
if(diag$num_divergent_transitions>0) print(diag$stdout)
```

**Describe alternatives you've considered**
Using regex to parse the cmdstan_diagnose stdout or reimplementing part of cmdstan_diagnose in my own code, but these seem like messy solutions.

**Comment by rok-cesnovar** [comment]
Hey @nicokist ,

thanks for the issue. `cmdstan_diagnose()` is meant to call the bin/diagnose of CmdStan and output what that executable prints. We do cmdstan_summary and summary() the same way. cmdstan_summary runs bin/stansummary while $summary() returns actual numerical values. 

What we have been discussing is adding `fit$diagnose()` that would be what summary is to cmdstan_summary(). This was partly discussed here: https://github.com/stan-dev/cmdstanr/issues/205

The easiest way to get the number of divergent transitions is: 

```
> fit <- cmdstanr_example("schools")
> apply(posterior::subset_draws(fit$sampler_diagnostics(), variable = "divergent__"), 2, sum)
 1  2  3  4 
 1 18 99 18 
```

This outputs the number of divergent transitions for each chain.

**Comment by nicokist** [comment]
Thanks @rok-cesnovar, that will tide me over until #205 and https://github.com/stan-dev/posterior/issues/77 are resolved.

**Comment by jgabry** [comment]
@nicokist Just following up on this to say that there's currently a draft pull request #585 to address #205 and provide an easy way to access the diagnostic values.
