### ISSUE TITLE
CmdStanR report adaptation - step_size as well as inv_metric?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#465]
does CmdStanR report step_size from adaptation output?
cf - https://cmdstanpy.readthedocs.io/en/v0.9.68/api.html#cmdstanpy.CmdStanMCMC.step_size

**Comment by rok-cesnovar** [comment]
Yes, right now its part of the metadata:

```r
fit <- cmdstanr::cmdstanr_example()
fit$metadata()$step_size_adaptation
```

**Comment by rok-cesnovar** [comment]
Is there anything to do in cmdstanr or can we close this?

**Comment by jgabry** [comment]
> Is there anything to do in cmdstanr or can we close this?

Closing since there doesn't seem to be any action we need to take. We can reopen if necessary (e.g., if it's decided that metadata() isn't the right place for this)
