### ISSUE TITLE
Next minor release of cmdstanr (0.4.0)

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#466]
**Describe the issue**

I think the next minor release for cmdstanr is long overdue. I would like to address a few things before we do it, but am opening an issue to remind us to do it.

Issues that need closing prior to release: 

- https://github.com/stan-dev/cmdstanr/issues/445 ( I have a fix for this ready, just need to cleanup)
- https://github.com/stan-dev/cmdstanr/issues/389 (PR https://github.com/stan-dev/cmdstanr/pull/439)
- https://github.com/stan-dev/cmdstanr/issues/438

@jgabry I know you are pretty busy with other stuff a the moment but if you have a chance could you write down the tasks we need to do for the release (like webpage update etc.). You typically handled this stuff.

**Comment by bbbales2** [comment]
If #439 is ready for review I can probably do that later today.

**Comment by rok-cesnovar** [comment]
Yeah, I think it should be ready. Just merge master in. Also has comments for open questions.

**Comment by jgabry** [comment]
You're right that it's overdue! Probably mostly my fault for being caught up in other stuff for a while now. 

>  if you have a chance could you write down the tasks we need to do for the release (like webpage update etc.). You typically handled this stuff.

I'm starting to have a bit more time so I'm happy to do those for this release too. But in general the list is just something like this: 

- Update DESCRIPTION file with new version number and date. 
- Make sure doc (Rd files) have been regenerated (i.e., run `devtools::document()`)
- Regenerate the website 
- Tag release on github
- Upload to stan-dev/r-packages

Hopefully I'm not forgetting something ;)

**Comment by rok-cesnovar** [comment]
Now that #445 was addressed we just need to approve/merge #439

**Comment by jgabry** [comment]
For #439 the code looks good I just still need to go through the vignette. Will try to get to that soon. Hopefully later today or tomorrow.

**Comment by rok-cesnovar** [comment]
No rush no rush. Take your time. Thanks! Was just stating so we know what is left to do.

**Comment by jgabry** [comment]
I can start preparing the release now that #439 is merged

**Comment by rok-cesnovar** [comment]
Cool, let me know if I can help in any way.

**Comment by jgabry** [comment]
All set, going to tag the release shortly

**Comment by jgabry** [comment]
Actually I didn't regenerate the opencl vignette (because the speedup is much more impressive on your system). That means that it lists the version number (at the top of the page) as 0.3.0.9000 still just for that vignette. Can you pull from master and then run this

```r
withr::with_envvar(c("NOT_CRAN" = "true"), {
  pkgdown::build_article("opencl")
})
```
and push to master? Not super urgent (can even be done after I tag the release), that will just get the right version number on the opencl vignette webpage.

**Comment by rok-cesnovar** [comment]
Will do that right now.

**Comment by jgabry** [comment]
Thanks!

**Comment by rok-cesnovar** [comment]
Done.

**Comment by jgabry** [comment]
ok great, thanks. will tag the release now

**Comment by jgabry** [comment]
All set, version 0.4.0 is released! Will close this issue.
