### ISSUE TITLE
Function to check if CmdStan is installed

### ISSUE THREAD

**Issue by wlandau** [stan-dev/cmdstanr#467]
I am developing a [package on top of `cmdstanr`](https://github.com/wlandau/stantargets),  and I would like the ability to skip tests if CmdStan is not installed. My current workaround is a [`tryCatch()` wrapper around `cmdstan_version()`](https://github.com/wlandau/stantargets/blob/main/tests/testthat/helper-skip.R).

**Comment by rok-cesnovar** [comment]
Thanks for the feature request.

Would `cmdstan_version(error_on_NA = FALSE)` which would just return NULL if no cmdstan found work for you?
error_on_NA would be TRUE by default.

I agree it makes sense.

**Comment by wlandau** [comment]
Yes, that would be perfect! Should I submit a PR?

**Comment by rok-cesnovar** [comment]
That would be fantastic!
