### ISSUE TITLE
Not sure if overwriting make/local is the correct behavior

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#47]
My custom make/local settings keep getting overwritten by cmdstanr when I go to compile. I"m not sure that's good behavior.

**Comment by rok-cesnovar** [comment]
You can set any cmdstan flag you want through cmdstanr with

mod$compile(compiler_flags = c("CXXFLAGS += -DTEST1", "CXXFLAGS += -DTEST2"))

This way we can keep track of any changes that occured to the compiler flags so we 
can recompile main.o and model.o if for instance someone turns on STAN_THREADS.

But yeah, we could change this so that the "generated" parts of make/local are separated and we can leave any custom flags.

PS: with cmdstanr you can get around your Cmdstan not-recompiling for changes in stan issue. Just put another compile flag that changes with timestamp or something.

**Comment by rok-cesnovar** [comment]
The plus side of allowing the user to add custom stuff to make/local directly in cmdstan is off course allowing the user the freedom to do so. Its also much easier to migrate from cmdstan to cmdstanr/cmdstanpy if you dont have to copy the flags. 

You also dont need to specify the flags for each model. But I am not sure if that is really a huge plus? I probably lost a few hours from forgetting I have something turned off in make/local from something I did the week before.

The down side of it is that if a user does changes make/local and fails to remove main.o this could cause a bunch of compile time errors that could be easily avoided if the user changed those flags through cmdstanr. This wont be an issue once cmdstan handles make/local as a dependency of main.o (see https://github.com/stan-dev/cmdstan/issues/757).

A compromise would be to have a section in make/local that would be appended from cmdstanr and we only check that for changes. For other changes the user is on its own until cmdstan fixes issue 757. The user also needs to be aware of any potential conflicts from flags set directly and through cmdstanr.

**Comment by bbbales2** [comment]
I don't like this cause I expect cmdstanr is invisibly wrap cmdstan. In this way cmdstanr can change the behavior of my cmdstan silently (also deleting my makefiles lol). I like having complete control over the cmdstan from the command line so I can do weird tests.

> This way we can keep track of any changes that occured to the compiler flags so we
can recompile main.o and model.o if for instance someone turns on STAN_THREADS.

Aah, I see where you're coming from on this. Doesn't make absorb these sorts of flags from the user environment? If cmdstanr wanted to enforce things, could it set environment environmental variables in whatever context it's calling? That seems more polite.

Also setting make/local as a dependency probably won't work as expected unless you're painfully careful with how you update the file. Make works on timestamps, so if cmdstanr is rewriting the file, even it's exactly the same, make will rebuild everything. If cmdstanr is going to wrap compiled behavior like this, it'll probably need a way to check the build flags of a binary or whatever. Dunno how to do this, but I don't think it works cleanly otherwise (I could be wrong). This could certainly be done by adding a flag to cmdstan.

**Comment by rok-cesnovar** [comment]
> (also deleting my makefiles lol)

Sorry about that. Hope I didnt cause too much trouble :(

> Make works on timestamps, so if cmdstanr is rewriting the file, even it's exactly the same, make will rebuild everything.

Once cmdstan adds that, cmdstanr wont rewrite. It didnt rewrite now everytime if you set all flags through cmdstanr.

Anyhow, I have a fix incoming in 2 minutes that will do the following. The make/local with manually set flags and cmdstanr flags will look like this:

```
CXXFLAGS += -DDIRECT_FLAG
CXXFLAGS += -DDIRECT_FLAG2
# cmdstanr generated make/local flags (add user flags above this line)
CXXFLAGS += -DCMDSTANR_TEST1
CXXFLAGS += -DCMDSTANR_TEST234
```
So whatever you have set manually will still be above that comment. No more rewriting those. If you set any flags from cmdstanr those get appended. If you use no flags in cmdstanr there will be zero changes to make/local. That sounds better?

**Comment by bbbales2** [comment]
Looks good!

> Sorry about that. Hope I didnt cause too much trouble :(

Nah nah it's all good was just some debugging stuff

**Comment by jgabry** [comment]
Thanks to both of you! That seems like a good solution. Will review the PR shortly
