### ISSUE TITLE
On `<-` in the code-style

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstanr#478]
Yeah, I'm going to be "that guy" and bring up a style challenge, sorry (kinda). 

What's the motivation behind the current style rule whereby `<-` must be used for assignment? 

I've used R for about 17 years now and I've never experienced any negative consequences to always using `=`. I was trying to search through my recent PR to replace my habitual `=`s with `<-` to conform, and it occurred to me that `<-` is particularly ambiguous in the context of R6, where we're creating lots of lists of named elements and in those cases using `=`. I actually had to test for myself to discern that `<-` is allowed in list creation but doesn't yield a named element, just an anonymous element with the value. All to say that I find `<-` both unnecessary and indeed a possible source of confusion.

**Comment by jgabry** [comment]
I don't think there is anything wrong with `=` (in fact I like it), but we
definitely want to use a consistent coding style throughout the package
(and throughout all of our R packages if possible). So it's not so much a
question of `<-` vs `=`, it's just consistency. All of our R packages use
`<-` and while I wouldn't have a problem if they all used `=` I don't think
it's worth changing everything.

**Comment by mike-lawrence** [comment]
> I don't think it's worth changing everything.

```
find . -type f -name '*.r' | xargs sed -i 's/<-/=/g'
```
:)
But presumably you were aware of that kind of automation, and intended rather that there are other risks associated with a change.

**Comment by rok-cesnovar** [comment]
And it would need to be done over all stan-related R packages.

**Comment by jgabry** [comment]
On Thu, Apr 1, 2021 at 1:32 PM Mike Lawrence ***@***.***>
wrote:

> But presumably you were aware of that kind of automation, and intended
> rather that there are other risks associated with a change.
>
> If a significant majority of contributors to stan-dev R packages were in
favor of using `=` then maybe it would be worth it, but almost everyone is
used to coding with `<-`, which is also the standard in the R community (so
most new contributors will be used to `<-`). It's also the recommended
style in every prominent R style guide I've seen (e.g.
http://adv-r.had.co.nz/Style.html,
https://google.github.io/styleguide/Rguide.html, etc.). So even though I'm
not personally opposed to using `=` in theory I really don't think it's
worth changing.


>
