### ISSUE TITLE
Make sure all argument doc clearly indicates type in parentheses

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#496]
We're a bit inconsistent in the doc about indicating argument types. Sometimes we do this 

```
@param arg (type) ...
```

and other times we don't put the type in parenthesis and just mention it in a sentence. It's so much clearer if the types are made explicit like this than if they're just described somewhere in a sentence so I think we should do this throughout the package. Ideally we should do this in all of our R packages because it's much better than the typical R doc. 

I'm working on some doc updates already so I'll take care of this. (Thanks to @bob-carpenter for reminding me about this!)

**Comment by rok-cesnovar** [comment]
Good call!
