### ISSUE TITLE
Use `model$variables()` format also for variables in `metadata()`

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#504]
In CmdStan 2.27 we will be able to obtain a JSON with a list of data variables, parameters/transformed parameters and generated_quantities from stanc3 with - `--info`. 

I think we should add methods to the CmdStanModel class:
- `$data()` returns a vector of data variables (also useful for checking the input data)
- `$parameters()` returns a vector of parameters/trans. paramaters/GQ

I am not sure if `$parameters()` should also return the list of generated_quantities? Maybe return a list with separate vectors for parameters, transformed_parameters and generated_quantities?

Maybe model$variables() that returns a list of data/parameters/TP/GQ? I am not sure what the best API would be.

This information will be consumed by cmdstanr for checking data/init values (so we need to separate parameters from TP and GQ) or could be consumed by the user like shown here: https://github.com/stan-dev/cmdstanr/issues/377#issuecomment-756289778

**Comment by jgabry** [comment]
Awesome. 

> Maybe model$variables() that returns a list of data/parameters/TP/GQ? I am not sure what the best API would be.

I think I like this option the best, with sublists for each of the different blocks. 

Also, I haven't thought this through much but what about using this information to structure the variables reported by `fit$metadata()`? Right now the parameters, transformed parameters, and generated quantities are all lumped in together.

**Comment by rok-cesnovar** [comment]
> Also, I haven't thought this through much but what about using this information to structure the variables reported by fit$metadata()? Right now the parameters, transformed parameters, and generated quantities are all lumped in together.

How do we want to do this? There are two different cases we need to handle:
a) cmdstan 2.26.1 and earlier or if fit is the result of as_cmdstan_fit (from CSV files only)
b) cmdstan 2.27.0+ and not result of as_cmdstan_fit

Options:
1.) leave it as $model_params for a) and split $model_params to $parameters, $transformed_parameters, $generated_quantities and leave $model_params
2.) leave it as $model_params for a) and split $model_params to $parameters, $transformed_parameters, $generated_quantities and remove $model_params
3.) leave it as $model_params for a) and do the split inside model_params to $model_params$parameters, $model_params$transformed_parameters, $model_params$generated_quantities

**Comment by jgabry** [comment]
I forgot that this won't work for the output from `as_cmdstan_fit`. Maybe (1) is best because it doesn't break the existing `model_params` in any situation. But I'm open to other options if you prefer. 

It's also a bit unfortunate that this is called `params` and not `variables` since many of these variables are not parameters. But maybe it's too much to change the name also?

**Comment by rok-cesnovar** [comment]
The only problem I have with (1) is that the type of the return changes between versions. Maybe lets just change the name (have both until 1.0) and 
if anyone wants to organize them they can use `mod$variables()`?

**Comment by jgabry** [comment]
Ok yeah that sounds good.
