### ISSUE TITLE
Replace recommendations in warning messages with link to website

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#505]
@martinmodrak @andrewgelman @avehtari and I are working on the content for a webpage that will have recommendations for how to proceed after seeing Stan's various warning messages (basically it's an improved (and non rstan-specific) version of http://mc-stan.org/misc/warnings). This will allow us to remove the recommendations from the warning messages themselves and instead point to the website. Three of the advantages of this are: 

* we can keep improving the recommendations without having to keep changing the warning messages
* we can put more thorough recommendations than we can fit in warning messages
* multiple interfaces can point to the same webpage

For now there's no action necessary for CmdStanR, but as soon as the website is ready we can address this issue.

**Comment by jgabry** [comment]
@avehtari @martinmodrak @andrewgelman Any updates on this website? Is there anything I can do to help get us closer? I ask because we're about to add E-BFMI warnings to CmdStanR (see #500) to go along with the current checks for divergences and treedepth problems, but I'm mindful of the fact that we still don't have anywhere to direct the users when they see these warnings.

**Comment by martinmodrak** [comment]
My conclusion from the last discussion with @avehtari is that the current draft is satsifactory except for the "What are divergences" appendix that needs a bit more work. So I think we can definitely make the draft into a public page without the appendix almost immediately (it might be useful to ask for additional feedback on Discourse before that).

**Comment by jgabry** [comment]
Ok great, thanks Martin! 

> (it might be useful to ask for additional feedback on Discourse before that).

By "before that", do you mean before making it public or before adding the divergences appendix?

**Comment by martinmodrak** [comment]
I meant before making the document public and start linking to it from error messages.

**Comment by jgabry** [comment]
Ok cool, that makes sense. @avehtari What do you think? Are you ok with soliciting comments about the current draft on discourse at this point?
