### ISSUE TITLE
should `write_stan_json` error with duplicate names?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#515]
This currently works but I think it should probably be an error: 

```r
write_stan_json(list(x = 1, x = 2), file = tempfile())
```

@rok-cesnovar (or anyone else) can you think of any reason not to error here? If there's no good reason then I'll go ahead and add an error.

**Comment by rok-cesnovar** [comment]
Agree, this should definitely error!

**Comment by mike-lawrence** [comment]
I didn't even know that R permits duplicate names in lists!

**Comment by jgabry** [comment]
> I didn't even know that R permits duplicate names in lists!

Yeah it's super weird. I'm not sure why it's allowed.
