### ISSUE TITLE
Add as.mcmc.list function for CmdStanMCMC

### ISSUE THREAD

**Issue by MatsuuraKentaro** [stan-dev/cmdstanr#521]
The plot function in the `coda` package is still useful to draw trace plots when the number of parameters is large, because it draws fast and paginates a pdf file.

To make this easier, I would like to add the following `as.mcmc.list` function for the `CmdStanMCMC` class. This will also work if a model contains multidimensional parameters. This function corresponds to the `As.mcmc.list` function in the `rstan` package.

```r
library(coda)

as.mcmc.list.CmdStanMCMC <- function(fit) {
  sample_matrix <- fit$draws()
  class(sample_matrix) <- 'array'
  n_chain <- dim(sample_matrix)[[2]]
  mcmc_list <- as.mcmc.list(
    lapply(seq_len(n_chain),
           function(chain) as.mcmc(sample_matrix[, chain, ])))
  return(mcmc_list)
}
```

If we have this function, for example, we can easily save the trace plot to pdf as follows:
```r
library(cmdstanr)
library(coda)

...
fit <- model$sample(data=data, seed=123)

pdf(file='traceplot.pdf')
plot(as.mcmc.list(fit))
dev.off()
```

**Comment by jgabry** [comment]
Hi @MatsuuraKentaro, thank you for the suggestion! 

I have mixed feelings about this. On the one hand you are definitely correct that the ggplot2-based traceplots are slower than what coda does, especially for large numbers of parameters. On the other hand, if the number of parameters is large we don't recommend making trace plots for all of them (i.e., we don't recommend looking at hundreds or thousands of traceplots), so I'm not sure we need this if the only purpose is to plot tons of trace plots. But I'm open to being convinced ;) 

What do other people think?

**Comment by MatsuuraKentaro** [comment]
Hi @jgabry, thank you very much for reply!

Sorry for misleading you by writing only the main purpose.
The `as.mcmc.list` function is only a data conversion function, and it facilitates the transition to Stan for BUGS and JAGS users who are used to `mcmc.list`.

If this issue in the `bayesplot` package, it would be unnecessary. However, since this is in the `cmdstanr` package, I think it would be preferable to give users the options of which package to use after sampling.

**Comment by jgabry** [comment]
Hi @MatsuuraKentaro, very sorry for the delay on this! I think I accidentally marked this as "read" so it wasn't showing up anymore in my list of issues to work on. 

I think you are right that adding this function for would helpful for some users. Would you like to submit a pull request for this and contribute to CmdStanR? If not (no worries!) then I can try to add it.

**Comment by MatsuuraKentaro** [comment]
Hi @jgabry, thank you for the reply! I made a pull request, but it looks like I am not authorized to create a branch in the cmdstanr repository. Do I need some kind of authorization?

I thought it would be a good idea to add the following `as.mcmc.list` function to `R/utils.R` so as not to contaminate other files (and not to depend on `coda` package). 

```
# convert draws --------------------------------------------------------

#' Convert CmdStanMCMC object to mcmc.list object in coda package
#'
#' @noRd
#' @param fit CmdStanMCMC object
#' @return mcmc.list object in coda package
#' @export
as.mcmc.list <- function(fit) {
  sample_matrix <- fit$draws()
  class(sample_matrix) <- 'array'
  n_chain <- dim(sample_matrix)[[2]]
  mcmc_list <- coda::as.mcmc.list(
    lapply(seq_len(n_chain),
           function(chain) coda::as.mcmc(sample_matrix[, chain, ])))
  return(mcmc_list)
}
```

I have no experience in package development, so I'm sorry I didn't know how to add a test and how to add documents. After executing `pkgload::load_all()` on RStudio, I just checked that the following code terminated normally.

```
set_cmdstan_path()
mod <- testing_model("bernoulli")
data_list <- testing_data("bernoulli")
fit <- mod$sample(data = data_list)
pdf(file='test-plot.pdf')
plot(as.mcmc.list(fit))
dev.off()  
```

**Comment by MatsuuraKentaro** [comment]
I have removed the dependency on the coda package.

```
# convert draws --------------------------------------------------------

#' Convert CmdStanMCMC object to mcmc.list object in coda package
#'
#' @noRd
#' @param fit CmdStanMCMC object
#' @return mcmc.list object in coda package
#' @export
as_mcmc_list <- function(fit) {
  sample_matrix <- fit$draws()
  class(sample_matrix) <- 'array'
  n_chain <- dim(sample_matrix)[[2]]
  n_iteration <- dim(sample_matrix)[[1]]
  mcmc_list <- lapply(seq_len(n_chain), function(chain) {
    x <- sample_matrix[, chain, ]
    dimnames(x) <- list(iteration = dimnames(sample_matrix)$iteration,
                        variable  = dimnames(sample_matrix)$variable)
    attr(x, 'mcpar') <- c(1, n_iteration, 1)
    class(x) <- 'mcmc'
    x
  })
  class(mcmc_list) <- 'mcmc.list'
  return(mcmc_list)
}
```

The code for check is as follows:
```
set_cmdstan_path()
mod <- testing_model("bernoulli")
data_list <- testing_data("bernoulli")
fit <- mod$sample(data = data_list)
library(coda)
pdf(file='test-plot.pdf')
plot(as_mcmc_list(fit))
dev.off()
```
To modify `NAMESPACE`, I will run `devtools::document()`.

**Comment by jgabry** [comment]
> Hi @jgabry, thank you for the reply! I tried to make a pull request, but it looks like I am not authorized to create a branch in the cmdstanr repository. Do I need some kind of authorization?

If you want to make the pull request what you can do is to "fork" the cmdstanr repository and create a branch in your fork. And then you would submit the PR from your fork to our master branch. If you'd rather not deal with all this that's totally fine and I can take the code you've written and add it (giving you credit of course!). Let me know what you prefer, either way is ok. 


> I have removed the dependency on the coda package.

Great, thanks, the code looks good!

**Comment by MatsuuraKentaro** [comment]
I followed your advice and created a pull request:
https://github.com/stan-dev/cmdstanr/pull/584
I hope this is OK.

**Comment by jgabry** [comment]
> I hope this is OK.

Yes, thank you!
