### ISSUE TITLE
draws method: using `format='matrix'` can permanently mess up draws stored internally

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#523]
**Describe the bug**

Currently using the `format` argument to `draws()` not only changes the returned draws format but also changes the format used to store the draws:

https://github.com/stan-dev/cmdstanr/blob/bee82544915179be3c348c9ec3f85a72cb446de8/R/fit.R#L226
https://github.com/stan-dev/cmdstanr/blob/bee82544915179be3c348c9ec3f85a72cb446de8/R/fit.R#L865
https://github.com/stan-dev/cmdstanr/blob/bee82544915179be3c348c9ec3f85a72cb446de8/R/fit.R#L1388

The problem is that changing the storage format means that if `draws(format="matrix")` is used even just one time it results in chain information being lost permanently.

**To Reproduce**

```r
fit <- cmdstanr_example()
posterior::nchains(fit$draws(format = "array"))   # returns 4 (correct)
posterior::nchains(fit$draws(format = "df"))      # returns 4 (correct)
posterior::nchains(fit$draws(format = "matrix"))  # returns 1 (correct because matrix combines them) 

# now try array and df again after using matrix
posterior::nchains(fit$draws(format = "array"))   # returns 1 (wrong!)
posterior::nchains(fit$draws(format = "df"))      # returns 1 (wrong!)
```

**Expected behavior**

To be able to use array and df after matrix and still get the correct output. 

**CmdStanR version number**

0.4.0.9000

**Comment by rok-cesnovar** [comment]
Possible solutions: 
a) do not convert internal storage to matrix (convert before returning)
b) store matrix separately if used

a is more computation for access, b is more RAM used. I am fine with any of them.

**Comment by rok-cesnovar** [comment]
With Github version of posterior this is now fixed:

```r
> library(cmdstanr)
> fit <- cmdstanr_example()
Compiling Stan program...
 
> posterior::nchains(fit$draws(format = "array"))   # returns 4 (correct)
[1] 4
> posterior::nchains(fit$draws(format = "df"))      # returns 4 (correct)
[1] 4
> posterior::nchains(fit$draws(format = "matrix"))  # returns 1 (correct because matrix combines them) 
[1] 4
> posterior::nchains(fit$draws(format = "array"))   # returns 1 (wrong!)
[1] 4
> posterior::nchains(fit$draws(format = "df"))      # returns 1 (wrong!)
[1] 4
```
We can close this now or once we bump the minimum posterior version once the next posterior version is released.

**Comment by jgabry** [comment]
Ok great, let's just go ahead and close this. We might forget to close it when posterior is released.
