### ISSUE TITLE
check_cmdstan_toolchain fails to notice problem for some configurations of PATH

### ISSUE THREAD

**Issue by jsocolar** [stan-dev/cmdstanr#529]
### Background
In a failed attempt to get OpenMP working, I installed llvm with `brew install llvm`. This didn’t play nicely with the compiler flags that I was using for arm64 architecture, and so after fiddling around blindly for a while, I eventually reinstalled llvm and then uninstalled it with `brew uninstall llvm`.

### The problem
After uninstalling, I was left in a state where the behavior of Stan, called from R (with or without Rstudio) depended on whether I opened R(studio) by double-clicking the icon in the `/Applications` folder or opening it via Terminal with `open /Applications/Rstudio.app` or `open /Applications/R.app`. Instances opened by double clicking worked completely as expected. Instances opened from Terminal displayed the following behavior:

* failure to compile any c++, erroring with `error: can't exec '/opt/local/libexec/llvm-10/bin/clang++' (errno=NO such file or directory)`. This same error was also returned by Terminal when running, for example `clang++ -v`.
* `cmdstanr::check_cmdstan_toolchain()` indicated that the toolchain was set up properly.
* From R, `dirname(Sys.which("clang++"))` (which is used by `cmdstanr::check_cmdstan_toolchain()`) returned `"/opt/local/bin"`
* Setting the `PATH` in my `~/.zprofile` or `~/.bash_profile` to the above path (i.e. `export PATH="/opt/local/bin:$PATH"`) didn’t change anything.

### The solution
I needed to set the PATH to `“/usr/bin”` (i.e. `export PATH="/usr/bin:$PATH"`). This worked after an install of Xcode (not just Xcode command line tools), but I don’t have any reason to believe that the install of Xcode was necessary, except to help me troubleshoot (see below).

### How I got there
After installing Xcode, the output of R’s `dirname(Sys.which("clang++"))` changed from `"/opt/local/bin"` to `"/usr/bin"`, which was the path I needed.

### What I think was going on
My env had `PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin`
I don’t know why R (both the versions that worked after launching by double-click and the versions that didn’t work after launching with terminal) initially returned `"/opt/local/bin"` from `dirname(Sys.which("clang++"))`, but in any case I think this wasn’t the correct path. Then, the Terminal-launched instances of R were looking on my PATH variable and going to `/opt/homebrew/bin`, which was still trying to point to my uninstalled llvm. Something like that anyway. 

# More details and info at
https://mc-stan.zulipchat.com/#narrow/stream/293049-general/topic/C.2B.2B.20woes
https://discourse.mc-stan.org/t/psa-setting-the-correct-path-for-compilation-on-osx/23163

**Comment by rok-cesnovar** [comment]
Sounds like it was a nightmare, sorry about that and thanks very much for the very detailed report and fix!. 

It does seem to me like this one would be difficult to flag automatically and avoid false positives. The question mostly is if we are sure `/opt/local/bin` will never be a valid return of `dirname(Sys.which("clang++"))` ? I am not confident enough to say it can never be.

Maybe we can just rely on users coming to this issue when googling this issue? Is this specific enough of a case where we can hope on that?

**Comment by rok-cesnovar** [comment]
Cleaning up issues, will close this as I really feel this one cant be fixed automatically.
