### ISSUE TITLE
codecov not updating recently 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#53]
@rok-cesnovar It seems that the last time codecov updated was after PR #43 was merged, 

 https://codecov.io/gh/stan-dev/cmdstanr/   (see "ALL RECENT COMMITS")

which means the next commit (PR #44) is likely the culprit. But I can't figure out why except that it has something to do with the test for `install_cmdstan`. It seems to run fine on travis (the tests pass) but then errors when codecov runs after travis is successful. See the travis log for PR #44  starting with line 936 for the error:

https://travis-ci.org/stan-dev/cmdstanr/jobs/602674188#L936

Any ideas? This isn't a huge deal, just weird.

**Comment by rok-cesnovar** [comment]
Will have a look, seems weird.

**Comment by jgabry** [comment]
Bummer, that didn't fix it. Anyway, this is something we can try to sort out but don't worry about spending too much time on it.

**Comment by jgabry** [comment]
fixed by #54
