### ISSUE TITLE
Error reading matrix with large integral numbers

### ISSUE THREAD

**Issue by alyst** [stan-dev/cmdstanr#533]
**Describe the bug**
Stan model fails to run with errors like
```
Chain 1 Exception: msglm_normalize_model_namespace::msglm_normalize_model: qData[sym1__, sym2__] is -1.26487e+09, but must be greater than or equal to 0 (in '/tmp/Rtmpf0rDdB/model-5e8fb26d65883.stan', line 17, column 2 to column 47)
```

The line in question in the Stan model is
```
matrix<lower=0>[Nobjects, Nmschannels] qData;
```

The input data that leads to the failure is [temp.json.zip](https://github.com/stan-dev/cmdstanr/files/6942289/temp.zip) (generated with `write_stan_json())`.
In R the original *qData* matrix has type double.

**To Reproduce**
Define the Stan model with *qData* as specified above, run it with given *qData* from the attachment.

**Expected behavior**
The given qData is correctly read by cmdstan, no range error occurs.

**Operating system**
ArchLinux

**CmdStanR version number**
CmdStanR is 0.4.0.9000, Stan is 2.27

**Additional context**
My current workaround is to modify the *qData* to contain fractional parts (e.g by adding very small number).
It seems in that case the numbers would be parsed as float and no integral overflow will occur.
So one potential fix would be to somehow force the decimal dot in the *.json* output of the double numbers.

There were no problems running the model with *rstan* (Stan 2.19).
Probably because with *rstan* the data is fed to the *Stan* model directly without saving and loading the *.json* file.

**Comment by jgabry** [comment]
@alyst thanks for reporting this. My first guess is that this is related to https://github.com/stan-dev/cmdstan/issues/1023. @rok-cesnovar do you agree?

**Comment by alyst** [comment]
@jgabry Yes, it's the same issue as stan-dev/cmdstan#1023.
