### ISSUE TITLE
R option for location of Stan file in write_stan_file

### ISSUE THREAD

**Issue by StaffanBetner** [stan-dev/cmdstanr#535]
It would be useful if a default location of Stan code files (and their compiled binaries) could be set with a R options statement, e.g. `options(write_stan_file_location = path)`, as many models that I, and many with me, fit with brms are the same seen from a Stan perspective.

**Comment by rok-cesnovar** [comment]
Ok, just to make sure everything is clear. If you write the same model with `write_stan_file()` it will be saved to the same temporary file.

```r
code <- "
data {
  int<lower=0> N;
  array[N] int<lower=0,upper=1> y;
}
parameters {
  real<lower=0,upper=1> theta;
}
model {
  theta ~ beta(1,1);
  y ~ bernoulli(theta);
}
"

file_1 <- write_stan_file(code)
file_2 <- write_stan_file(code)

> file_1
[1] "/tmp/RtmpchRWen/model_ed4e3bc0f908e1aa81f53d5c47513a84.stan"
> file_2
[1] "/tmp/RtmpchRWen/model_ed4e3bc0f908e1aa81f53d5c47513a84.stan"
```

You can also set the output dir for `write_stan_file()` and that will then save those temporary files there:
```r
file_1 <- write_stan_file(code, dir = "/home/rok/Desktop/test")
file_2 <- write_stan_file(code, dir = "/home/rok/Desktop/test")

> file_1
[1] "/home/rok/Desktop/test/model_ed4e3bc0f908e1aa81f53d5c47513a84.stan"
> file_2
[1] "/home/rok/Desktop/test/model_ed4e3bc0f908e1aa81f53d5c47513a84.stan"
```

In the first case, the model would not be recompiled inside the same R session, in the second one it would not be recompiled between sessions. But that leaves exe files and wastes users disk space and the users has to manually clean up the mess.

So, if I understand correctly, what you would want is to have an option to set the `dir` in `write_stan_file()`?

So [this](https://github.com/stan-dev/cmdstanr/blob/24b50ad412a4428132cd12fd1ade964d752a4caf/R/example.R#L145) signature would become

```r
write_stan_file <- function(code,
                            dir = getOption("cmdstanr_write_stan_file_dir", tempdir()),
                            basename = NULL,
                            force_overwrite = FALSE,
                            hash_salt = "") {
```

If I am understanding this correct I would be happy to add this, seems useful. If not, please correct me.

**Comment by StaffanBetner** [comment]
Yes, you understand precisely what I mean. I created a brms branch that did it, but I figured it would be more suitable to have the functionality directly in cmdstanr.
