### ISSUE TITLE
support rvars draws format

### ISSUE THREAD

**Issue by avehtari** [stan-dev/cmdstanr#536]
With the current github version
```
> draws <- fit_bern$draws(format="rvars")
Error: The supplied draws format is not valid. 
> draws <- fit_bern$draws(format="draws_rvars")
Error: The supplied draws format is not valid. 
```
and
```
> options(cmdstanr_draws_format="rvars")
> fit_bern <- mod_bern$sample(data = data_bern, seed = SEED)
Error: The supplied draws format is not valid.
```

It would be nice to support the rvars format, too.

**Comment by rok-cesnovar** [comment]
Thanks Aki!

A fix for this is ready on https://github.com/stan-dev/cmdstanr/tree/allow_draws_rvars but would just like to see if we can resolve https://github.com/stan-dev/posterior/issues/192 first.

**Comment by jgabry** [comment]
Before closing this we need

* posterior update on CRAN (currently works with github version)
* bump required posterior version in DESCRIPTION
