### ISSUE TITLE
sample method arg is "save_extra_diagnostics", docs say "save_latent_dynamics" - which is it?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#542]
Asking this question for compatability with CmdStanPy, cf issue: https://github.com/stan-dev/cmdstanpy/issues/260

looking at CmdStanR docs here - listing is inconsistent:  https://mc-stan.org/cmdstanr/reference/model-method-sample.html

**Comment by rok-cesnovar** [comment]
Its `save_latent_dynamics`:  https://github.com/stan-dev/cmdstanr/blob/ab7a359377182e711ef11d474daa9401a788ece9/R/model.R#L720

It was initially `save_extra_diagnostics` but that one is deprecated (https://github.com/stan-dev/cmdstanr/blob/ab7a359377182e711ef11d474daa9401a788ece9/R/model.R#L785). Its still there for now (duplicated functionality) but will be removed for 1.0.

**Comment by mitzimorris** [comment]
thanks!
