### ISSUE TITLE
Error: Can’t find the following sampler diagnostic(s) in the output: treedepth__, divergent__ 

### ISSUE THREAD

**Issue by jpkrooney** [stan-dev/cmdstanr#547]
**Describe the bug**
I'm getting the above error when running some models but not others under cmdstanr. Similar to https://github.com/stan-dev/cmdstanr/issues/364 but different enough that @rok-cesnovar asked me to start a new bug report here. 

**To Reproduce**
The linked model `simuGP.stan` appears to run but errors out at the last moment [https://discourse.mc-stan.org/uploads/short-url/dpfyaqrLYzlc8rNQR8Q0YaUbDfl.stan](url)

```
N = 551
x <- 22 * (0:(N - 1)) / (N - 1) - 11
alpha_true <- 3
rho_true <- 5.5

file <- file.path("simuGP.stan")

# Data as a named list (like RStan)
simu_data <- list(alpha=alpha_true, rho=rho_true, N=N, x=x)

# Run MCMC using the 'sample' method
fit_mcmc <- mod$sample(
    data = simu_data,
    seed = 123,
    chains = 2,
    parallel_chains = 2
)

```
This give me this output:
<img width="857" alt="Screenshot 2021-09-09 at 22 03 18" src="https://user-images.githubusercontent.com/41968663/132761509-f2c37a23-fea3-44d4-9ccf-3b3819dc519d.png">

**Operating system**
MacOS 11.4 Big Sur

**CmdStanR version number**
‘0.4.0.9000’

**Comment by rok-cesnovar** [comment]
Thanks. 

This bug occurs because Cmdstan 2.27.0+ will automatically switch to the `fixed_param` algorithm when there are no parameters and the output of fixed_param does not include `treedepth__`, `divergent__` or any other sampler diagnostics.
