### ISSUE TITLE
Feature request: add file extension to compiled objects

### ISSUE THREAD

**Issue by vandenman** [stan-dev/cmdstanr#551]
**Is your feature request related to a problem? Please describe.**
For many projects, I either use git or an automatic cloud service (or both). In both cases, I don't want to track or sync all files. However, models compiled through cmdstanr do not have a file type suffix (on Ubuntu 20.04). This makes it complicated to exclude the shared libraries from being synced or tracked in version control.

**Describe the solution you'd like**
An option to add a suffix to the compiled object (preferably enabled by default). I guess the suffix should be .so on Linux, .dylib on macOS, and .dll on Windows.

**Describe alternatives you've considered**
Waste a lot of space in the cloud by storing model objects that I cannot reuse on other computers.

**Additional context**
I'd be happy to open a PR to implement this.

**Comment by rok-cesnovar** [comment]
Hi, 

thanks for the feature request.

>  I guess the suffix should be .so on Linux, .dylib on macOS, and .dll on Windows.

These suffices can be used for shared object files, but these are executables, so  they have a .exe  suffix on Windows and no suffix on Mac/Linux, both of which are standard for the respective OSes.

An option that is possible is that we allow specifying `exe_file`, so users could specify their own exe file name.

**Comment by vandenman** [comment]
> both of which are standard for the respective OSes.

Hmm, I looked it up and you're right. I guess my workflow is just wrong and I should create a folder structure where all the executables end up in one directory which is excluded by default.
