### ISSUE TITLE
[FR] Add an extention or suffix to exe file even on non-Windows platforms

### ISSUE THREAD

**Issue by yutannihilation** [stan-dev/cmdstanr#556]
**Is your feature request related to a problem? Please describe.**
An extension is useful when I do not want to commit compiled model executables into a Git repository. With rstan, this is possible by ignoring `.rds` (and, ~~as this is included in a typical `.gitignore` for R, I guess most users don't even worry about this.~~ edit: sorry, this isn't true)

**Describe the solution you'd like**
I have no idea, but it might be easy to consistently add `.exe`?

**Describe alternatives you've considered**
If `.exe` looks weird for non-Windows, how about some suffix for example `-precompiled` at the end.

**Additional context**
N/A

**Comment by yutannihilation** [comment]
Ah, sorry I missed https://github.com/stan-dev/cmdstanr/issues/551 was recently filed and closed. Reading this comment,

> An option that is possible is that we allow specifying `exe_file`, so users could specify their own exe file name.
https://github.com/stan-dev/cmdstanr/issues/551#issuecomment-917960185

now I feel it might be good to describe `dir` argument in `cmdstan_model()` explicitly so that users can find how to specify the dir easily. Anyway now I agree that specifying the common extension despite the OSes isn't a good solution.

**Comment by rok-cesnovar** [comment]
Thanks @yutannihilation.

Yeah, `dir` is only documented with the $compile() method: https://mc-stan.org/cmdstanr/reference/model-method-compile.html

**Comment by yutannihilation** [comment]
Yes, I know. I meant exposing it explicitly. If this sounds good, I can create a pull request.

https://github.com/stan-dev/cmdstanr/compare/master...yutannihilation:doc/issue-556-add-dir-argument

**Comment by rok-cesnovar** [comment]
Will let @jgabry decide here. I am not so sure what is typically done in R packages wrt to this.

**Comment by yutannihilation** [comment]
Sure. To be clear, as I'm a very newbie to rstan and cmdstanr world, I have no idea how a typical project manages the compiled models. So I might be wrong here.

**Comment by rok-cesnovar** [comment]
@jgabry bumping you here again. Not sure what would be the best way to resolve this? I am not exactly an expert on R package docs.

**Comment by jgabry** [comment]
Unfortunately the best solution (using roxygen2's `@inheritDotParams`) won't work for us because of the way we're documenting the R6 methods. 

Instead what if we just mention in the doc for `...` what sorts of things are possible via the compile method. For example, the current doc for `...` is 

```
#' @param ... Optionally, additional arguments to pass to the
#'   [`$compile()`][model-method-compile] method if `compile=TRUE`.
```

What if we change it to this? 

```
#' @param ... Optionally, additional arguments to pass to the
#'   [`$compile()`][model-method-compile] method if `compile=TRUE`. These
#'   options include specifying the directory for saving the executable, turning
#'   on pedantic mode, specifying include paths, configuring C++ options, and
#'   more. See [`$compile()`][model-method-compile] for details.
```

**Comment by rok-cesnovar** [comment]
Yeah, I am cool with that.

**Comment by yutannihilation** [comment]
Thanks for improving the docs! While it itself looks good, I'm afraid it might not prevent the confusion like mine (and #551) much, but let's see if there will be some similar issues filed. I'm fine to close this for now.
