### ISSUE TITLE
Support mew multi thread multi chain sampling

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstanr#566]
**Is your feature request related to a problem? Please describe.**
It would be great to make use of the new feature of multi thread, multi chain sampling in 2.28

**Describe the solution you'd like**
Better use of ressources

**Describe alternatives you've considered**
Na

**Additional context**
Nope

**Comment by rok-cesnovar** [comment]
I have this mostly ready yeah. Will finish it up after the release is all done tomorrow. There was already an issue created for this https://github.com/stan-dev/cmdstanr/issues/534

**Comment by wds15** [comment]
oh... I did not know that...then we can close this issue?

Great to have this in cmdstanr soon! Will you make a release for that feature? I'd guess that makes sense, no?

**Comment by rok-cesnovar** [comment]
Lets close this one to keep the communication in one place.

> Will you make a release for that feature?

A new release is overdue anyways so I think it makes sense yes.
