### ISSUE TITLE
Unhelpful error message when size declarations are off

### ISSUE THREAD

**Issue by MerlinHeidemanns** [stan-dev/cmdstanr#567]
**Describe the bug**
This happens when trying to assign a vector to another object of a different size. Since the error message below does not indicate where the error i.e. the inaccurate size declaration occurs, I'd consider this a bug (also because I spent three hours trying to determine what causes this in the original model).

Chain 4 Assertion failed: (rows == this->rows() && cols == this->cols() && "DenseBase::resize() does not actually allow to resize."), function resize, file stan/lib/stan_math/lib/eigen_3.3.9/Eigen/src/Core/DenseBase.h, line 257.
Warning: Chain 4 finished unexpectedly!

**To Reproduce**
model <- "transformed data {
  vector[2] original;
  vector[3] copy = original;
}"
fit <- model $sample()

**Expected behavior**
I'd expect to receive an error that tells me where the code is off

**Operating system**
macOSX 11.2.3

**CmdStanR version number**
0.4.0

**Comment by rok-cesnovar** [comment]
Hi @MerlinHeidemanns, 

thanks for the report and sorry to here about the long debugging times :/

This particular issue has been known for some time and is an issue in the cmdstan backend (https://github.com/stan-dev/stanc3/issues/523). I bumped that issue again. Will keep this issue open until a release that will fix this.

**Comment by rok-cesnovar** [comment]
This issue was addressed in CmdStan. With 2.29.2 the error message when running: 

```r
model <- "transformed data {
vector[2] original;
vector[3] copy = original;
}"
stan_file <- write_stan_file(model)
mod <- cmdstan_model(stan_file)
fit <- mod$sample(fixed_param = TRUE)
```

is: 

```
Chain 1 Exception: vector assign rows: assigning variable copy (3) and right hand side rows (2) must match in size (in '/tmp/RtmpBTwd2F/model-2800064946674b.stan', line 3, column 0 to column 26)
Warning: Chain 1 finished unexpectedly!
```
