### ISSUE TITLE
Make sure `skip_on_cran()` is used for tests when necessary

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#574]
I think we have some tests that are missing `skip_on_cran()` (I know I've forgotten to add it a few times at least), so just opening this issue and adding it to the version 1.0 milestone so we remember to fix this before the CRAN release.

**Comment by jgabry** [comment]
@rok-cesnovar As an alternative to using `skip_on_cran()` in most of our tests, we could do what RStudio does for their tensorflow package and skip _all_ the tests on CRAN: 

https://github.com/rstudio/tensorflow/blob/b968ecae4c7c6497bbf8c7e8c4cd8742a3f3cfdf/tests/testthat.R#L4-L5

The advantage of this approach would be that we don't need to worry about putting `skip_on_cran()` in our tests. The disadvantage is that zero tests would be run on CRAN (we do have some tests that could be run on CRAN because they test functions that don't require running CmdStan, e.g. stuff in `utils.R` and other code not using CmdStan). 

But given that we have pretty thorough CI on GHA we could probably safely turn off all tests on CRAN and remove the burden of using `skip_on_cran()`. 

What do you think?

**Comment by rok-cesnovar** [comment]
> But given that we have pretty thorough CI on GHA we could probably safely turn off all tests on CRAN and remove the burden of using skip_on_cran().

I agree with this reasoning. I doubt running these same tests on the CRAN machines would add anything extra.

**Comment by jgabry** [comment]
Ok I'll make a PR that does this and removes all uses of `skip_on_cran()`. We're getting pretty close now on all the issues for v1.0!

**Comment by rok-cesnovar** [comment]
Yeah, I need to finish up the single-process multi-chain then together with the diagnostics its pretty close.
