### ISSUE TITLE
strange error when setting initial values

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/cmdstanr#576]
**Describe the bug**
I get a strange error when I set initial values for a specific model:
```
Chain 1 Unrecoverable error evaluating the log probability at the initial value.  
Chain 1 Exception: no more scalars to read (found before start of program) 
```
I'm not sure what's the meaning of this.

**To Reproduce**

Sorry for posting this monstrosity, but I can't create smaller example.

[lnrace.zip](https://github.com/stan-dev/cmdstanr/files/7353880/lnrace.zip)

```
df_blp <- readRDS("df_blp")
ls_blp_h_data <- list(N = nrow(df_blp),
                    rt = df_blp$rt,
                    nchoice = df_blp$nchoice,
                    c_lex = df_blp$c_lex,
                    lfreq = df_blp$lfreq,
                    N_subj = max(df_blp$subj),
                    subj = df_blp$subj)
lnrace_h <- "lnrace_h.stan"
  ln_mod <- cmdstan_model(lnrace_h)
  fit_lnrace_h_data_cmd <- ln_mod$sample(
    data = ls_blp_h_data,
    chains = 4,
    parallel_chains = 4,
    adapt_delta = .95,
    max_treedepth = 12,
     init =
      function() list(theta_c = runif(1, 0, .1))
  )
```
`theta_c` is a probability and I want the sampler to start from smaller values, but I also tried 
` function() list(theta_c = runif(1, 0, 1))` and all sort of options, and I still get the same error.

**Expected behavior**
I expect the model to run. And by the way, a simpler version of this model without hierarchical structure does work!

**Operating system**
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LT

**CmdStanR version number**
0.4.0.9000

**Comment by bnicenboim** [comment]
Also this works with rstan 2.21.2

**Comment by bnicenboim** [comment]
And for completeness it also works in the latest rstan

**Comment by rok-cesnovar** [comment]
Yeah, even stranger this has the same issue: 

```r
simple_model <- "
parameters {
  cholesky_factor_corr[2] L_u;
}
"

mod <- cmdstan_model(write_stan_file(simple_model))
fit <- mod$sample(
  chains = 1,
  init = function() list(L_u = matrix(c(1,-2, 0, 8),  ncol = 2)
)
```

**Comment by gbinding** [comment]
It might to be a problem with model compilation under cmdstanr 2.28.0. Using Ubuntu 20.04.3 LTS, cmdstanr_0.4.0, and R version 4.1.1 (2021-08-10), the model with initial values does not run if compiled with 2.28.0, does not run if using the model compiled in 2.28.0, but after having reverted to 2.27.0, and does run if it is compiled in 2.27.0 and run then.

```
library(cmdstanr)

simple_model <- "
parameters {
  cholesky_factor_corr[2] L_u;
}
"

# v 2.28.0 ####
install_cmdstan(
  dir = NULL,
  cores = getOption("mc.cores", 4),
  quiet = FALSE,
  overwrite = TRUE,
  timeout = 1200,
  version = NULL,
  release_url = "https://github.com/stan-dev/cmdstan/releases/download/v2.28.0/cmdstan-2.28.0.tar.gz",
  cpp_options = list(),
  check_toolchain = TRUE
)

cmdstan_path()

mod <- cmdstan_model(write_stan_file(simple_model, force_overwrite = T))
# doesn't work
fit <- mod$sample(chains = 1,  init = function() list(L_u = matrix(c(1.0, 0.0, 0.0, 1.0),  ncol = 2)))
# works
fit <- mod$sample(chains = 1)

# v 2.27.0 ####
install_cmdstan(
  dir = NULL,
  cores = getOption("mc.cores", 4),
  quiet = FALSE,
  overwrite = TRUE,
  timeout = 1200,
  version = NULL,
  release_url = "https://github.com/stan-dev/cmdstan/releases/download/v2.27.0/cmdstan-2.27.0.tar.gz",
  cpp_options = list(),
  check_toolchain = TRUE
)

cmdstan_path()

mod <- cmdstan_model(write_stan_file(simple_model, force_overwrite = FALSE))
# doesn't work
fit <- mod$sample(chains = 1,  init = function() list(L_u = matrix(c(1.0, 0.0, 0.0, 1.0),  ncol = 2)))
# works
fit <- mod$sample(chains = 1)

mod <- cmdstan_model(write_stan_file(simple_model, force_overwrite = TRUE))
# works
fit <- mod$sample(chains = 1,  init = function() list(L_u = matrix(c(1.0, 0.0, 0.0, 1.0),  ncol = 2)))
# works
fit <- mod$sample(chains = 1)
```

**Comment by torkar** [comment]
Rok, the below seems to work for me. Sure, a bunch of max treedepth and at the end I get,
```
Warning messages:
1: NAs introduced by coercion 
2: NAs introduced by coercion
```

But it samples using 2.28.1.

> Bruno, you are never a pain, your contributions with detailed bug reports are very very helpful. I havent responded much as I havent really gotten nowhere so far.
> 
> The simplest code with which I can replicate is this:
> 
> ```r
> library(cmdstanr)
> 
> options("cmdstanr_verbose" = TRUE) 
> 
> simple_model <- "data {
> }
> parameters {
>   cholesky_factor_corr[2] L_u;
>   vector[2] tau_u;
> }
> "
> 
> mod <- cmdstan_model(write_stan_file(simple_model))
> mod$sample(
>   chains = 1,
>   init = function() list(tau_u = c(.5,.5))
> )
> ```
> 
> Make sure to run `options("cmdstanr_verbose" = FALSE)` afterwards so you get less spam when running. The more helpful error I see is `Unrecoverable error evaluating the log probability at the initial value.`
> 
> The issue seems to stem from not setting initial values for L_u. As of this moment I have no idea why :/

**Comment by rok-cesnovar** [comment]
Oh, you are right, this was the same issue @gbinding had. Thanks for checking that!

**Comment by jgabry** [comment]
Thanks @torkar! Not only does that example now run for me too, but Bruno's smaller example also runs fine for me now. I haven't tested the much bigger original model. That is, this one runs ok for me with 2.28.1: 

> I managed to create much smaller minimal example, version 2.28.0
> 
> ```
> simple_model <- "data {
> }
> parameters {
>   vector<lower = 0>[2] tau_u;
>   matrix[2, 3] z_u;
>   cholesky_factor_corr[2] L_u;
> }
> transformed parameters {
>   matrix[3, 2] u;
>   u = (diag_pre_multiply(tau_u, L_u) * z_u)';
>   }
> model {
>   target += normal_lpdf(tau_u | 0, 1)
>     - 2 * normal_lccdf(0 | 0, 1);
>   target += lkj_corr_cholesky_lpdf(L_u | 2);
>   target += std_normal_lpdf(to_vector(z_u));
> 
> }
> "
> 
> mod <- cmdstan_model(write_stan_file(simple_model))
> mod$sample(
>     data = list(),
>     chains = 4,
>     parallel_chains = 4,
>     adapt_delta = .95,
>     max_treedepth = 12,
>      init =
>       function() list(tau_u = c(.5,.5))
>   )
> ```
> 
> I would bet it has to do with `L_u`, the `cholesky_factor_corr`, which is getting initial values of the wrong shape

**Comment by rok-cesnovar** [comment]
I can also confirm that the original example from @bnicenboim works fine with 2.28.1. Bruno, once you have the time, please try again with 2.28.1 and close the issue if you confirm my findings. Thanks!

**Comment by bnicenboim** [comment]
I just checked, it works! thanks!

**Comment by rok-cesnovar** [comment]
Woohoo, our simplest bugfix to date :)

Closing!
