### ISSUE TITLE
Allow specifying include paths 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#59]
Thanks to @mitzimorris for reminding us to check this. Right now it doesn't seem to be possible to compile via CmdStanR if using `#include` statements in the Stan program. 

@rok-cesnovar @bbbales2 Here's some code that produces the error (using some Stan programs I just added to the tests directory on the master branch)

```r
stan_file <- testthat::test_path("resources", "stan", "bernoulli_include.stan")
mod <- cmdstan_model(stan_file, quiet = FALSE) # will error
```

apparently because CmdStan can't find the Stan program specified by the `#include` statement (`divide_real_by_two.stan`) even though it's in the same directory as the main Stan program (`bernoulli_include.stan`).

**Comment by jgabry** [comment]
I can get this to work by changing the Stan program so that the `#include` statement includes a _full_ path, that is, changing 

https://github.com/stan-dev/cmdstanr/blob/4624deedaa5a45af32707b38494cd8f7126535b5/tests/testthat/resources/stan/bernoulli_include.stan#L2

to this 

```stan
#include /Users/jgabry/Documents/Stan/cmdstanr/tests/testthat/resources/stan/divide_real_by_two.stan
```

but for users I don't think we want to make them have to do this!

**Comment by mitzimorris** [comment]
in the philosophy of wrapping CmdStan, you need to get the user to specify the directories that need to be searched and specify this as part of the call to 'bin/stanc' using the `--include_paths=` option

**Comment by jgabry** [comment]
Ok thanks @mitzimorris !

**Comment by mitzimorris** [comment]
consequences for CmdStanPy:

1. model constructor takes flag "include_paths" which is a list of strings (paths)
2. model constructor also takes flag "compile"
3. compile method has argument "force" which forces recompile even if exe is newer than model.hpp - this will force it to pick up changes for models which use include

this needs more doc... working on updating CmdStanPy docs right now

**Comment by mitzimorris** [comment]
should "incude_paths" always include directory that Stan program occurs in?
putting this dir last in the list shouldn't hurt

**Comment by jgabry** [comment]
That seems like it would be convenient for users. There could be a rare case when a user doesn’t want that but I can’t think of one.

**Comment by jgabry** [comment]
(Since includes do actually currently work with full file paths this isn’t really a bug so I added the feature label. We definitely want to allow the user to specify the include paths as @mitzimorris demonstrated.)

**Comment by jgabry** [comment]
> in the philosophy of wrapping CmdStan, you need to get the user to specify the directories that need to be searched and specify this as part of the call to 'bin/stanc' using the stanc flag `include_paths`
> 
> ```
> bin/stanc  foo.stan --include_paths=path/to/includes,another/path/to/includes
> ```

Right now we're just calling `make` in CmdStanR and not calling `bin/stanc` directly, but I think we can just add this via `STANCFLAGS` right? @mitzimorris @rok-cesnovar Any reason to prefer calling `bin/stanc` directly?

**Comment by mitzimorris** [comment]
the only reason that CmdStanPy is calling `bin/stanc` directly is that this is how it was implemented in pycmdstan.  don't see why we shouldn't try calling make instead.
