### ISSUE TITLE
Print multiple parameter estimates with fit$summary()

### ISSUE THREAD

**Issue by fsdias** [stan-dev/cmdstanr#601]
Currently it is not possible to print summaries for more than one parameter at a time with fit$summary(). It would be nice to able to run:

`fit$summary("param1","param2")`

**Comment by jgabry** [comment]
The first argument `variables` can be a vector of parameters (the arguments after the first one are passed to `posterior::summarise_draws()`). So this will work: `fit$summary(c("param1","param2"))`.

**Comment by fsdias** [comment]
Thanks @jgabry. I should have thought of that! In any case, it would be useful to add this to the vignette.

**Comment by jgabry** [comment]
> it would be useful to add this to the vignette.

Yeah good idea! Will do that.
