### ISSUE TITLE
Problem with running cmdstanr: Error in data.table::fread(cmd = fread_cmd, colClasses = "character",  :

### ISSUE THREAD

**Issue by acraevschi** [stan-dev/cmdstanr#618]
I have reinstalled R, Rstudio and Rtools to use cmdstanr (to later use the newest _rethinking_ package). But I get a weird error message and I can't find solution elsewhere, although the same error is reported on this [page](https://stackoverflow.com/questions/66584705/cmdstanr-issue-related-to-data-tables-fread) but it has no answer. 

I have followed [this guide](https://mc-stan.org/docs/2_28/cmdstan-guide/cmdstan-installation.html) and everything seems to work. When I enter R and run the following piece of code, everything still seems to be working. 
```
file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)
mod$print()
```
But then, when I try to run a toy model or even a real one from _rethinking_ book, I get the same error as on the StackOverflow page (first hyperlink above): 
```
Error in data.table::fread(cmd = fread_cmd, colClasses = "character",  : 
  File 'C:\Users\LENOVO\AppData\Local\Temp\RtmpoDe8x4\file29f43d9a39f7' does not exist or is non-readable. getwd()=='C:/Users/LENOVO/Documents'
```

I try to run two following pieces of code. Either yield the same error. Note that in the first case, `mod$print()` actually works nicely, whereas `fit` doesn't.  

```

file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)

mod$print()

# names correspond to the data block in the Stan program
data_list <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500
)
```

```

library(rethinking)
data(chimpanzees)
d <- chimpanzees

## R code 11.2
d$treatment <- 1 + d$prosoc_left + 2*d$condition


dat_list <- list(
  pulled_left = d$pulled_left,
  actor = d$actor,
  treatment = as.integer(d$treatment) )

## R code 11.11
m11.4 <- ulam(
  alist(
    pulled_left ~ dbinom( 1 , p ) ,
    logit(p) <- a[actor] + b[treatment] ,
    a[actor] ~ dnorm( 0 , 1.5 ),
    b[treatment] ~ dnorm( 0 , 0.5 )
  ) , data=dat_list , chains=4)
precis( m11.4 , depth=2 )
```

I was suspicious of data.table package and deleted it completely, restarted R and tried running same thing again and it didn't help but the error message changed to: 

```
Error in loadNamespace(x) : there is no package called 'data.table'
```

Here's the session info:

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cmdstanr_0.4.0

loaded via a namespace (and not attached):
 [1] compiler_4.1.2    prettyunits_1.1.1 remotes_2.4.2     tools_4.1.2       testthat_3.1.2    digest_0.6.29    
 [7] pkgbuild_1.3.1    pkgload_1.2.4     jsonlite_1.7.3    evaluate_0.14     memoise_2.0.1     lifecycle_1.0.1  
[13] checkmate_2.0.0   rlang_0.4.12      cli_3.1.1         yaml_2.2.2        parallel_4.1.2    xfun_0.29        
[19] fastmap_1.1.0     withr_2.4.3       knitr_1.37        desc_1.4.0        fs_1.5.2          devtools_2.4.3   
[25] rprojroot_2.0.2   glue_1.6.0        R6_2.5.1          processx_3.5.2    rmarkdown_2.11    sessioninfo_1.2.2
[31] callr_3.7.0       purrr_0.3.4       magrittr_2.0.1    backports_1.4.1   ps_1.6.0          ellipsis_0.3.2   
[37] htmltools_0.5.2   usethis_2.1.5     cachem_1.0.6      crayon_1.4.2      brio_1.1.3       
```

**Comment by rok-cesnovar** [comment]
Sorry to hear about that @acraevschi .

Can you post the output of `Sys.getenv("R_SESSION_TMPDIR")`?

**Comment by acraevschi** [comment]
Thank you for helping me! 

Does it matter if I load _cmdstanr_ before running it? Just in case, I did load it, please tell me if I shouldn't. That's the output:
```
> Sys.getenv("R_SESSION_TMPDIR")
[1] ""
```

**Comment by rok-cesnovar** [comment]
No need to load cmdstanr first. 

Does `tmpdir()` print anything?

**Comment by acraevschi** [comment]
Tried again without loading cmdstanr, the output is the same for the function above. 

Did you mean `tempdir()` ? If so, that's the output:
```
> tempdir()
[1] "C:\\Users\\LENOVO\\AppData\\Local\\Temp\\Rtmp8yyovJ"
```

**Comment by rok-cesnovar** [comment]
Hm, a bit more to debug.

Can you run the following: 

```r
file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)

mod$print()

# names correspond to the data block in the Stan program
data_list <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500,
  validate_csv = FALSE
)
```

and if it succeeds, run and paste the output of:

```r
fit$output_files()
```

**Comment by acraevschi** [comment]
It succeded! Here is the output:
```
> fit$output_files()
[1] "C:/Users/LENOVO/AppData/Local/Temp/Rtmp8yyovJ/bernoulli-202201272033-1-4f7584.csv"
[2] "C:/Users/LENOVO/AppData/Local/Temp/Rtmp8yyovJ/bernoulli-202201272033-2-4f7584.csv"
[3] "C:/Users/LENOVO/AppData/Local/Temp/Rtmp8yyovJ/bernoulli-202201272033-3-4f7584.csv"
[4] "C:/Users/LENOVO/AppData/Local/Temp/Rtmp8yyovJ/bernoulli-202201272033-4-4f7584.csv"
> 
```

**Comment by rok-cesnovar** [comment]
And now if you run `fit$draws()` it will fail right?

**Comment by acraevschi** [comment]
Yes. Says again:

`Error in loadNamespace(x) : there is no package called 'data.table'`

**Comment by rok-cesnovar** [comment]
You need to install data.table again, and then run it again, but I am guessing it will fail again.

**Comment by acraevschi** [comment]
Unfortunately :( 
I have restarted the session after installation. 
```
Error in data.table::fread(cmd = fread_cmd, colClasses = "character",  : 
  File 'C:\Users\LENOVO\AppData\Local\Temp\RtmpoDe8x4\file29f43d9a39f7' does not exist or is non-readable. getwd()=='C:/Users/LENOVO/Documents'
```

I am only guessing, might there be some problem about Rtools and cmdstan being on one local drive and R itself being on the other one?

**Comment by acraevschi** [comment]
@rok-cesnovar I apologize for bothering you but maybe you know some kind of short term solution that might work for me? Maybe I can install somehow an earlier version of rstan to be able to work with it?

**Comment by rok-cesnovar** [comment]
I think this issue was resolved in https://github.com/stan-dev/cmdstanr/pull/630
Apologies for the lack of response, this slipped through my emails it seems.

I am going to close this, but please reopen it if you still experience issues. Please make sure you are using the latest version of CmdStanR by running:

```
remotes::install_github("stan-dev/cmdstanr")
```

**Comment by acraevschi** [comment]
Sorry, was somewhat busy and couldn't try to reinstall it. I have tried just installing the new version of cmdstanr (everything else appears to be working) and it wouldn't run the models in brms or rethinking packages. Before I say that the update didn't help, maybe you have a recommendation on what I should reinstall to be more certain about it? 

Last time, I have reinstalled literally everything (starting with R and finishing up with clearing all the Paths in system variables) but somehow the error persisted.

**Comment by rok-cesnovar** [comment]
Start a fresh session and run `remotes::install_github("stan-dev/cmdstanr")`. Once that completes run:

```r
check_cmdstan_toolchain()
fit <- cmdstanr_example()
```

**Comment by acraevschi** [comment]
> library(cmdstanr)
This is cmdstanr version 0.5.2
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: C:/Users/LENOVO/Documents/.cmdstan/cmdstan-2.29.2
- CmdStan version: 2.29.2
> check_cmdstan_toolchain()
The C++ toolchain required for CmdStan is setup properly!
> fit <- cmdstanr_example()
Compiling Stan program...
Error in data.table::fread(cmd = fread_cmd, colClasses = "character",  : 
  File 'C:\Users\LENOVO\AppData\Local\Temp\RtmpUXIKkn\file1974327f706c' does not exist or is non-readable. getwd()=='C:/Users/LENOVO/Documents'
