### ISSUE TITLE
Timing metadata only returned for one chain?

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/cmdstanr#621]
**Describe the bug**
metadata() method returns timing information for only one MCMC chain

**To Reproduce**
```
fit_mcmc <- cmdstanr_example("logistic", method = "sample")
fit_mcmc$metadata()$time
```
returns
```
  chain_id warmup sampling total
1        1  0.022    0.079 0.101
```
whereas 
`fit_mcmc$time()`
returns
```
$total
[1] 3.784975

$chains
  chain_id warmup sampling total
1        1  0.022    0.079 0.101
2        2  0.030    0.110 0.140
3        3  0.027    0.099 0.126
4        4  0.031    0.111 0.142
```

**Expected behavior**

I expected that the `metadata()$time` would match the `time()$chains`, though I may not have read the doc closely enough to understand why they're different.

**Operating system**
mac os x 12.1

**CmdStanR version number**
 `0.4.0`

**Comment by rok-cesnovar** [comment]
> I expected that the metadata()$time would match the time()$chains, though I may not have read the doc closely enough to understand why they're different.

I agree. Thanks for spotting this Rob!

**Comment by rok-cesnovar** [comment]
Should be fixed on master now, a version bump is coming shortly.

**Comment by jgabry** [comment]
Thanks @rtrangucci (and @rok-cesnovar for fixing)!
