### ISSUE TITLE
More helpful message on how to handle deprecations

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#626]
With deprecated syntax, stanc3 in 2.29 prints out this warning:
```
Warning in '/tmp/RtmpfALmCi/model-1d8e6aeb78c2.stan', line 6, column 18: normal_log
    is deprecated and will be removed in Stan 2.32.0. Use normal_lpdf
    instead. This can be automatically changed using the canonicalize flag
    for stanc
```

As @avehtari mentioned, the suggestion could be more helpful. We can't change what stanc3 prints, nor can we have stanc3 spit out a helpful warning for all possible interfaces.

I think the best plan would be to:
 - add a vignette on how to address deprecations
 - catch if any stanc3 message mentions deprecations and print an R warning pointing to the online vignette

**Comment by rok-cesnovar** [comment]
A draft of this vignette is now available here: https://rok-cesnovar.github.io/cmdstanr/articles/deprecations.html

The corresponding PR is available here: https://github.com/stan-dev/cmdstanr/pull/644 Comments/suggestions are very welcome. 

Once that is merged I will include the URL in the warning message.

**Comment by jgabry** [comment]
I think this can be closed now, but if not feel free to reopen.
