### ISSUE TITLE
M1 mac need to download the correct arm64 application (Rstudio, vscode, etc.) for cmdstanr

### ISSUE THREAD

**Issue by spinkney** [stan-dev/cmdstanr#627]
This is perplexing to me. I can compile Stan models fine in Rstudio but when I try in visual studio code I get this error
```r
Compiling Stan program...
error: half args and returns was enabled in PCH file but is currently disabled
error: PCH file was compiled for the target 'arm64-apple-macosx12.0.0' but the current translation unit is being compiled for target 'x86_64-apple-macosx12.0.0'

2 errors generated.

make: *** [/var/folders/22/bpr3xfb5343gnd0jqvhwk2380000gn/T/Rtmp9HZXxi/model-6dca7c937013] Error 1

Error: An error occured during compilation! See the message above for more information.
In addition: Warning messages:
1: In readLines(stan_file) :
  incomplete final line found on 'unidentified_multiply.stan'
2: CmdStan's precompiled header (PCH) files may need to be rebuilt.
If your model failed to compile please run rebuild_cmdstan().
If the issue persists please open a bug report. 
```
I checked the R version that is running in vscode terminal and it's the arm one
```r
r$> R.Version()                                                                                                                                                  
$platform
[1] "aarch64-apple-darwin20"

$arch
[1] "aarch64"

$os
[1] "darwin20"

$system
[1] "aarch64, darwin20"

$status
[1] ""

$major
[1] "4"

$minor
[1] "1.2"

$year
[1] "2021"

$month
[1] "11"

$day
[1] "01"

$`svn rev`
[1] "81115"

$language
[1] "R"

$version.string
[1] "R version 4.1.2 (2021-11-01)"

$nickname
[1] "Bird Hippie"
```
The cmdstanr version is the dev version (as of 5 mins ago) and cmdstan 2.29.0
```r
r$> library(cmdstanr)                                                                                                                                            
This is cmdstanr version 0.4.0.9001
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: /Users/sean/.cmdstan/cmdstan-2.29.0
- CmdStan version: 2.29.0
```
Why is cmdstanr in vscode trying to link to x86?

**Comment by rok-cesnovar** [comment]
Can you set options(“cmdstanr_verbose”=TRUE) and recompile the model in both and paste the commands or find a difference?

**Comment by spinkney** [comment]
Ok I figured it out...god this m1 stuff. When you download vscode you must download the arm64 version
![Screen Shot 2022-02-17 at 4 16 55 PM](https://user-images.githubusercontent.com/23704057/154572231-7f4c108e-5ee0-4ad0-9845-f4fa32babb04.png)

**Comment by spinkney** [comment]
Is there a place we should put this stuff? Like note to M1 users

* Here's an issue with Julia https://discourse.mc-stan.org/t/errors-during-compile/20663/15?u=spinkney
* Probably need Rstudio arm64
* vscode arm64
* etc. To note that they should run the app version that is compatible with their R version

**Comment by rok-cesnovar** [comment]
On the blog would be my first instinct and in the CmdStan docs as well. 

Getting my M1 Mac soon, hope I fibd a way to automatically warn users as well.

**Comment by spinkney** [comment]
I'll close this, should I open a warning issue?

**Comment by rok-cesnovar** [comment]
Lets just leave this one. Maybe change the title only.

**Comment by idontgetoutmuch** [comment]
This seems related: https://github.com/stan-dev/cmdstanr/issues/636
