### ISSUE TITLE
Typo in documentation example of install_cmdstan()

### ISSUE THREAD

**Issue by sims1253** [stan-dev/cmdstanr#631]
The Example in the documentation gives the following `cpp_options`:
```
cpp_options <- list(
  "CXX" = "clang++",
  "CXXFLAGS+= -march-native",
  PRECOMPILED_HEADERS = TRUE
)
```
However, using that throws an error about `-march-native` being unknown. It should probably be `-march=native` as it works with that.

**CmdStanR version number**
0.4.0.9001

**Comment by rok-cesnovar** [comment]
Thanks! 

Added a fix for this in #629
