### ISSUE TITLE
$loo() not working in v0.5.0 on fits from v0.4.0

### ISSUE THREAD

**Issue by cbdavis33** [stan-dev/cmdstanr#642]
**Describe the bug**
I have CmdStanMCMC objects fit with cmdstanr v0.4.0. I could do fit$loo() with no problems. After updating to cmdstanr v0.5.0, fit$loo() gives the error 

'Error in suggest_package("loo") : 
  could not find function "suggest_package"'

Refitting the same model with no changes in v0.5.0 and then doing fit$loo() resolves the issue, but it would be nice not to have to re-fit everything.

**To Reproduce**
Take any CmdStanMCMC object with a log_lik variable fit with cmdstanr v0.4.0, then execute $loo() in cmdstanr v0.5.0.

**Expected behavior**
I would expect the usual named list to be returned.

**Operating system**
Windows 10

**CmdStanR version number**
currently 0.5.0, previously 0.4.0 

**Additional context**

**Comment by rok-cesnovar** [comment]
Hi @cbdavis33 and thanks for the bug report.

Unfortunately, we cannot support this, as the `$loo()` function changed between these two versions (in minor detail, but still) and it's difficult to keep internal backwards compatibility.

There is a somewhat simple fix for this, which is running: 
```
suggest_package <- cmdstanr:::require_suggested_package
```
and then $loo() should work on your 0.4.0 fit objects.

The other solution is to just call loo on your own using the obtained draws.

**Comment by cbdavis33** [comment]
OK, good enough for me. Thank you
