### ISSUE TITLE
show_messages=FALSE is showing messages

### ISSUE THREAD

**Issue by avehtari** [stan-dev/cmdstanr#646]
**Describe the bug**

There are two output related options
```
 refresh: (non-negative integer) The number of iterations between
          printed screen updates. If ‘refresh = 0’, only error messages
          will be printed.

show_messages: (logical) When ‘TRUE’ (the default), prints all
          informational messages, for example rejection of the current
          proposal. Disable if you wish to silence these messages, but
          this is not usually recommended unless you are very confident
          that the model is correct up to numerical error. If the
          messages are silenced then the ‘$output()’ method of the
          resulting fit object can be used to display the silenced
          messages.
```

Based on the documentation I would expect that setting `refresh=0` and `show_messages=FALSE` would get rid of messages, but I still see
```
Running MCMC with 4 parallel chains...
Chain 1 finished in 34.4 seconds.
Chain 2 finished in 34.6 seconds.
Chain 3 finished in 34.4 seconds.
Chain 4 finished in 34.6 seconds.

Both chains finished successfully.
Mean chain execution time: 34.5 seconds.
Total execution time: 34.8 seconds.
```

**Expected behavior**

Allow option to disable all output.

**CmdStanR version number**
The latest githuib version

**Additional context**
When running simulations, it is really annoying to see all the output, and adding sink-wrappers makes the code more complicated and ugly in notebooks. Just let the user choose what out is seen,

**Comment by jgabry** [comment]
Closing this since `show_messages=FALSE` now suppresses these extra lines of output.
