### ISSUE TITLE
R toolchain bug

### ISSUE THREAD

**Issue by pwarncke77** [stan-dev/cmdstanr#649]
**Describe the bug**
cmdstanr::install_cmdstan()
Error: 
Rtools42 installation found but the toolchain was not installed.
Run check_cmdstan_toolchain(fix = TRUE) to fix the issue.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A description of what you expected to happen.

**Operating system**
Your operating system (e.g. mac os x 10.15, windows 10, etc.)

**CmdStanR version number**
Your CmdStanR version number (e.g. from `packageVersion("cmdstanr")`). 

**Additional context**

**Comment by rok-cesnovar** [comment]
Hi @pwarncke77, can you specify what is the problem you are trying to solve?

Based on the error message you got, you need to run 
```
cmdstanr::check_cmdstan_toolchain(fix = TRUE)
```

**Comment by rok-cesnovar** [comment]
Closing this. Please re-open if needed.

**Comment by cethomas24** [comment]
Hello, 

I receive the same error message. When I run cmdstanr::check_cmdstan_toolchain(fix = TRUE), I receive another error message. "No write permissions in the RTools folder. This might prevent installing the toolchain. Consider changing permissions or reinstalling RTools in a different folder." I've tried reinstalling RTools to my C drive, but the error persists. 
![image](https://github.com/stan-dev/cmdstanr/assets/172987484/33f06abe-4c42-420e-af18-c6687afab589)
