### ISSUE TITLE
fit$time()

### ISSUE THREAD

**Issue by StanHKdc** [stan-dev/cmdstanr#655]
Hello @rok-cesnovar @jgabry , 

The problem encountered is to retrieve fit$time() when among the n chains launched, one failed to finish. 
When we try to retrieve the fit$time(), an error appears saying that **there are some incomplete lines in the data.frame** created in the time function (as shown in the following image). 

![image](https://user-images.githubusercontent.com/66433669/169364824-2aeef4f6-7e75-4b26-8263-59062a204282.png)

In this image, I launched 8 chains with a challenging warm-up phase and one failed to find an initialisation so I have only 7 chains terminated, which I want to retrieve the time. 

Thank you for your help,

Stanislas

**Comment by rok-cesnovar** [comment]
Hey @StanHKdc,

sorry this slipped through and no one responded. I agree that this is a bug and I should be able to fix it shortly. Thanks for the report!
