### ISSUE TITLE
Error in check_cmdstan_toolchain(fix = TRUE, quiet = TRUE) 

### ISSUE THREAD

**Issue by NoaShen** [stan-dev/cmdstanr#662]
**Describe the bug**
I get an error in check_cmdstan_toolchain(fix = TRUE, quiet = TRUE):

The error: 
Installation of the toolchain failed. Try reinstalling RTools and trying again.
If the issue persists, open a bug report at https://github.com/stan-dev/cmdstanr.

**To Reproduce**
Its happens after  I running: 
1. install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos"))):

Installing package into ‘C:/Users/User/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://mc-stan.org/r-packages/bin/windows/contrib/4.1/cmdstanr_0.5.2.zip'
Content type 'application/zip' length 1243519 bytes (1.2 MB)
downloaded 1.2 MB

2. library(cmdstanr) 

This is cmdstanr version 0.5.2
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: C:/Users/User/Documents/.cmdstan/cmdstan-2.29.2
- CmdStan version: 2.29.2

**Expected behavior**
Work with cmdstan

**Operating system**
Windows 10 Enterprise

**CmdStanR version number**
‘0.5.2’

**Additional context**

**Comment by rok-cesnovar** [comment]
Hi @NoaShen, can you try installing the branch:
```r
remotes::install_github("stan-dev/cmdstanr@fix-toolchain-checks-windows")
```

and let me know if it fixes the issue?
