### ISSUE TITLE
The $format() method is not available. 

### ISSUE THREAD

**Issue by acastroaraujo** [stan-dev/cmdstanr#673]
The [format method](https://mc-stan.org/cmdstanr/reference/model-method-format.html) is not available in my version of CmdStanR (0.4.0).

For example, using the example from the website:

```
file <- write_stan_file("
data {
  int N;
  int y[N];
}
parameters {
  real                     lambda;
}
model {
  target +=
 poisson_log(y | lambda);
}
")
mod <- cmdstan_model(file, compile = FALSE)
mod$format(canonicalize = TRUE)
```
Produces this error:

```
Error: attempt to apply non-function
```

**Comment by rok-cesnovar** [comment]
For the format() method you need to have the 0.5.0 version or newer. Get that by running:

```r
install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

or 

```r
remotes::install_github("stan-dev/cdmstanr")
```

**Comment by rok-cesnovar** [comment]
No apologies are necessary! Glad it fixed the problem.
