### ISSUE TITLE
Organizing tests

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#68]
@rok-cesnovar @jgabry @mitzimorris 

A discussion of how to organize tests came up in this pull request: https://github.com/stan-dev/cmdstanr/pull/64

I don't like working with giant, monolithic test files cause it's hard to keep oriented in them and they run slow.

This was happening in that pull req. so I broke out some tests into their own files: https://github.com/stan-dev/cmdstanr/blob/761a70e6eef455443cdb5c11f71697847801f91f/tests/testthat/test-metric.R

The issue with this is the number of tests are gonna explode so I guess we gotta work out naming and how exactly broken up tests need to be.

How about we organize test filenames by issue number? So something like tests-issue-63-metric.R should be where I put the tests. So you kinda vaguely know what's in the file, and when the tests break you can do a little sleuthing and see what that issue is about.

And if the tests cover multiple issues we could include multiple numbers tests-issue-63-64-whatever.R.

I don't really want to try to make the tests super indexed like they are in the math library.

**Comment by jgabry** [comment]
I agree that we should have a strategy for organizing the tests better. My only concern with this particular proposal is that having a separate file for every issue is going to result in a ton of files. Having all tests of the metric file in a single file like you had in the PR seems reasonable to me, and we could do the same for the other arguments. In other words we could have 

```
test-sample-metric.R
test-sample-init.R
etc.
```

To keep the issue information we could add a comment in specific tests linking to the issue and/or a comment when closing the issue linking to the test. 

What do you all think?

**Comment by rok-cesnovar** [comment]
I am going to close this one, I think the structure of tests files is fine for now.
