### ISSUE TITLE
Failure to install rtools toolchain correctly

### ISSUE THREAD

**Issue by salrior** [stan-dev/cmdstanr#707]
I am attempting to get the C++ toolchain set up for running cmdstanr and have downloaded and installed rtools42.

When I check the toolchain I receive this message:
> check_cmdstan_toolchain()
Error: 
Rtools42 installation found but the toolchain was not installed.
Run cmdstanr::check_cmdstan_toolchain(fix = TRUE) to fix the issue.

When I then run the tookchain fix, I receive this message:
> check_cmdstan_toolchain(fix = TRUE)
Installing mingw32-make and g++ with Rtools42.
Error: 
Installation of the toolchain failed. Try reinstalling RTools and trying again.
If the issue persists, open a bug report at https://github.com/stan-dev/cmdstanr.

I've reinstalled RTools with the same result.

I am on Windows 10.
I am using a university laptop with restricted permissions, so have needed administrators to execute the rtools exe.
I'm reinstalled the latest version of R (4.2.1) and R Studio (Build 576) 
Be glad of any help on this, thank you!

**Comment by rok-cesnovar** [comment]
Can you set

```options("cmdstanr_verbose" = TRUE)``

and run the checks again and paste the output.

Also, please try out the development version by running:

```
# install.packages("remotes")
remotes::install_github("stan-dev/cmdstanr") 
```

**Comment by salrior** [comment]
Hi rok-cesnovar and thank you for your reply. I've tried out the development version and set the verbose option to TRUE.

After the initial output:

> check_cmdstan_toolchain(fix = TRUE)
Running "g++" --version
g++ (GCC) 10.4.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Installing mingw32-make and g++ with Rtools42.
Running pacman -Sy mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-gcc --noconfirm
:: Synchronizing package databases...
 mingw32 downloading...
 mingw64 downloading...
 ucrt64 downloading...
 clang32 downloading...
 clang64 downloading...
 msys downloading...

I then recceive hundreds of messages of the following kind:

warning: warning given when extracting /ucrt64/include/c++/12.2.0/bits/exception_defines.h (Failed to create dir '/ucrt64/include/c++')
warning: warning given when extracting /ucrt64/include/c++/12.2.0/bits/exception_ptr.h (Failed to create dir '/ucrt64/include/c++')
warning: warning given when extracting /ucrt64/include/c++/12.2.0/bits/forward_list.h (Failed to create dir '/ucrt64/include/c++')
warning: warning given when extracting /ucrt64/include/c++/12.2.0/bits/forward_list.tcc (Failed to create dir '/ucrt64/include/c++')
warning: warning given when extracting /ucrt64/include/c++/12.2.0/bits/fs_dir.h (Failed to create dir '/ucrt64/include/c++')
warning: warning given when extracting /ucrt64/include/c++/12.2.0/bits/fs_fwd.h (Failed to create dir '/ucrt64/include/c++')
warning: warning given when extracting /ucrt64/include/c++/12.2.0/bits/fs_ops.h (Failed to create dir '/ucrt64/include/c++')

warning: warning given when extracting /ucrt64/share/man/man1/gcov.1.gz (Failed to create dir '/ucrt64/share/man')
warning: warning given when extracting /ucrt64/share/man/man1/gfdl.7.gz (Failed to create dir '/ucrt64/share/man')
warning: warning given when extracting /ucrt64/share/man/man1/gpl.7.gz (Failed to create dir '/ucrt64/share/man')

**Comment by rok-cesnovar** [comment]
Hi, I was finally able to reproduce this issue this week on a Windows machine. This is unfortunately a permission issue. It seems that you are unable to update Rtools if it was installed using administrator permission. 

Maybe try installing Rtools in your user folder? In any case, this is unfortunately not an issue that can be fixed on the cmdstanr side, so will close this issue.
