### ISSUE TITLE
error in the documentation of  model-method-format

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/cmdstanr#721]
**Describe the bug**
There is an error in the example of the documentation:
https://mc-stan.org/cmdstanr/reference/model-method-format.html

The use of `poisson_log` is throwing an error, and it's not formatting anthing:

```
Only functions with names ending in _lpdf, _lupdf, _lpmf, _lupmf, _cdf, _lcdf, _lccdf can make use of conditional notation.
#> Error: Syntax error found! See the message above for more information.
```

I'm not sure if the problem is with poisson_log or with the method, but I guess you should be aware.
(I never used the method or poission_log)

**Comment by rok-cesnovar** [comment]
Yeah, it should be poisson_log_lpdf(). Thanks for pointing this out.
