### ISSUE TITLE
How to uninstall cmdstan?

### ISSUE THREAD

**Issue by beew** [stan-dev/cmdstanr#744]
**Describe the issue**
I have run cmdstanr::install_cmdstan() 
but cmdstan is installed in /root instead of /usr as I expected

I am sure this is not correct and I want to remove it and start again in my home 

But I can't find any documentation on how to remove an existing installation  of cmdstan

**CmdStanR version number**
cmdstanr 0.5.3
OS is Ubuntu 22.04

**Comment by jgabry** [comment]
Assuming you have access to root (if you don't I'm guessing you couldn't have installed it there?), you can just remove/delete the `.cmdstan` folder created by the installation process. You don't need to run any special uninstaller or anything like that.

**Comment by andrjohns** [comment]
You can also do this in R if you'd prefer by running:
```r
unlink(cmdstanr::cmdstan_default_install_path(), recursive=TRUE)
```

But given that it was installed in your root directory, I'd recommend double-checking that the output of `cmdstanr::cmdstan_default_install_path()` is the path that you expect - you don't want to be accidentally deleting folders from your root directory!
