### ISSUE TITLE
Cannot compile stan code on apple M1

### ISSUE THREAD

**Issue by schae211** [stan-dev/cmdstanr#750]
**Describe the bug**
The installation of Cmdstan seems to work fine (I just get some warnings which are related to sprintf depracation). The toolchains seems to be OK. I used macrtools to set everything up.

But when I want to compile the example stan program
```
file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)
```
I get 14 errors. I think all of them are related to "no matching function calls".
```
/opt/homebrew/Cellar/llvm/16.0.0/bin/../include/c++/v1/complex:640:23: error: no matching function for call to '__constexpr_copysign'
                __c = std::__constexpr_copysign(_Tp(0), __c);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
```

```
/opt/homebrew/Cellar/llvm/16.0.0/bin/../include/c++/v1/complex:638:19: error: no matching function for call to '__constexpr_copysign'
            __b = std::__constexpr_copysign(std::__constexpr_isinf(__b) ? _Tp(1) : _Tp(0), __b);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
```
I have tried several times to remove cmdstanr, and cmdstan and reinstall, but I still does not work.

Could it be related to the compiler version: "/opt/homebrew/Cellar/llvm/16.0.0"?

**Operating system**
mac OS Ventura 13.1

**CmdStanR version number**
CmdStanR: 0.5.3, CmdStan: 2.31.0

**Comment by andrjohns** [comment]
Unfortunately using custom toolchains through homebrew can often lead to odd configurations and compiler errors, so we only officially support the standard Mac toolchain (from the xcode command line tools)

**Comment by schae211** [comment]
And how could I specify to use standard Mac toolchain? I have the xcode tools installed.
