### ISSUE TITLE
Output handling with failed chains

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#76]
From @bbbales2 in #61 :

- output_files gives us all the output files for things that work and I like that. But it would still be good to access files of chains that failed for debugging. Can we add an included_failed = FALSE argument to output_files and diagnostic_files? Probably should add that flag with save_output_files and save_diagnostic_files as well -- though in this cause I kinda feel like the default should be the opposite.

- diagnostic_files returns files from all chains, whether they succeeded or failed.

By default the output files and draws, etc. should be returned only for chains that succeeded. With include_failed = TRUE we would also include available info for failed chains. Take special care for cases where chains finish extremely early and there might be no info to show.

**Comment by jgabry** [comment]
Sounds good to me!

**Comment by rok-cesnovar** [comment]
@bbbales2 do you maybe have a model that runs for some time and then fails? I would need such a model to test this and am failing to come up with a tests model. The one we currently have for failed chains either finishes or fails immediately. Thanks!

**Comment by bbbales2** [comment]
Check this one: https://github.com/stan-dev/cmdstanr/blob/master/tests/testthat/resources/stan/chain_fails.stan

It takes one argument which is the probability of failure (and it'll only fail at runtime).

**Comment by rok-cesnovar** [comment]
I checked that one yeah and when it failed I found no samples in the csv file.

**Comment by rok-cesnovar** [comment]
I am actually not sure now if cmdstan actually outputs samples to the csv if chains fail?

**Comment by bbbales2** [comment]
If you get one that blows up halfway through, you'll get half the output. But I think this issue doesn't need that. The empty files can be annoying if you have scripts that expect cmdstan output.

**Comment by jgabry** [comment]
@rok-cesnovar @bbbales2 Is this still an issue or was this addressed by one of the recent or semi-recent PRs?

**Comment by rok-cesnovar** [comment]
Still an issue. I plan on tackling this after the fix to #131 and the new compile flags system.

**Comment by jgabry** [comment]
Ok thanks!

**Comment by rok-cesnovar** [comment]
@bbbales2 Do you have a model that fails half way through or have a trick up you sleeve for forcing it? It would really help when adding this. The model above either fails immediatelly or runs fine.
I am going to tackle this tomorrow or on Thursday.

**Comment by bbbales2** [comment]
Oof, nah. I think those failures come from somebody killing a process while it's running.

I could see how to generate some partial test files to verify that the read csv functionality worked or whatnot, but I don't know how to get cmdstanr to blow up in this way.

The goal here was to optionally return either all the outputs or only the outputs from chains that completed without error.

Now that I read this issue again I think we should by default include the failed chains and then add a flag to filter them out if necessary lol.

But I think if this worked and was tested for only controlled failures at the start or end that's fine.

**Comment by rok-cesnovar** [comment]
Reviving this issue again now that I tried again and have a simple-ish way of reproducing. Rundown of thoughts and what I learned when turning on including all chains (regardless of failed or not): 
- `fit$draws()`, `fit$sampler_diagnostics()`, `fit$summary()` etc. (basically anything that requires reading in samples) fails if we include failed chains and we would need to refactor the CSV read and how we form the samples array. We cant return them in a 3D array (parameter, chain, iteration) as we cant return a ragged samples array (a failed chain will always have a different number of rows/iterations).
- `fit$cmdstan_diagnose()` and `fit$cmdstan_summary()` work fine (those Cmdstan executables just read in samples, dont really care how many of them are in each separate CSV)
- `fit$save_latent_dynamics_files()` and `fit$save_output_files()` works fine
- `read_sample_csv(fit$output_files()[2])` works fine (chain 2 failed)

Options: 
- A: don't read in samples from failed chains for `$draws()`, `$summary()` and such. Warn users of failed chains and that they can use `read_sample_csv`to read samples form failed chains. `output_files()` returns all csv file paths, as does `latent_dynamics_files()`. Saving the files also works for all chains.

- B: refactor reading in samples and return a 2D samples array (parameter, iteration) where chain 2 iterations follow chain 1 iterations. This would mean that everything could work in theory.

**Comment by bbbales2** [comment]
> A: don't read in samples from failed chains for $draws(), $summary() and such. Warn users of failed chains

I like this better.

I suspect many failed chains never initialized, and so there isn't much interesting to be learned from the output (though the error messages are useful).

**Comment by rok-cesnovar** [comment]
I like A much better also. Will proceed with that option.

**Comment by jgabry** [comment]
That sounds good to me too, thanks! Will review the PR as soon as possible.
