### ISSUE TITLE
How do you look at docs for R6 class methods?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/cmdstanr#78]
I tried `CmdStanModel?Sample` with no dice. Srry never worked with R6 before

**Comment by jgabry** [comment]
Good question. Two options for now:

1) `?CmdStanModel`, then click on `sample` hyperlink in the table listing the methods 

or directly via 

2) `?"model-method-sample"`

I don't think we could get the syntax `CmdStanModel?Sample` (with the ? in the middle) to work but we can change `?"model-method-sample"` or add more aliases if you have suggestions.

**Comment by SteveBronder** [comment]
Ayyyy

https://twitter.com/hadleywickham/status/1194338595202576385?s=19

**Comment by jgabry** [comment]
Awesome I’ve been waiting for that for a while! Will update.

**Comment by jgabry** [comment]
Closing since we now have #81 open for using the new roxygen2 support for R6. I'll take care of it ASAP. Thanks @SteveBronder!
