### ISSUE TITLE
save_object() for variational fit loses return code

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/cmdstanr#780]
**Describe the bug**
After running a variational estimation, saving the fit with save_object(), and reading it back with readRDS(), return_codes() returns NA instead of the return code from estimation.

**To Reproduce**

```r
    file <- file.path(cmdstanr::cmdstan_path(), "examples/bernoulli/bernoulli.stan")
    mod <- cmdstanr::cmdstan_model(file)
    stan_data <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
    fit_vb <- mod$variational(data = stan_data, seed = 123)
    fit_vb$return_codes() # returns 0 as expected
    fit_vb$save_object('~/Tmp/vbexample.rds')
    fit_vb1 <- readRDS('~/Tmp/vbexample.rds')
    fit_vb1$return_codes() # returns NA
```

**Expected behavior**
The call `fit_vb1$return_codes()` should also return 0.

**Operating system**
Mac OS Ventura 13.4

**CmdStanR version number**
0.5.3.

**Additional context**
R version 4.2.2.

**Comment by jgabry** [comment]
Thanks for reporting this. It would indeed be good to get the right return
codes after loading the saved model.

**Comment by jgabry** [comment]
@ksvanhorn I have a PR open that fixes this: https://github.com/stan-dev/cmdstanr/pull/798 

Would you mind trying it out and making sure it resolves the issue you were having?
