### ISSUE TITLE
Data file with wrong extension silently treated as no data file provided

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/cmdstanr#782]
**Describe the bug**
If the data argument to `model$sample()` is a file path ending in '.csv' then, even if the file contains valid JSON with all the variables in the data section of the model defined, it tells you that the variables are not defined.

**To Reproduce**
```
library(cmdstanr)
file <- file.path(cmdstan_path(), "examples/bernoulli/bernoulli.stan")
mod <- cmdstan_model(file)
stan_data <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
jsonlite::write_json(stan_data, '~/Tmp/stan_data.json', auto_unbox=TRUE)
fit1 <- mod$sample(data = '~/Tmp/stan_data.json') # This works
file.copy('~/Tmp/stan_data.json', '~/Tmp/stan_data.csv')
fit2 <- mod$sample(data = '~/Tmp/stan_data.csv') # This fails with "variable does not exist"
```

**Expected behavior**
It either shouldn't matter what the extension is, or it should fail with an error saying that it expects a file path with a '.json' extension.

**Operating system**
macOS 13.4 Ventura

**CmdStanR version number**
0.5.3

**Additional context**
R version 4.2.2

**Comment by andrjohns** [comment]
This actually occurs in `cmdstan` itself, as it uses the file extension to decide how to parse the file - `cmdstan` doesn't have the functionality to inspect a file and determine the format prior to attempting to parse

**Comment by andrjohns** [comment]
I'm going to close this as expected behaviour on the `cmdstanr` side, but if you want the ability to pass data where the file format doesn't match the extension then I'd recommend opening an issue on the `cmdstan` github
