### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#792]
@rok-cesnovar @andrjohns I think we're due for another release of cmdstanr that includes the new stuff like exposing functions, constraining variables, etc. Thoughts? Can you remind me if there are still things to work out with those methods or are they ready for primetime?

**Comment by jgabry** [comment]
There is some missing documentation that I've started adding in the `next-release` branch (e.g., `expose_functions` now gets it's own doc page). I need to check on the other new methods still.

**Comment by rok-cesnovar** [comment]
I think we should do another release. I wanted to start work on it, but I honestly forgot how to update the webpage 😊.
I think the functions are ready to be released, they have been around long enough at this point. There are going to be minor things that will pop up, but doing a release and publicizing them will only help improving them.

**Comment by jgabry** [comment]
> I think we should do another release. I wanted to start work on it, but I honestly forgot how to update the webpage 😊.

No worries, I can do it! We're missing some documentation for some of the new stuff, but I'll go through it and see what we need.

**Comment by jgabry** [comment]
@rok-cesnovar When you have a chance can you regenerate the OpenCL vignette and push the generated html to the `next-release` branch? I think you need to do this:
  
```r
withr::with_envvar(c("NOT_CRAN" = "true", "CMDSTANR_OPENCL_TESTS" = "true"), {
  pkgdown::build_article("articles-online-only/opencl")
})
```
