### ISSUE TITLE
Implement fixed_param version of sample method

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#8]
Implement fixed_param version of sample method

**Comment by dickoa** [comment]
Hi @jgabry 
I hope all is good I wanted to know if this feature is still something that will be added to `cmdstanr`.
Thanks again

**Comment by rok-cesnovar** [comment]
Hi @dickoa, 

fixed_param is in the works and will hopefully be done for the beta release.

**Comment by dickoa** [comment]
Hi @rok-cesnovar 
Thanks a lot and great work on this awesome package!
