### ISSUE TITLE
user_header will not enter the $cpp_options() if the model is not recompiled

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/cmdstanr#812]
**Describe the bug**
The contents of `CmdStanModel$cpp_options()` depend on whether a user header was passed via tha `user_header` argument or explicitly via tha `cpp_options` argument

**To Reproduce**
```r
# Make sure target file does not exist
file.remove("gp.exe")
# Compile 
m <- cmdstan_model("gp.stan", stanc_options = list("allow-undefined"), user_header = here::here("gp.hpp"))
m$cpp_options() #Includes USER_HEADER

# No change, just load the model
m <- cmdstan_model("gp.stan", stanc_options = list("allow-undefined"), user_header = here::here("gp.hpp"))
m$cpp_options() #Does not include USER_HEADER

m <- cmdstan_model("gp.stan", stanc_options = list("allow-undefined"), user_header = here::here("gp.hpp"), force_recompile = TRUE)
m$cpp_options() #Includes USER_HEADER


# No change, just load the model
m <- cmdstan_model("gp.stan", stanc_options = list("allow-undefined"),  cpp_options = list(USER_HEADER = here::here("gp.hpp")))
m$cpp_options() #Includes USER_HEADER
```

**Expected behavior**
I'd expect `USER_HEADER` to be a part of `cpp_options()` in all cases

**Operating system**
Windows 10

**CmdStanR version number**
0.6.0

**Comment by martinmodrak** [comment]
Happy to prepare a PR if the team agrees that I am right about the desired behaviour.

**Comment by jgabry** [comment]
I think you're right, that inconsistency does seem like a bug. Thanks for offering to make a PR. That sounds good to me unless Rok or Andrew knows of a reason why we should keep it this way.

**Comment by rok-cesnovar** [comment]
Yeah, this sounds like a good idea!
