### ISSUE TITLE
output duplicated when running diagnose

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/cmdstanr#826]
**Describe the bug**
In the file `R/run.R`, near the end of the function `.run_diagnose`, are these lines, which get called if the diagnose operation fails:

```
if (file.exists(stdout_file)) {
      cat(readLines(stdout_file), sep = "\n")
    }
    if (file.exists(stdout_file)) {
      cat(readLines(stdout_file), sep = "\n")
    }
```

**Expected behavior**
There's no point in printing the output twice, so I suspect that one of those is supposed to be `stderrr`.

**Other notes**
I encountered this because `model$diagnose(data=data_file)` failed for me, and most of the output scrolled off the top of my console window, making it inaccessible. In particular, the initial part of the output, with all the information about the program options and the column headings, is not visible. I had to run the debugger and step through execution to get the info I wanted. I think there ought to be a better way of presenting this information to the user.

It's worth noting the the columns in the output aren't documented anywhere that I can find. I can guess what some of them are, but what are "param idx" and "value"?

One other note: it seems that the diagnose operation failed with a return code of 1, but none of the information I was able to gather told me why the program failed. I'm guessing that maybe an exception got thrown while evaluating an extremely large gradient, but it would be useful for the program to say more instead of just returning an error code of 1.

**Comment by jgabry** [comment]
Yeah I think one of those `stdout_file`s should be `stderr_file`. Regarding the lack of documentation of the columns and the lack of additional information, I agree but I think those are CmdStan issues, so I'll open a separate issue there and close this one once we fix the duplicate `stdout_file`.
