### ISSUE TITLE
Extracting gradient of log posterior and unconstrained parameters 

### ISSUE THREAD

**Issue by simonrmaskell** [stan-dev/cmdstanr#827]
We're keen to enable Stan's users to capitalise on control variates. To make that possible (in R), one route would be to add functionality to posterior and to CmdStanR (which I now understand to use posterior to generate the summaries that control variates could sensibly augment). See here: https://github.com/stan-dev/posterior/issues/273.

To make that possible, we'll need to get the gradient of the log posterior with respect to the unconstrained parameters and the unconstrained parameters themselves out of CmdStanR. We're happy to expend effort to make this happen, but would welcome perspectives on how this might best be achieved.

**Comment by jgabry** [comment]
In the latest version of cmdstanr @andrjohns added methods `grad_log_prob`, `unconstrain_variables`, and `unconstrain_draws`. Does that give you what you need? 

* https://mc-stan.org/cmdstanr/reference/fit-method-init_model_methods.html
* https://mc-stan.org/cmdstanr/reference/fit-method-grad_log_prob.html

**Comment by simonrmaskell** [comment]
Awesome. Yes, I think so. Thank you @jgabry and @andrjohns !!
