### ISSUE TITLE
Diagnose method missing from help page for CmdStanModel objects

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/cmdstanr#829]
**Describe the bug**
Although there is a help page for the `diagnose` method of `CmdStanModel` objects, this method is nowhere mentioned in the `CmdStanModel objects` help page itself.

**Comment by jgabry** [comment]
Thanks, I hadn't noticed that. We'll add that method to the `CmdStanModel` page. Also, thanks for all the bug reports recently, very helpful!
