### ISSUE TITLE
`wsl_installed()` is not deterministic

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/cmdstanr#838]
**Describe the bug**
On my Windows machine (with WSLv2 installed), when running from Windows shell, `wsl_installed()` will sometimes return `TRUE` and sometimes return `FALSE`

**To Reproduce**
Probably hard to reproduce on all machines, but:

```r
for(i in 1:10) { print(cmdstanr:::wsl_installed())}
```

gives stuff like:
```
[1] FALSE
[1] FALSE
[1] FALSE
[1] FALSE
[1] FALSE
[1] FALSE
[1] TRUE
[1] TRUE
[1] TRUE
[1] TRUE
```

**Expected behavior**
WSL is reliably detected as installed.

**Operating system**
Windows 10

**CmdStanR version number**
0.6.0

**Additional context**
Presumably, this is because the `Sleep(1)` call is sometimes not enough to let `wsl.exe` complete.

**Comment by jgabry** [comment]
Good catch!
