### ISSUE TITLE
expose_functions errors after update to 2.33

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#845]
**Describe the bug**

@andrjohns I can't expose stan functions anymore after installing 2.33. Have you run into this? Or any ideas what's going on? 

**To Reproduce**

The example at `?expose_functions` now errors when it didn't before: 

```r
stan_file <- write_stan_file(
  "
 functions {
   real a_plus_b(real a, real b) {
     return a + b;
   }
 }
 parameters {
   real x;
 }
 model {
   x ~ std_normal();
 }
 "
)
mod <- cmdstan_model(stan_file)
mod$expose_functions()
```

```
Compiling standalone functions...
Error in 1:first_decl : NA/NaN argument
```

**Expected behavior**
No error

**Operating system**

Mac Big Sur

**CmdStanR version number**

Current master branch (v 0.6.1.9000)

**Comment by jgabry** [comment]
The error seems to be coming from `get_plain_rtn()` in `utils.R`. Is that because something in the generated c++ code changed that cmdstanr was assuming wouldn't change between cmdstan versions?

**Comment by jgabry** [comment]
Not sure why but finding the first function declaration returns NA now: 

```r
# this now returns NA_integer_
first_decl <- grep(paste0(fun_name,"\\("), model_lines)[1]
```

**Comment by jgabry** [comment]
we should probably run cmdstanr unit tests against the release candidate version of cmdstan going forward so we can catch this sooner

**Comment by WardBrian** [comment]
I'm guessing this is because of https://github.com/stan-dev/stanc3/pull/1313 which @andrjohns requested to make this feature easier for cmdstanr

We do run the cmdstanr unit tests during the release candidates, it's not always clear if the failures are significant - this time a few looked like they were due to the deprecations

**Comment by jgabry** [comment]
Yeah that looks like it would cause the issue I'm seeing. Thankfully this doesn't affect running any models. But it does cause a bunch of unit tests to fail that aren't just due to the deprecations: 

https://github.com/stan-dev/cmdstanr/actions/runs/6114306271/job/16595596153?pr=843#step:13:3398

**Comment by jgabry** [comment]
Closing now that #843 was merged
