### ISSUE TITLE
Support R tools 4.3

### ISSUE THREAD

**Issue by Newtype07** [stan-dev/cmdstanr#846]
I want to update `cmdstan` version using `install_cmdstan()`, but it requires R tools 4.2, R tools 4.3 has been released for a long time, and stan programs can be compiled by R tools 4.3, maybe it is the time to support R tools 4.3 for compiling `cmdstan` itself.

**Comment by andrjohns** [comment]
It already is supported, what version of R and `cmdstanr` are you using?

**Comment by jgabry** [comment]
Closing since Rtools 4.3 is already supported like @andrjohns said. If you can provide an example where Rtools 4.3 isn't supported then we can reopen (and fix it!). Thanks!
