### ISSUE TITLE
Error：Native call to `processx_exec` failed

### ISSUE THREAD

**Issue by 01litterbear** [stan-dev/cmdstanr#864]
**Describe the bug**
library(cmdstanr)
library(posterior)
library(bayesplot)
color_scheme_set("brightblue")
file <- file.path(cmdstan_path(), "examples/bernoulli/bernoulli.stan")

mod <- cmdstan_model(file)

**Compiling Stan program...
Error in `process_initialize(self, private, command, args, stdin, stdout, …`:
! Native call to `processx_exec` failed
Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …`:
! Command 'bin/stanc.exe' not found @win/processx.c:982 (processx_exec)
Type .Last.error to see the more details.**

---
Backtrace:
 1. cmdstanr::cmdstan_model(file)
 2. CmdStanModel$new(stan_file = stan_file, exe_file = exe_file, …
 3. local initialize(...)
 4. self$compile(...)
 5. cmdstanr:::get_standalone_hpp(temp_stan_file, stancflags_standalone)
 6. withr::with_path(c(toolchain_PATH_env_var(), tbb_path()), wsl_compatible_run(command = stanc_cmd(), …
 7. base::force(code)
 8. cmdstanr:::wsl_compatible_run(command = stanc_cmd(), args = c(stan_file, …
 9. base::do.call(processx::run, run_args)
10. (function (command = NULL, args = character(), error_on_status = TRUE, …
11. process$new(command, args, echo_cmd = echo_cmd, wd = wd, windows_verbatim_args = windows_verbatim_args, …
12. local initialize(...)
13. processx:::process_initialize(self, private, command, args, stdin, stdout, …
14. processx:::chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …
15. | base::withCallingHandlers(do.call(".Call", list(.NAME, ...)), error = function(e) { …
16. | base::do.call(".Call", list(.NAME, ...))
17. | base::.handleSimpleError(function (e) …
18. | local h(simpleError(msg, call))
19. | processx:::throw_error(err, parent = e)

**Operating system**
Win11
rtool4.0
r 4.23

**CmdStanR version number**
> library(cmdstanr)
This is cmdstanr version 0.6.1.9000
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: C:/Users/xqhon/Documents/.cmdstan/cmdstan-2.33.1
- CmdStan version: 2.33.1

**Comment by andrjohns** [comment]
It looks like some of the cmdstan files are missing, what happens when you run: `rebuild_cmdstan()`

**Comment by 01litterbear** [comment]
> It looks like some of the cmdstan files are missing, what happens when you run: `rebuild_cmdstan()`
Thank you for your prompt reply！
It's solved! using mobile hotspot can effectively solve it！
referring to this article https://www.maxmantei.com/2020/05/16/cmdstanr-windows/
