### ISSUE TITLE
install_cmdstan() fails because it can't be downloaded

### ISSUE THREAD

**Issue by JAQuent** [stan-dev/cmdstanr#865]
I'm actually pretty frustrated because for some hours now I've tried to install the latest version of install_cmdstan() but it just doesn't work as the download fails. The reason is that where I live (China) github.com is not blocked but the connectivity without VPN is abysmal and most of the time not functioning. 

**The solution I'd like**
A simple solution would be to allow to use already downloaded .tar.gz archives. I thought I'd be smart and just download the archive from [here](https://github.com/stan-dev/cmdstan/releases/download/v2.33.1/cmdstan-2.33.1.tar.gz) myself and then use the path with the argument release_url but unfortunately this doesn't work. 

However, this would also be super helpful in cases where one can't use any VPNs like high-performance clusters of universities but also for me now. This would make cmdstan(r) much more accessible in my opinion. 

PS So far I haven't found out how to install cmdstan without this function. Any guidance would be highly appreciated.

**Comment by andrjohns** [comment]
> I'm actually pretty frustrated because for some hours now I've tried to install the latest version of install_cmdstan() but it just doesn't work as the download fails.

Please remember that this is an open source project primarily worked on by volunteers, some functionality might not be present and some might not work as expected, but we try to work with the community to do our best. All you have to do is ask.

I've opened a PR to add this functionality.

**Comment by JAQuent** [comment]
Oh thank you. Btw, I didn't want to sound angry at any devs, I just started like the example that is provided when you open an issue, which was "I am frustrated". Hopefully, this didn't come across wrongly. If it did, my apologies.
