### ISSUE TITLE
Latest RStudio version 2023.09.1+494 crashes cmdstanr and brms

### ISSUE THREAD

**Issue by hauselin** [stan-dev/cmdstanr#868]
**Describe the bug**
Upgraded to RStudio Version: 2023.09.1+494 | Released: 2023-10-17 and `brms` crashes when `backend = cmdstanr`. See also https://discourse.mc-stan.org/t/using-cmdstanr-crashing-rstudio/33081/2

**To Reproduce**

Install latest RStudio Version: 2023.09.1+494 | Released: 2023-10-17

```r
# RStudio version: 2023.09.1+494 | Released: 2023-10-17
# R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
library(brms)
brm(mpg ~ cyl, mtcars)   # doesn't crash RStudio
brm(mpg ~ cyl, mtcars, backend = 'cmdstanr')   # crashes RStudio
```

**Operating system**
Apple M1 Max, Ventura 13.0

**CmdStanR version number**
0.6.1.9000

**Additional context**

Downgrading to older RStudio resolved the issue. https://dailies.rstudio.com/version/2023.09.0+463.pro11/

```
# RStudio 2023.09.0+463.pro11
> packageVersion("StanHeaders")
[1] ‘2.26.28’
> packageVersion("rstan")
[1] ‘2.32.3’
> packageVersion("brms")
[1] ‘2.20.5’
> packageVersion("cmdstanr")
[1] ‘0.6.1.9000’
```

**Comment by jgabry** [comment]
Thanks for reporting this, that's not good! I just saw the forum post too, so it looks like you're not the only one with this issue. Does this also happen if you run cmdstanr itself without using brms? For example, if you start a clean R session and don't load brms (only load cmdstanr) and then run `cmdstanr_example()`, does it crash?

I haven't been able to reproduce this using same versions of RStudio, brms, and cmdstanr that you have, but I'm using an older Intel Mac (not sure if that's related, might not be a Mac thing, but possibly). @andrjohns or @rok-cesnovar are either of you able to reproduce this?

**Comment by marcdotson** [comment]
If I run a clean R session and only load cmdstanr, it doesn't crash. That's how I figured it was an RStudio problem and downgraded to get cmdstanr working again with RStudio.

**Comment by hauselin** [comment]
If I remember correctly, when I load cmdstanr then brms, RStudio crashes immediately. But if I load bmrs then cmdstanr, it crashes only when it starts sampling.

**Comment by marcdotson** [comment]
Just wanted to confirm that this problem persists with cmdstanr 0.7.0. It looks like RStudio Version 2023.06.2+561 (2023.06.2+561) remains the latest version of RStudio that doesn't crash with cmdstanr.

**Comment by jgabry** [comment]
That’s frustrating, sorry it’s still happening. As far as I know we’re not doing anything with cmdstanr that RStudio doesnt allow and the problem seemed to initially emerge due to a new RStudio version and not a new cmdstanr version, so I think this should probably be considered an RStudio issue unless anyone can point to something we’re doing in cmdstanr that’s a problem. I wish I had some idea of what the issue is but I have no clue! 

There’s  an open RStudio issue https://github.com/rstudio/rstudio/issues/13769 but it hasn’t been resolved yet. Although @eipi10 reported that reinstalling RStudio fixed it for them for some mysterious reason: https://github.com/rstudio/rstudio/issues/13769#issuecomment-1856995426

**Comment by marcdotson** [comment]
I'm not sure what's changed, but I no longer get fatal errors when loading cmdstanr or using it to compile and sample.

- RStudio Version 2023.12.0+369
- CmdStan version: 2.33.1
- cmdstanr version 0.7.1
- MacBook Pro M2 Pro
- macOS Sonoma 14.2.1

**Comment by hauselin** [comment]
With the latest R and RStudio, I also no longer get the fatal errors.

- R version 4.3.2 (2023-10-31)
- RStudio: Version 2023.12.1+402 (2023.12.1+402)
- Operating system: Apple M1 Max, Ventura 13.0

**Comment by jgabry** [comment]
Awesome, thanks for following up. I wish we had a better idea of why this was happening, but I'm glad it's working for you now.
