### ISSUE TITLE
Doc typos

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#87]
I'm making an issue thread for these. I think that's how Bob handle's them in the other repos (they all get fixed together and then the issue is closed and a new one is opened)

In model-method-sample "A character vector containing paths to JSON or Rdump file files (one per chain) compatible". The "file files" thing is off.

**Comment by jgabry** [comment]
Thanks!

**Comment by jgabry** [comment]
@rok-cesnovar fixed this in #101 so closing
