### ISSUE TITLE
jacobian vs jacobian_adjustment

### ISSUE THREAD

**Issue by avehtari** [stan-dev/cmdstanr#877]
`$optimize()` and `$laplace()` docs list option `jacobian`, but `$log_prob()` and `$log_prob_grad()` docs list option `jacobian_adjustment`. However, `$log_prob()` and `$log_prob_grad()` seem to work also with option `jacobian`. Maybe clarify the documentation of `$log_prob()` and `$log_prob_grad()` ?. Maybe also add a link to Stan doc https://mc-stan.org/docs/stan-users-guide/change-of-variables.html ?

**Comment by jgabry** [comment]
> However, `$log_prob()` and `$log_prob_grad()` seem to work also with option `jacobian`.

This may just be due to the fact that R allows partial argument matching (in some cases). 

@avehtari @andrjohns Should we just change the argument name `jacobian_adjustment` to `jacobian` in methods like `log_prob` to match the argument names in the other methods like `optimize` and `laplace`?

**Comment by jgabry** [comment]
@avehtari I can go ahead and change the argument name from `jacobian_adjustment` to `jacobian` to be consistent with `optimize` and `laplace`, but then we should still keep `jacobian_adjustment` temporarily and add a deprecation warning for now. So the function signature would include both arguments for some time:  

```r
log_prob <- function(unconstrained_variables, jacobian = TRUE, jacobian_adjustment = TRUE)
```

with a deprecation warning if `jacobian_adjustment` is used. Do you prefer this or prefer just keeping the current `jacobian_adjustment` argument as is?

**Comment by avehtari** [comment]
I prefer consistent option naming between functions as it makes easier to remember them (so `jacobian` in this case)

**Comment by jgabry** [comment]
Ok I agree, I will deprecate `jacobian_adjustment` in favor of `jacobian`
