### ISSUE TITLE
Dont use bash on windows for install_cmdstan()

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#88]
The install_cmdstan() command currently uses bash, which is not native on Windows and is not installed with RTools. The easies way of installing it currently is to have Git for Windows. Its not the worst of dependencies one can have, but it would still be nice to get rid of it. This was pointed out [here](https://discourse.mc-stan.org/t/cmdstanr-installation-error-command-not-found-win-processx-c-977/11970).

The solution would be to have to most of the work done in R and only call curl, mingw32-make, tar, etc in the command line. I dont think powershell scripting or .bat files are worth the trouble.

**Comment by jgabry** [comment]
> The solution would be to have to most of the work done in R

Ok yeah that would be good!

**Comment by mitzimorris** [comment]
that makes sense - for CmdStanPy, we rewrote this script as a Python script early on.

**Comment by jgabry** [comment]
@rok-cesnovar I started playing around with this on the branch `install_cmdstan_via_r`:  
https://github.com/stan-dev/cmdstanr/blob/install_cmdstan_via_r/R/install.R

I haven't added the repo_clone/branch functionality yet but I do have a version now that successfully downloads and installs the latest release (at least on my mac!).

**Comment by jgabry** [comment]
Ok added the `repo_clone` functionality to the new `install_cmdstan()`. I think the version on the branch should now be fully functional. (I haven't touched `cmdstan_git_checkout_branch()` though).

**Comment by jgabry** [comment]
Will open a PR soon
