### ISSUE TITLE
How to update cmdstanr?

### ISSUE THREAD

**Issue by beew** [stan-dev/cmdstanr#882]
I don't seem to be able to find this information. I can only find how to install it in R. I have 0.5.3 and I want to upgrade to 0.6.1

I tried in R
```
update.packages("cmdstanr", repos = [c](https://rdrr.io/r/base/c.html)("https://mc-stan.org/r-packages/", [getOption](https://rdrr.io/r/base/options.html)("repos")))
```

But nothing happened.

**Comment by jgabry** [comment]
Can you try 

```r
remotes::install_github("stan-dev/cmdstanr")
```

Does that work?

**Comment by beew** [comment]
> Can you try
> 
> ```r
> remotes::install_github("stan-dev/cmdstanr")
> ```
> 
> Does that work?

Does it just install it again?

**Comment by beew** [comment]
> Yeah, that will install the latest version from GitHub. update.packages() doesn't work here because cmdstanr isn't on CRAN at the moment (but in general update.packages() also just installs the latest versions of packages).

That will install the unstable development version, which is not what I want.

I want to update to the latest stable version, so I ran instead
```
install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```
Basically = reinstalling.

**Comment by jgabry** [comment]
> > Yeah, that will install the latest version from GitHub. update.packages() doesn't work here because cmdstanr isn't on CRAN at the moment (but in general update.packages() also just installs the latest versions of packages).
> 
> That will install the unstable development version, which is not what I want.
> 
> I want to update to the latest stable version, so I ran instead
> 

Yeah your code will install the latest release, which is fine. I had put the latest development version since it includes several bug fixes that haven't been released yet (we're working on the next release currently), but I should have mentioned that. 

> Basically = reinstalling.

Yeah, in general there is no way to "update" an R package without reinstalling it (for any R package, not just this one).
