### ISSUE TITLE
cmdstanr broken if used from make

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstanr#883]
**Describe the bug**
I am using cmdstanr inside a build process which is controlled by make. This means that the make calls emitted by cmdstanr are child processes from an outer make controlled process. In this setting cmdstanr stops working with our GNU make 4.2 installation.

**To Reproduce**

Here is a minimal makefile to trigger the mis-behaviour (and the commented out solution I found):
```
# activating this line fixes the issues with sub-make
# MAKEFLAGS += --no-print-directory

printstanc:
        cd $(CMDSTAN); make print-STANCFLAGS
```

If one now calls

`CMDSTAN=..path..to..cmdstan.. make printstanc`

then I do get this:

![image](https://github.com/stan-dev/cmdstanr/assets/12070126/68d27a06-0a34-401c-bf05-4b214c69d042)

Note that there are the "Entering directory" prints - these kill cmdstanr as these prints become literally part of what cmdstanr bakes into the STANCFLAGS. Calling make with the option shown above or uncommenting the comment in the example makefile makes things work ok. Then you get

![image](https://github.com/stan-dev/cmdstanr/assets/12070126/c9018fd4-74b3-4a30-b00c-5a9811d9ea1a)

There are not more "Entering" prints as cmdstanr expects it.

I guess a solution here is to add this option when querying these options (which is done via make) or filter out the Entering messages.

**Expected behavior**
Things should just work ok when building things with cmdstanr whenever one uses things as a sub make process.

**Operating system**
Linux

**CmdStanR version number**
0.6.1

**Additional context**

**Comment by andrjohns** [comment]
I think this is already fixed in the github version

**Comment by wds15** [comment]
I burned a lot of my time to pin this down. A release would be great with this fix to save others from running into this.

**Comment by rok-cesnovar** [comment]
Ouch, sorry for that.

The release is going to happen very soon: https://github.com/stan-dev/cmdstanr/pull/871 I think we have most things ready. 

@jgabry do you need any help with the 0.7 release?

**Comment by jgabry** [comment]
Sorry got a bit behind on the release. There are a few pathfinder related things that @avehtari had asked for that I haven't had a chance to do yet (#876, #873) and @SteveBronder was going to look into whether the pathfinder implementation in cmdstanr could handle multiple inits (pathfinder can initialize paths separately but I think the R implementation won't allow multiple inits currently). Should we just go ahead and do a release without these things and add them as features later?

**Comment by avehtari** [comment]
I'm ok making a quick release due to that make fix

**Comment by andrjohns** [comment]
+1 to go ahead with the release now and add the features later as well

**Comment by jgabry** [comment]
Sounds good, we can do a follow up release as soon as those features are available.

**Comment by bbolker** [comment]
I'm surprised, but I seem to have run into this (which I have reported before) in cmdstanr 0.8.1. @wds15's MAKEFLAGS workaround worked for me ... can anyone confirm that this fix really made it in?  (I could swear that Carl Pearson and I have reported this issue elsewhere as well, but I can't find it now ...)

**Comment by jgabry** [comment]
@bbolker Thanks for reporting this, that's strange, I also thought this had been fixed but I can't seem to track down the commit where that happened. @rok-cesnovar @andrjohns do you remember what the fix for this was that was referred to [here](https://github.com/stan-dev/cmdstanr/issues/883#issuecomment-1851702759)?  

> I think this is already fixed in the github version

**Comment by bbolker** [comment]
This **looks** like it's fixed [here](https://github.com/stan-dev/cmdstanr/blob/master/R/utils.R#L705-L714), from https://github.com/stan-dev/cmdstanr/commit/48ca5e656eaed7aadbae4534dd62f2615ed56b23

I can't be sure I didn't do something else weird; the "-s" seems to be there. I haven't gotten around to testing carefully.

Related:

- https://github.com/stan-dev/cmdstanr/commit/57eb00eaf82dad2af8ab6e10ac7280b9f49e9a93
- https://github.com/stan-dev/cmdstanr/commit/5e77e1988f07f0911e4a3d8840a2b76fb5c8b1e1
