### ISSUE TITLE
Silence output message from optimization

### ISSUE THREAD

**Issue by zhengchencai** [stan-dev/cmdstanr#884]
Hello,

Is there a way to silence output message for ```mod$optimize()```? I am fitting a simple model which takes less than 1s but repeating for many data (>30K). After parallelization using ```doFuture``` the total fitting time is fine but the printed message takes time. In ```mod$sample``` we have show_messages and show_exceptions, but not for optimization. Thanks a lot. 

BTW, when pathfinder will be relaeased in cmdstanr? I see a PR of v0.7 in the pull requests :)

**Comment by jgabry** [comment]
Right now I don't think that can be turned off in any way, but that's a good point. The other model fitting methods besides `sample` should also have those arguments. 

Regarding the pathfinder release, I'm working on getting that ready right now. So maybe today, but definitely this week. If you want to try it now you can install from that PR branch (it should be working).

**Comment by zhengchencai** [comment]
Thanks a lot @jgabry. Looking forward to playing the pathfinder.

**Comment by jgabry** [comment]
Let's actually leave this issue open until we add the ability to avoid printing during optimization. That's a good feature to have.
