### ISSUE TITLE
make multicore support more consistent between pathfinder and sampling algorithms

### ISSUE THREAD

**Issue by wpetry** [stan-dev/cmdstanr#888]
**Is your feature request related to a problem? Please describe.**
When `num_paths` > 1 in `$pathfinder()`, each path runs in series. This could be faster if it took advantage of more processing cores. This is related to but separate from the existing `num_threads` argument.

**Describe the solution you'd like**
Follow the behavior of `$sampling()` by including a `cores` argument. This could default to `getOption("mc.cores", 1L)`.

**Describe alternatives you've considered**
I can achieve this by running repeating calls with `num_paths = 1` in `parallel::mclapply`, `furrr::future_map`, or similar. It'd be much preferred to avoid dependencies by following existing behavior for other algorithms.

**Additional context**
I'm working from Aki Vehtari's example [using Pathfinder to find initial values](https://users.aalto.fi/~ave/casestudies/Birthdays/birthdays.html#Models_for_relative_number_of_birthdays). The model for my use case more complicated, with the total runtime of ~10 min. If each path was distributed to a different processing core, this would likely be reduced to a more reasonable couple of minutes.

**Comment by andrjohns** [comment]
> This is related to but separate from the existing num_threads argument.

This is handled by the `num_threads` argument, which initialises a total threadpool to distribute paths as well as `reduce_sum` workloads

**Comment by wpetry** [comment]
Ok, I think I've figured this out. The behavior and workflow is quite different than running chains on different cores in `$sampling` as I had expected. Thank you @andrjohns for getting me on the right track.

To get this working as expected/intended,
- add `cpp_options = list(stan_threads = TRUE)` to the `cmdstan_model` call when compiling the model
- use the `num_threads` argument as suggested to distribute pathfinder paths among cores
- add `threads_per_chain` argument if `$sampling()` from the compiled model (i.e., this can be =1 if not using `reduce_sum`

Although it's clear now that the feature I requested is already implemented, I still think it would be helpful to make the multicore syntax and workflow consistent across the different fitting algorithms. If a user's Stan code doesn't use `map_reduce`, it's not obvious that they need to compile with threading support to distribute paths in `$pathfinder()` but not chains in `$sampling()`. If there's a reason these need to be implemented differently that I'm not seeing, perhaps there are some documentation and/or message/warning improvements that would better communicate how to make use of multicores. For example, if the user calls `$pathfinder()` with `num_threads`>1 but the model hasn't been compiled with threading support, perhaps a message letting them know it will run sequentially + how to distribute paths to different cores would be helpful.

**Comment by andrjohns** [comment]
Thanks for diving into this more @wpetry, and apologies for the confusion! 

The current handling of parallel chains was implemented before we had support in `cmdstan` for running parallel chains directly, so it's still on the to-do list to update (good to have a reminder!).

But that's a really good catch about the handling of `num_threads` without `STAN_THREADS`, we should definitely be giving a warning/message of some kind.

I'm going to create two issues so that we can track these separately, and close this one, but thanks for reporting!
