### ISSUE TITLE
Add `output_dir` argument to `$sample()` and other fitting methods

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#89]
Following CmdStanPy (https://github.com/stan-dev/cmdstanpy/issues/133#issuecomment-551942038), if the user knows in advance that they want to save the output csv files we could do that via an `output_dir` argument. They can always call `$save_output_files()` afterwards, but this would save that step if they know the want the files.

**Comment by jgabry** [comment]
If there are no objections I can do this after #84 is merged

**Comment by bbbales2** [comment]
No objection
