### ISSUE TITLE
issues of include  stan math library in compile

### ISSUE THREAD

**Issue by MSQ-123** [stan-dev/cmdstanr#902]
I tried to include stan math library by:

file <- file.path("./Txn_burst_test.stan")

mod <- cmdstan_model(file, compile = FALSE)
mod$compile(include_paths = c('math-4.7.0/',
                '/usr/local/include/eigen3/',
                '/usr/local/include/eigen3/Eigen/'))

with errors:

Syntax error in '/usr/local/include/eigen3/Eigen/src/Core/util/Macros.h', line 23, column 38,

#define EIGEN_VERSION_AT_LEAST(x,y,z) (EIGEN_WORLD_VERSION>x || (EIGEN_WORLD_VERSION>=x && \
    23:                                        (EIGEN_MAJOR_VERSION>y || (EIGEN_MAJOR_VERSION>=y && \
                                               ^
    24:                                                                   EIGEN_MINOR_VERSION>=z))))

Expected "functions {" or "data {" or "transformed data {" or "parameters {" or "transformed parameters {" or "model {" or "generated quantities {".

make: *** [/var/folders/2j/k27f0c2x3cddhvbwn5_t2x200000gn/T/Rtmp8SsQHu/model-547b6b851eca.hpp] Error 1

Error: An error occured during compilation! See the message above for more information.

It seems strang with this error

**Comment by andrjohns** [comment]
The `include_paths=` argument is for including additional Stan files, not C++ headers. If you want to use a custom directory for the Math library then you need to change your `make/local` file:
```r
cmdstan_make_local(cpp_options = list("MATH"="YOUR_PATH_HERE"),
                   append = TRUE)
```
