### ISSUE TITLE
Be able to silence warning about init values being set only for subset of parameters

### ISSUE THREAD

**Issue by ben18785** [stan-dev/cmdstanr#912]
**Is your feature request related to a problem? Please describe.**
I am integrating `cmdstanr` into a package that calls `model$sample`. Some of my parameters are being optionally defined as follows:

```stan
array[is_poisson==1 ? 0 : 1] real kappa;
```

and if `is_poisson==1` is `FALSE`, I would like not to have to supply initial values for these. But when I don't I get a warning:

> Init values were only set for a subset of parameters. 
> Missing init values for the following parameters:
> sigma

**Describe the solution you'd like**
I'd like to be able to silence the above warning.

**Describe alternatives you've considered**
I could supply some sort of null values for the parameters, but that feels a bit messy.

**Additional context**
The package I'm working on repeatedly calls `model$sample` so the above warning is emitted repeatedly, causing a messy collection of stuff being printed to the console.

**Comment by jgabry** [comment]
It would be pretty easy to add an argument for this to the _internal_ function that checks the inits, but I'm not sure about how the user should control this. Some options: 

* Add an argument for turning off this warning. The downside to this approach is that we would need to add this argument to all model fitting methods, which already have so many (too many?) arguments and we don't have any other arguments like that control individual warning messages (we have `show_exceptions`, but that controls _all_ exceptions thrown by Stan itself) 

* Add a global option, e.g., `options(cmdstanr_warn_inits = FALSE)`. The downside is that it's harder for the user to find which options apply to particular function calls. We currently have the `cmdstanr_verbose` option, which may only be documented in the vignette.  (Also @avehtari [proposed changing this](https://github.com/stan-dev/cmdstanr/issues/900#issuecomment-1909881165) into an actual argument to the fitting methods.)

* Get rid of this warning altogether and assume that the user is specifying initial values for the parameters they want. 

@rok-cesnovar @andrjohns (or anyone else) Any preference on this or other ideas?

**Comment by jgabry** [comment]
> The last option is my least favourite because I think it can lead to silent bugs when you think you have set inits for parameters, but they are not actually set. I would lean towards the global option because this would be a feature for a smaller audience of users (power users or package maintainers that use cmdstanr).

Yeah I'm leaning towards global option too. And we could add a doc page that lists the global options (some packages list all global options on the help page with the package name, i.e. in `cmdstanr-package.R`).

**Comment by jgabry** [comment]
I can make a PR for this

**Comment by venpopov** [comment]
I'd also love this feature
