### ISSUE TITLE
Syntax error when adding a Gaussian Process term

### ISSUE THREAD

**Issue by FredericBlum** [stan-dev/cmdstanr#926]
**Describe the bug**
When I am adding a gaussian process term within brms, I get a syntax error when I specify that I want to use cmdstanr as a backend. With rstan, the model runs through without problems.

**To Reproduce**
Consider the following brms model:

```
  brm(data=data,
      family=Gamma("log"),
      formula=Duration ~ 1 + utt_initial + word_initial + 
        gp(Longitude, Latitude, by=Macroarea, gr=TRUE),
      prior=c(prior(normal(4.5, 0.1), class=Intercept),
              prior(normal(6, 0.5), class=shape),
              prior(normal(0, 0.3), class=b),
              prior(exponential(12), class=sd),
              prior(lkj(5), class=cor),
              prior(normal(0, 1), class = sdgp)
      ),
      iter=50, warmup=25, chains=4, cores=4,
      control=list(adapt_delta=0.90, max_treedepth=10),
      seed=1,
      silent=0,
      backend='cmdstanr'
```

I receive the following error message:

```
Syntax error in '/var/folders/tp/38bwgqbn0_qgdjzjm2xkbbsm0000gp/T/RtmpaLy5IR/model_bbafd24c38b94b9192507696cc00ee47.stan', line 24, column 23 to column 24, parsing error:
   -------------------------------------------------
    22:     *   a vector to be added to the linear predictor
    23:     */
    24:    vector gp(data vector[] x, real sdgp, vector lscale, vector zgp) {
                                ^
    25:      int Dls = rows(lscale);
    26:      int N = size(x);
   -------------------------------------------------

An identifier is expected as a function argument name.

Error: Syntax error found! See the message above for more information.
```

**Expected behavior**
Model should run without problems.

**Operating system**
MacOS 14.3.1 (23D60)

**CmdStanR version number**
0.7.1

**Additional context**
Not really sure what I am missing, or if this is indeed a cmdstanr problem, or an error through brms. But since the model works with rstan, I decided to first post this here.

**Comment by jgabry** [comment]
I think this might be a brms issue. If I'm not mistaken, with the latest versions of Stan that cmdstanr is using I think instead of `vector[] x` brms should write `array[] vector x`.

**Comment by jgabry** [comment]
Ok great, thanks for following up
