### ISSUE TITLE
Make documentation of `$sample()` method of a `CmdStanModel` more explicit about output

### ISSUE THREAD

**Issue by odros** [stan-dev/cmdstanr#928]
**Describe the issue**

According to the [CmdStan User’s Guide v2.34](https://mc-stan.org/docs/cmdstan-guide/mcmc_sampling_intro.html#mcmc_output_csv), one output file per chain is produced when a model is run. The [documentation](https://mc-stan.org/cmdstanr/reference/model-method-sample.html) of the `$sample()` method of CmdStanModel does not explicitly state this. Making it so would save some time when trying to understand how to extract and merge information from the output.

Adding a something like the following to the `output_dir` parameter description [here](https://github.com/stan-dev/cmdstanr/blob/master/man/model-method-sample.Rd) is all this would take:
```
A path to a directory where CmdStan should write its output CSV files, one per chain in the model.
```
Instead of:
```
A path to a directory where CmdStan should write its output CSV files.
```

**CmdStanR version number**
0.7.1

**Comment by jgabry** [comment]
Thanks, good suggestion. We should definitely clarify in the doc that one file per chain is produced when using the sample method.
