### ISSUE TITLE
Add the new Stan 2.34 arguments save_metric and save_cmdstan_config

### ISSUE THREAD

**Issue by venpopov** [stan-dev/cmdstanr#931]
Stan 2.34 added two new arguments:

- save_metric: save the inv_metric to a json file
- save_cmdstan_config: saves what is normally the header of the csvs in separate files

It would be good to have these options as arguments to method `sample` (similar issue raised for CmdStanPy [here](https://github.com/stan-dev/cmdstanpy/issues/713).

If these are enable by default, also the current methods for reading in the metadata can be changed to read from those files instead for much faster creation of the cmdstanmcmc object when diagnostics = "".

**Comment by venpopov** [comment]
I got it working (exposing the new arguments part) so if it's of interest I can open a PR

**Comment by jgabry** [comment]
A PR would be great, thank you!
