### ISSUE TITLE
Imprecision in the log function

### ISSUE THREAD

**Issue by wellington36** [stan-dev/cmdstanr#949]
**Describe the bug**
Running some applications that depend on the `log` function of `cmdstanr`, we found an inaccuracy in the function that returns values with precision of ~1e-7 (instead of ~1e-16 as in other languages).

**To Reproduce**
We can verify this with the following Stan and R codes. Note that the problem does not occur when evaluating the square of a number, only the `log`.

```stan
data {
  real x;
}

generated quantities {
  real defaultLog = log(x);
  real defaultSquare = x^2;
}
```

```R
library(cmdstanr)

stanfit <- function(fit) rstan::read_stan_csv(fit$output_files())

# system("rm main")   # remove the binary
model <- cmdstan_model("main.stan")

x <- 2
cdata <- list(
  x = x
)

comparison <- stanfit(
  model$sample(
    data = cdata,
    fixed_param = TRUE,
    iter_sampling = 1,
    adapt_engaged = FALSE,
    chains = 1
  )
)

( ext <- rstan::extract(comparison) )

print("Ln 2 in R:")
Rmpfr::mpfr(log(x), 100)

print("Ln 2 in Stan")
Rmpfr::mpfr(ext$defaultLog, 100)

print("Difference between R and Stan of Ln 2:")
Rmpfr::mpfr(abs(ext$defaultLog - log(x)), 100)

print("Difference between R and Stan of the square:")
Rmpfr::mpfr(abs(ext$defaultSquare - x^2), 100)
```
*Out:*
```
[1] "Ln 2 in R:"
[1] 0.69314718055994528622676398299518
[1] "Ln 2 in Stan"
[1] 0.69314699999999995760902038455242
[1] "Difference between R and Stan of Ln 2:"
[1] 1.8055994532861774359844275750220e-7
[1] "Difference between R and Stan of the square:"
[1] 0.
```

**Expected behavior**
The 1e-7 error suggests to me that at some point the log is being converted to 32bit, given that the [epsilon](https://en.wikipedia.org/wiki/Machine_epsilon) of a 32bit machine is ~1e-7.

**Operating system**
Linux (error verified in Ubuntu and Manjaro distros)

**CmdStanR version number**
Error verified in `v0.7.1`, `v0.6.1` and `v.0.4.0`

**Additional context**
As far as I checked, the imprecision only occurs in the log, the `lgamma` function for example, does not have this precision error.

@maxbiostat

**Comment by jgabry** [comment]
Thanks for reporting this! Two questions: 

1. Does changing the `sig_figs` argument affect this?

> (positive integer) The number of significant figures used when storing the output values. By default, CmdStan represent the output values with 6 significant figures. The upper limit for sig_figs is 18. Increasing this value will result in larger output CSV files and thus an increased usage of disk space.

2. Do you know if this is a cmdstanr issue or a Stan issue more generally? If the latter I think we should move this issue so the right developers see it.

**Comment by wellington36** [comment]
> 1. Does changing the `sig_figs` argument affect this?

Yes, if I use `sig_figs=10`, for example, the error goes to ~1e-10, and is equivalent for other values of `sig_figs`. But still strange why wouldn't other functions like `lgamma` have this loss of precision?

> 2. Do you know if this is a cmdstanr issue or a Stan issue more generally? If the latter I think we should move this issue so the right developers see it.

I suppose not, I just tested it in pystan and there was no problem, but I couldn't say if it affects other repositories besides these 2.

**Comment by rok-cesnovar** [comment]
pystan/rstan return the draws directly in memory with the system floating point precision, cmdstanr/py store it in CSV with precision based on sig_figs

**Comment by andrjohns** [comment]
Confirmed this is just a `sig_figs` difference. You can verify by exposing Stan's `log()` function to R and performing the same comparison:

```r
funcode <- "
functions {
  real cmdstanr_log(real x) {
    return log(x);
  }
}
"

library(cmdstanr)

funmod <- cmdstan_model(write_stan_file(funcode), compile_standalone = TRUE)
funmod$expose_functions(global=TRUE)

print("Ln 2 in R:")
Rmpfr::mpfr(log(x), 100)

print("Ln 2 in Stan")
Rmpfr::mpfr(cmdstanr_log(x), 100)

print("Difference between R and Stan of Ln 2:")
Rmpfr::mpfr(abs(cmdstanr_log(x) - log(x)), 100)
```

Returns:
```
[1] "Ln 2 in R:"
[1] 0.69314718055994528622676398299518
[1] "Ln 2 in Stan"
[1] 0.69314718055994528622676398299518
[1] "Difference between R and Stan of Ln 2:"
[1] 0
```
