### ISSUE TITLE
pathfinder does not work with init functions

### ISSUE THREAD

**Issue by sbfnk** [stan-dev/cmdstanr#963]
**Describe the bug**
pathfinder does not work with initial values specified as a function

**To Reproduce**
``` r
library("cmdstanr")
#> This is cmdstanr version 0.7.1
#> - CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
#> - CmdStan path: /Users/eidesfun/.cmdstan/cmdstan-2.34.1
#> - CmdStan version: 2.34.1
file <- file.path(cmdstan_path(), "examples/bernoulli/bernoulli.stan")
mod <- cmdstan_model(file)
stan_data <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
fit_pf <- mod$pathfinder(
  data = stan_data, seed = 123, init = function() return(list(theta = 0.5))
)
#> Warning in seq_len(num_procs): first element used of 'length.out' argument
#> Error in seq_len(num_procs): argument must be coercible to non-negative integer
```

<sup>Created on 2024-05-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Expected behavior**
No error

**Operating system**
Ubuntu 22.04.4

**CmdStanR version number**
21888fa

**Additional context**
Haven't been able yet to dig all the way but possibly related to changes in https://github.com/stan-dev/cmdstanr/commit/c36f280708545afa26f13fc58116f75abb59feee

**Comment by andrjohns** [comment]
Thanks for catching this! Will be fixed in #964
