### ISSUE TITLE
Strange error after sampling (Linux)

### ISSUE THREAD

**Issue by csetraynor** [stan-dev/cmdstanr#97]
**Describe the bug**
This error happens just after sampling the model. The compiling and sampling go fine the problem happens just after this. The error is pretty opaque.

**To Reproduce**
The model from the vignette is enough to reproduce the model.
```
library(cmdstanr)
cmdstanr::set_cmdstan_path("~/opt/cmdstan")
file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)

data_list <- list(N = 10, y =c(0,1,0,0,0,0,0,0,0,1))
fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  num_chains = 2, 
  num_cores = 2
)
```
The error then happens after sampling this is the traceback output:

```
Both chains finished succesfully.
Mean chain execution time: 0.3 seconds.
Total execution time: 0.3 seconds.
Error in FUN(X[[i]], ...) : attempt to apply non-function
> traceback()
6: FUN(X[[i]], ...)
5: lapply(private$processes_, function(p) p$kill_tree())
4: procs$cleanup()
3: private$run_sample_()
2: runset$run_cmdstan()
1: mod$sample(data = data_list, seed = 123, num_chains = 2, num_cores = 2)
```
The sessionInfo() :

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /opt/scp/software/mro/3.5.1-foss-2017a/lib64/R/lib/libRblas.so
LAPACK: /opt/scp/software/mro/3.5.1-foss-2017a/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] cmdstanr_0.0.0.9000  RevoUtils_11.0.1    
[3] RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] crayon_1.3.4          assertthat_0.2.1.9000
 [3] R6_2.4.1.9000         jsonlite_1.5         
 [5] backports_1.1.2       git2r_0.23.0         
 [7] magrittr_1.5          tidyproject_0.3.1    
 [9] rlang_0.4.1.9000      debugme_1.1.0        
[11] rstudioapi_0.7        checkmate_1.8.5      
[13] tools_3.5.1           yaml_2.2.0           
[15] compiler_3.5.1        processx_3.1.0  
```

**Comment by rok-cesnovar** [comment]
Thanks for reporting and a thorough description. Will take a look. 
If you can, please also post the output of "g++ --version".

**Comment by csetraynor** [comment]
Hi @rok-cesnovar yes no problem thank you. 
```
bash-4.2$ g++ --version
g++ (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by csetraynor** [comment]
Not sure if this was the intended behaviour but run.R line 309 looks odd.. The error was comming from this one. I changed a small typo and #99 works fine

**Comment by rok-cesnovar** [comment]
Thanks for the fix @csetraynor. Fixed with #99

**Comment by jgabry** [comment]
Sorry to be late to this. I'm glad changing this makes the error go away but I'm not sure the solution is quite right (I might just be confused though!). Doesn't this

```r
lapply(private$processes_, function(p) p$kill_tree)
```

_not_ result in `kill_tree` being evaluated? That is `p$kill_tree` just returns the `kill_tree` method but doesn't call it. That's why it was `p$kill_tree()` with the parentheses before. So this might avoid the error but I'm not sure it's actually killing the trees. Does that make sense? Again, I might just be confused!

**Comment by jgabry** [comment]
@bbbales2 and I verified that this isn't properly terminating processes (e.g. using the RStudio stop button). we need to evaluate `kill_tree()` not just return the function `p$kill_tree` as an object. I think we can revert back to what we had before but avoid the error for @csetraynor if we wrap it in `try(..., silent = TRUE)`. I'll submit a PR.
