### ISSUE TITLE
Test for using pathfinder as init omits argument

### ISSUE THREAD

**Issue by wpetry** [stan-dev/cmdstanr#976]
https://github.com/stan-dev/cmdstanr/blob/12fe0f8fd35226dadf3abc50de726537dc9ea475/tests/testthat/test-fit-init.R#L64-L69

This test is identical to the one above it called `"Pathfinder works as init"`, omitting `psis_resample = FALSE` suggested by the test title.

**Comment by jgabry** [comment]
Thanks for pointing that out! Should be fixed by https://github.com/stan-dev/cmdstanr/pull/1011.
