### ISSUE TITLE
cmdstan fails with "Error in !is.null(csv_contents$metadata$save_warmup) && csv_contents$metadata$save_warmup :    invalid 'y' type in 'x && y' "

### ISSUE THREAD

**Issue by fsdias** [stan-dev/cmdstanr#997]
System info:
Ubuntu 22.04, cmdstan 2.35, cmdstanr 0.7.1, R 4.4.0

Today I tried to run a new model with cmdstan 2.35 and the run ends with the following error message:

```
Error in !is.null(csv_contents$metadata$save_warmup) && csv_contents$metadata$save_warmup : 
  invalid 'y' type in 'x && y'
```

I get the same error message when I run:

```
fit_logistic_mcmc <- cmdstanr_example("logistic", chains = 2)
Compiling Stan program...
Error in !is.null(csv_contents$metadata$save_warmup) && csv_contents$metadata$save_warmup : 
  invalid 'y' type in 'x && y'
```

I deleted the "~/.cmdstan" folder, reinstalled cmdstan but the problem persists.

Maybe related to #971 ?

**Comment by andrjohns** [comment]
The current version of `cmdstanr` is 0.8.1, please upgrade

**Comment by fsdias** [comment]
0.8.1 is not yet available, just 0.8.0. 

I installed the development version cmdstanr_0.8.1.9000 and it works

Thanks

**Comment by andrjohns** [comment]
> 0.8.1 is not yet available, just 0.8.0. 
> 
> I installed the development version cmdstanr_0.8.1.9000 and it works
> 
> Thanks

https://discourse.mc-stan.org/t/cmdstanr-v0-8-1-release/35407

**Comment by fsdias** [comment]
I used the instructions I found here: https://mc-stan.org/cmdstanr/ which install 0.8.0. Using the code you posted on Discourse I was able to install 0.8.1.

**Comment by andrjohns** [comment]
Thanks for pointing that out, I've updated the old instructions in that link now
